// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: notifications.proto

package notificationsservice

import (
	"context"

	"github.com/suleymanmyradov/growth-server/services/gateway/services/notifications/rpc/notifications"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateNotificationRequest             = notifications.CreateNotificationRequest
	CreateNotificationResponse            = notifications.CreateNotificationResponse
	DeleteNotificationRequest             = notifications.DeleteNotificationRequest
	DeleteNotificationResponse            = notifications.DeleteNotificationResponse
	GetNotificationPreferencesRequest     = notifications.GetNotificationPreferencesRequest
	GetNotificationPreferencesResponse    = notifications.GetNotificationPreferencesResponse
	GetNotificationRequest                = notifications.GetNotificationRequest
	GetNotificationResponse               = notifications.GetNotificationResponse
	GetNotificationTypesRequest           = notifications.GetNotificationTypesRequest
	GetNotificationTypesResponse          = notifications.GetNotificationTypesResponse
	GetUnreadCountRequest                 = notifications.GetUnreadCountRequest
	GetUnreadCountResponse                = notifications.GetUnreadCountResponse
	ListNotificationsRequest              = notifications.ListNotificationsRequest
	ListNotificationsResponse             = notifications.ListNotificationsResponse
	MarkAllNotificationsReadRequest       = notifications.MarkAllNotificationsReadRequest
	MarkAllNotificationsReadResponse      = notifications.MarkAllNotificationsReadResponse
	MarkNotificationReadRequest           = notifications.MarkNotificationReadRequest
	MarkNotificationReadResponse          = notifications.MarkNotificationReadResponse
	Notification                          = notifications.Notification
	NotificationPreferences               = notifications.NotificationPreferences
	NotificationType                      = notifications.NotificationType
	UpdateNotificationPreferencesRequest  = notifications.UpdateNotificationPreferencesRequest
	UpdateNotificationPreferencesResponse = notifications.UpdateNotificationPreferencesResponse

	NotificationsService interface {
		// CRUD operations
		ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error)
		GetNotification(ctx context.Context, in *GetNotificationRequest, opts ...grpc.CallOption) (*GetNotificationResponse, error)
		CreateNotification(ctx context.Context, in *CreateNotificationRequest, opts ...grpc.CallOption) (*CreateNotificationResponse, error)
		DeleteNotification(ctx context.Context, in *DeleteNotificationRequest, opts ...grpc.CallOption) (*DeleteNotificationResponse, error)
		// Read status
		MarkNotificationRead(ctx context.Context, in *MarkNotificationReadRequest, opts ...grpc.CallOption) (*MarkNotificationReadResponse, error)
		MarkAllNotificationsRead(ctx context.Context, in *MarkAllNotificationsReadRequest, opts ...grpc.CallOption) (*MarkAllNotificationsReadResponse, error)
		GetUnreadCount(ctx context.Context, in *GetUnreadCountRequest, opts ...grpc.CallOption) (*GetUnreadCountResponse, error)
		// Preferences
		GetNotificationPreferences(ctx context.Context, in *GetNotificationPreferencesRequest, opts ...grpc.CallOption) (*GetNotificationPreferencesResponse, error)
		UpdateNotificationPreferences(ctx context.Context, in *UpdateNotificationPreferencesRequest, opts ...grpc.CallOption) (*UpdateNotificationPreferencesResponse, error)
		GetNotificationTypes(ctx context.Context, in *GetNotificationTypesRequest, opts ...grpc.CallOption) (*GetNotificationTypesResponse, error)
	}

	defaultNotificationsService struct {
		cli zrpc.Client
	}
)

func NewNotificationsService(cli zrpc.Client) NotificationsService {
	return &defaultNotificationsService{
		cli: cli,
	}
}

// CRUD operations
func (m *defaultNotificationsService) ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error) {
	client := notifications.NewNotificationsServiceClient(m.cli.Conn())
	return client.ListNotifications(ctx, in, opts...)
}

func (m *defaultNotificationsService) GetNotification(ctx context.Context, in *GetNotificationRequest, opts ...grpc.CallOption) (*GetNotificationResponse, error) {
	client := notifications.NewNotificationsServiceClient(m.cli.Conn())
	return client.GetNotification(ctx, in, opts...)
}

func (m *defaultNotificationsService) CreateNotification(ctx context.Context, in *CreateNotificationRequest, opts ...grpc.CallOption) (*CreateNotificationResponse, error) {
	client := notifications.NewNotificationsServiceClient(m.cli.Conn())
	return client.CreateNotification(ctx, in, opts...)
}

func (m *defaultNotificationsService) DeleteNotification(ctx context.Context, in *DeleteNotificationRequest, opts ...grpc.CallOption) (*DeleteNotificationResponse, error) {
	client := notifications.NewNotificationsServiceClient(m.cli.Conn())
	return client.DeleteNotification(ctx, in, opts...)
}

// Read status
func (m *defaultNotificationsService) MarkNotificationRead(ctx context.Context, in *MarkNotificationReadRequest, opts ...grpc.CallOption) (*MarkNotificationReadResponse, error) {
	client := notifications.NewNotificationsServiceClient(m.cli.Conn())
	return client.MarkNotificationRead(ctx, in, opts...)
}

func (m *defaultNotificationsService) MarkAllNotificationsRead(ctx context.Context, in *MarkAllNotificationsReadRequest, opts ...grpc.CallOption) (*MarkAllNotificationsReadResponse, error) {
	client := notifications.NewNotificationsServiceClient(m.cli.Conn())
	return client.MarkAllNotificationsRead(ctx, in, opts...)
}

func (m *defaultNotificationsService) GetUnreadCount(ctx context.Context, in *GetUnreadCountRequest, opts ...grpc.CallOption) (*GetUnreadCountResponse, error) {
	client := notifications.NewNotificationsServiceClient(m.cli.Conn())
	return client.GetUnreadCount(ctx, in, opts...)
}

// Preferences
func (m *defaultNotificationsService) GetNotificationPreferences(ctx context.Context, in *GetNotificationPreferencesRequest, opts ...grpc.CallOption) (*GetNotificationPreferencesResponse, error) {
	client := notifications.NewNotificationsServiceClient(m.cli.Conn())
	return client.GetNotificationPreferences(ctx, in, opts...)
}

func (m *defaultNotificationsService) UpdateNotificationPreferences(ctx context.Context, in *UpdateNotificationPreferencesRequest, opts ...grpc.CallOption) (*UpdateNotificationPreferencesResponse, error) {
	client := notifications.NewNotificationsServiceClient(m.cli.Conn())
	return client.UpdateNotificationPreferences(ctx, in, opts...)
}

func (m *defaultNotificationsService) GetNotificationTypes(ctx context.Context, in *GetNotificationTypesRequest, opts ...grpc.CallOption) (*GetNotificationTypesResponse, error) {
	client := notifications.NewNotificationsServiceClient(m.cli.Conn())
	return client.GetNotificationTypes(ctx, in, opts...)
}
