// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const archiveConversation = `-- name: ArchiveConversation :one
UPDATE conversations
SET archived = true, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, type, last_message, created_at, updated_at, archived
`

func (q *Queries) ArchiveConversation(ctx context.Context, iD uuid.UUID, userID uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, archiveConversation, iD, userID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.LastMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const countArchivedConversations = `-- name: CountArchivedConversations :one
SELECT count(*) FROM conversations
WHERE user_id = $1 AND archived = true
`

func (q *Queries) CountArchivedConversations(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countArchivedConversations, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConversations = `-- name: CountConversations :one
SELECT count(*) FROM conversations
WHERE user_id = $1 AND archived = false
`

func (q *Queries) CountConversations(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countConversations, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (user_id, title, type)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, type, last_message, created_at, updated_at, archived
`

func (q *Queries) CreateConversation(ctx context.Context, userID uuid.UUID, title string, type_ string) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, userID, title, type_)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.LastMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations
WHERE id = $1 AND user_id = $2
`

func (q *Queries) DeleteConversation(ctx context.Context, iD uuid.UUID, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, iD, userID)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, user_id, title, type, last_message, created_at, updated_at, archived
FROM conversations
WHERE id = $1 AND user_id = $2
`

func (q *Queries) GetConversation(ctx context.Context, iD uuid.UUID, userID uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, iD, userID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.LastMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const listArchivedConversations = `-- name: ListArchivedConversations :many
SELECT id, user_id, title, type, last_message, created_at, updated_at, archived
FROM conversations
WHERE user_id = $1 AND archived = true
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListArchivedConversations(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listArchivedConversations, userID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Type,
			&i.LastMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT id, user_id, title, type, last_message, created_at, updated_at, archived
FROM conversations
WHERE user_id = $1 AND archived = false
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListConversations(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations, userID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Type,
			&i.LastMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveConversation = `-- name: UnarchiveConversation :one
UPDATE conversations
SET archived = false, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, type, last_message, created_at, updated_at, archived
`

func (q *Queries) UnarchiveConversation(ctx context.Context, iD uuid.UUID, userID uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, unarchiveConversation, iD, userID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.LastMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const updateConversationLastMessage = `-- name: UpdateConversationLastMessage :one
UPDATE conversations
SET last_message = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, type, last_message, created_at, updated_at, archived
`

func (q *Queries) UpdateConversationLastMessage(ctx context.Context, iD uuid.UUID, lastMessage string) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationLastMessage, iD, lastMessage)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.LastMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const updateConversationTitle = `-- name: UpdateConversationTitle :one
UPDATE conversations
SET title = $2
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, title, type, last_message, created_at, updated_at, archived
`

func (q *Queries) UpdateConversationTitle(ctx context.Context, iD uuid.UUID, title string, userID uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationTitle, iD, title, userID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.LastMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}
