// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const archiveConversation = `-- name: ArchiveConversation :one
UPDATE conversations
SET archived = true, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, type, last_message, created_at, updated_at, archived
`

func (q *Queries) ArchiveConversation(ctx context.Context, iD uuid.UUID, userID uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, archiveConversation, iD, userID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.LastMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const countConversations = `-- name: CountConversations :one
SELECT count(*) FROM conversations
WHERE user_id = $1
  AND archived = $3
  AND (type = $2 OR $2 = '')
`

func (q *Queries) CountConversations(ctx context.Context, userID uuid.UUID, type_ string, archived bool) (int64, error) {
	row := q.db.QueryRow(ctx, countConversations, userID, type_, archived)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (user_id, title, type)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, type, last_message, created_at, updated_at, archived
`

func (q *Queries) CreateConversation(ctx context.Context, userID uuid.UUID, title string, type_ string) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, userID, title, type_)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.LastMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations
WHERE id = $1 AND user_id = $2
`

func (q *Queries) DeleteConversation(ctx context.Context, iD uuid.UUID, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, iD, userID)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, user_id, title, type, last_message, created_at, updated_at, archived
FROM conversations
WHERE id = $1 AND user_id = $2
`

func (q *Queries) GetConversation(ctx context.Context, iD uuid.UUID, userID uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, iD, userID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.LastMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, user_id, title, type, last_message, created_at, updated_at, archived
FROM conversations
WHERE user_id = $1
  AND archived = $5
  AND (type = $4 OR $4 = '')
ORDER BY updated_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListConversationsParams struct {
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
	Type     string    `db:"type" json:"type"`
	Archived bool      `db:"archived" json:"archived"`
}

// The archived flag is a required parameter, not a tri-state: false (the zero
// value, so also the default when a caller omits it) lists active
// conversations and true lists archived ones. Archived conversations used to
// leak into the default list because this query ignored the column entirely.
// CountConversations MUST take the same filters or the pagination totals
// describe a different result set than the page.
func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Type,
		arg.Archived,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Type,
			&i.LastMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveConversation = `-- name: UnarchiveConversation :one
UPDATE conversations
SET archived = false, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, type, last_message, created_at, updated_at, archived
`

func (q *Queries) UnarchiveConversation(ctx context.Context, iD uuid.UUID, userID uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, unarchiveConversation, iD, userID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.LastMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const updateConversationLastMessage = `-- name: UpdateConversationLastMessage :one
UPDATE conversations
SET last_message = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, type, last_message, created_at, updated_at, archived
`

func (q *Queries) UpdateConversationLastMessage(ctx context.Context, iD uuid.UUID, lastMessage string) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationLastMessage, iD, lastMessage)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.LastMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const updateConversationTitle = `-- name: UpdateConversationTitle :one
UPDATE conversations
SET title = $2
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, title, type, last_message, created_at, updated_at, archived
`

func (q *Queries) UpdateConversationTitle(ctx context.Context, iD uuid.UUID, title string, userID uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationTitle, iD, title, userID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.LastMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}
