// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: services/microservices/ai-coach/api/v1/ai-coach.proto

package aicoach

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Check-in Feedback
type CheckInFeedbackRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HabitId              string                 `protobuf:"bytes,2,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	HabitName            string                 `protobuf:"bytes,3,opt,name=habit_name,json=habitName,proto3" json:"habit_name,omitempty"`
	Status               string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // completed | missed
	Mood                 string                 `protobuf:"bytes,5,opt,name=mood,proto3" json:"mood,omitempty"`
	Energy               string                 `protobuf:"bytes,6,opt,name=energy,proto3" json:"energy,omitempty"`
	Blocker              string                 `protobuf:"bytes,7,opt,name=blocker,proto3" json:"blocker,omitempty"`
	Note                 string                 `protobuf:"bytes,8,opt,name=note,proto3" json:"note,omitempty"`
	Streak               int32                  `protobuf:"varint,9,opt,name=streak,proto3" json:"streak,omitempty"`
	AccountabilityStyle  string                 `protobuf:"bytes,10,opt,name=accountability_style,json=accountabilityStyle,proto3" json:"accountability_style,omitempty"`
	PreferredTone        string                 `protobuf:"bytes,11,opt,name=preferred_tone,json=preferredTone,proto3" json:"preferred_tone,omitempty"`
	DifficultyPreference string                 `protobuf:"bytes,12,opt,name=difficulty_preference,json=difficultyPreference,proto3" json:"difficulty_preference,omitempty"`
	CommonBlockers       []string               `protobuf:"bytes,13,rep,name=common_blockers,json=commonBlockers,proto3" json:"common_blockers,omitempty"`
	RecentPattern        string                 `protobuf:"bytes,14,opt,name=recent_pattern,json=recentPattern,proto3" json:"recent_pattern,omitempty"`
	GoalTitle            string                 `protobuf:"bytes,15,opt,name=goal_title,json=goalTitle,proto3" json:"goal_title,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CheckInFeedbackRequest) Reset() {
	*x = CheckInFeedbackRequest{}
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInFeedbackRequest) ProtoMessage() {}

func (x *CheckInFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInFeedbackRequest.ProtoReflect.Descriptor instead.
func (*CheckInFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescGZIP(), []int{0}
}

func (x *CheckInFeedbackRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckInFeedbackRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *CheckInFeedbackRequest) GetHabitName() string {
	if x != nil {
		return x.HabitName
	}
	return ""
}

func (x *CheckInFeedbackRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckInFeedbackRequest) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *CheckInFeedbackRequest) GetEnergy() string {
	if x != nil {
		return x.Energy
	}
	return ""
}

func (x *CheckInFeedbackRequest) GetBlocker() string {
	if x != nil {
		return x.Blocker
	}
	return ""
}

func (x *CheckInFeedbackRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CheckInFeedbackRequest) GetStreak() int32 {
	if x != nil {
		return x.Streak
	}
	return 0
}

func (x *CheckInFeedbackRequest) GetAccountabilityStyle() string {
	if x != nil {
		return x.AccountabilityStyle
	}
	return ""
}

func (x *CheckInFeedbackRequest) GetPreferredTone() string {
	if x != nil {
		return x.PreferredTone
	}
	return ""
}

func (x *CheckInFeedbackRequest) GetDifficultyPreference() string {
	if x != nil {
		return x.DifficultyPreference
	}
	return ""
}

func (x *CheckInFeedbackRequest) GetCommonBlockers() []string {
	if x != nil {
		return x.CommonBlockers
	}
	return nil
}

func (x *CheckInFeedbackRequest) GetRecentPattern() string {
	if x != nil {
		return x.RecentPattern
	}
	return ""
}

func (x *CheckInFeedbackRequest) GetGoalTitle() string {
	if x != nil {
		return x.GoalTitle
	}
	return ""
}

type CheckInFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feedback      string                 `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInFeedbackResponse) Reset() {
	*x = CheckInFeedbackResponse{}
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInFeedbackResponse) ProtoMessage() {}

func (x *CheckInFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInFeedbackResponse.ProtoReflect.Descriptor instead.
func (*CheckInFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescGZIP(), []int{1}
}

func (x *CheckInFeedbackResponse) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

// Personalized Coaching
type PersonalizedCoachingRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserId                string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserMessage           string                 `protobuf:"bytes,2,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	AccountabilityStyle   string                 `protobuf:"bytes,3,opt,name=accountability_style,json=accountabilityStyle,proto3" json:"accountability_style,omitempty"`
	PreferredTone         string                 `protobuf:"bytes,4,opt,name=preferred_tone,json=preferredTone,proto3" json:"preferred_tone,omitempty"`
	DifficultyPreference  string                 `protobuf:"bytes,5,opt,name=difficulty_preference,json=difficultyPreference,proto3" json:"difficulty_preference,omitempty"`
	ActiveGoals           []string               `protobuf:"bytes,6,rep,name=active_goals,json=activeGoals,proto3" json:"active_goals,omitempty"`
	ActiveHabits          []string               `protobuf:"bytes,7,rep,name=active_habits,json=activeHabits,proto3" json:"active_habits,omitempty"`
	RecentCheckInsSummary string                 `protobuf:"bytes,8,opt,name=recent_check_ins_summary,json=recentCheckInsSummary,proto3" json:"recent_check_ins_summary,omitempty"`
	CommonBlockers        []string               `protobuf:"bytes,9,rep,name=common_blockers,json=commonBlockers,proto3" json:"common_blockers,omitempty"`
	PatternInsights       map[string]string      `protobuf:"bytes,10,rep,name=pattern_insights,json=patternInsights,proto3" json:"pattern_insights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PersonalizedCoachingRequest) Reset() {
	*x = PersonalizedCoachingRequest{}
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalizedCoachingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalizedCoachingRequest) ProtoMessage() {}

func (x *PersonalizedCoachingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalizedCoachingRequest.ProtoReflect.Descriptor instead.
func (*PersonalizedCoachingRequest) Descriptor() ([]byte, []int) {
	return file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescGZIP(), []int{2}
}

func (x *PersonalizedCoachingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PersonalizedCoachingRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

func (x *PersonalizedCoachingRequest) GetAccountabilityStyle() string {
	if x != nil {
		return x.AccountabilityStyle
	}
	return ""
}

func (x *PersonalizedCoachingRequest) GetPreferredTone() string {
	if x != nil {
		return x.PreferredTone
	}
	return ""
}

func (x *PersonalizedCoachingRequest) GetDifficultyPreference() string {
	if x != nil {
		return x.DifficultyPreference
	}
	return ""
}

func (x *PersonalizedCoachingRequest) GetActiveGoals() []string {
	if x != nil {
		return x.ActiveGoals
	}
	return nil
}

func (x *PersonalizedCoachingRequest) GetActiveHabits() []string {
	if x != nil {
		return x.ActiveHabits
	}
	return nil
}

func (x *PersonalizedCoachingRequest) GetRecentCheckInsSummary() string {
	if x != nil {
		return x.RecentCheckInsSummary
	}
	return ""
}

func (x *PersonalizedCoachingRequest) GetCommonBlockers() []string {
	if x != nil {
		return x.CommonBlockers
	}
	return nil
}

func (x *PersonalizedCoachingRequest) GetPatternInsights() map[string]string {
	if x != nil {
		return x.PatternInsights
	}
	return nil
}

type PersonalizedCoachingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CoachingResponse string                 `protobuf:"bytes,1,opt,name=coaching_response,json=coachingResponse,proto3" json:"coaching_response,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PersonalizedCoachingResponse) Reset() {
	*x = PersonalizedCoachingResponse{}
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalizedCoachingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalizedCoachingResponse) ProtoMessage() {}

func (x *PersonalizedCoachingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalizedCoachingResponse.ProtoReflect.Descriptor instead.
func (*PersonalizedCoachingResponse) Descriptor() ([]byte, []int) {
	return file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescGZIP(), []int{3}
}

func (x *PersonalizedCoachingResponse) GetCoachingResponse() string {
	if x != nil {
		return x.CoachingResponse
	}
	return ""
}

// Weekly Review
type HabitBreakdown struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HabitId        string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	HabitName      string                 `protobuf:"bytes,2,opt,name=habit_name,json=habitName,proto3" json:"habit_name,omitempty"`
	Category       string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	CompletedCount int32                  `protobuf:"varint,4,opt,name=completed_count,json=completedCount,proto3" json:"completed_count,omitempty"`
	MissedCount    int32                  `protobuf:"varint,5,opt,name=missed_count,json=missedCount,proto3" json:"missed_count,omitempty"`
	CompletionRate float32                `protobuf:"fixed32,6,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HabitBreakdown) Reset() {
	*x = HabitBreakdown{}
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HabitBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HabitBreakdown) ProtoMessage() {}

func (x *HabitBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HabitBreakdown.ProtoReflect.Descriptor instead.
func (*HabitBreakdown) Descriptor() ([]byte, []int) {
	return file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescGZIP(), []int{4}
}

func (x *HabitBreakdown) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *HabitBreakdown) GetHabitName() string {
	if x != nil {
		return x.HabitName
	}
	return ""
}

func (x *HabitBreakdown) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *HabitBreakdown) GetCompletedCount() int32 {
	if x != nil {
		return x.CompletedCount
	}
	return 0
}

func (x *HabitBreakdown) GetMissedCount() int32 {
	if x != nil {
		return x.MissedCount
	}
	return 0
}

func (x *HabitBreakdown) GetCompletionRate() float32 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

type BlockerStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocker       string                 `protobuf:"bytes,1,opt,name=blocker,proto3" json:"blocker,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockerStat) Reset() {
	*x = BlockerStat{}
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockerStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockerStat) ProtoMessage() {}

func (x *BlockerStat) ProtoReflect() protoreflect.Message {
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockerStat.ProtoReflect.Descriptor instead.
func (*BlockerStat) Descriptor() ([]byte, []int) {
	return file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescGZIP(), []int{5}
}

func (x *BlockerStat) GetBlocker() string {
	if x != nil {
		return x.Blocker
	}
	return ""
}

func (x *BlockerStat) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MoodStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mood          string                 `protobuf:"bytes,1,opt,name=mood,proto3" json:"mood,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoodStat) Reset() {
	*x = MoodStat{}
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoodStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoodStat) ProtoMessage() {}

func (x *MoodStat) ProtoReflect() protoreflect.Message {
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoodStat.ProtoReflect.Descriptor instead.
func (*MoodStat) Descriptor() ([]byte, []int) {
	return file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescGZIP(), []int{6}
}

func (x *MoodStat) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *MoodStat) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type EnergyStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Energy        string                 `protobuf:"bytes,1,opt,name=energy,proto3" json:"energy,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnergyStat) Reset() {
	*x = EnergyStat{}
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnergyStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnergyStat) ProtoMessage() {}

func (x *EnergyStat) ProtoReflect() protoreflect.Message {
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnergyStat.ProtoReflect.Descriptor instead.
func (*EnergyStat) Descriptor() ([]byte, []int) {
	return file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescGZIP(), []int{7}
}

func (x *EnergyStat) GetEnergy() string {
	if x != nil {
		return x.Energy
	}
	return ""
}

func (x *EnergyStat) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type WeeklyReviewAdjustment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HabitId        string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	HabitName      string                 `protobuf:"bytes,2,opt,name=habit_name,json=habitName,proto3" json:"habit_name,omitempty"`
	Reason         string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Suggestion     string                 `protobuf:"bytes,4,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	AdjustmentType string                 `protobuf:"bytes,5,opt,name=adjustment_type,json=adjustmentType,proto3" json:"adjustment_type,omitempty"` // reduce_difficulty | change_time | clarify_plan | keep_same | pause_habit
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WeeklyReviewAdjustment) Reset() {
	*x = WeeklyReviewAdjustment{}
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklyReviewAdjustment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyReviewAdjustment) ProtoMessage() {}

func (x *WeeklyReviewAdjustment) ProtoReflect() protoreflect.Message {
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyReviewAdjustment.ProtoReflect.Descriptor instead.
func (*WeeklyReviewAdjustment) Descriptor() ([]byte, []int) {
	return file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescGZIP(), []int{8}
}

func (x *WeeklyReviewAdjustment) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *WeeklyReviewAdjustment) GetHabitName() string {
	if x != nil {
		return x.HabitName
	}
	return ""
}

func (x *WeeklyReviewAdjustment) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *WeeklyReviewAdjustment) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

func (x *WeeklyReviewAdjustment) GetAdjustmentType() string {
	if x != nil {
		return x.AdjustmentType
	}
	return ""
}

type NextWeekPlan struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Focus           string                 `protobuf:"bytes,1,opt,name=focus,proto3" json:"focus,omitempty"`
	Commitments     []string               `protobuf:"bytes,2,rep,name=commitments,proto3" json:"commitments,omitempty"`
	Risks           []string               `protobuf:"bytes,3,rep,name=risks,proto3" json:"risks,omitempty"`
	RecoveryActions []string               `protobuf:"bytes,4,rep,name=recovery_actions,json=recoveryActions,proto3" json:"recovery_actions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NextWeekPlan) Reset() {
	*x = NextWeekPlan{}
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextWeekPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextWeekPlan) ProtoMessage() {}

func (x *NextWeekPlan) ProtoReflect() protoreflect.Message {
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextWeekPlan.ProtoReflect.Descriptor instead.
func (*NextWeekPlan) Descriptor() ([]byte, []int) {
	return file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescGZIP(), []int{9}
}

func (x *NextWeekPlan) GetFocus() string {
	if x != nil {
		return x.Focus
	}
	return ""
}

func (x *NextWeekPlan) GetCommitments() []string {
	if x != nil {
		return x.Commitments
	}
	return nil
}

func (x *NextWeekPlan) GetRisks() []string {
	if x != nil {
		return x.Risks
	}
	return nil
}

func (x *NextWeekPlan) GetRecoveryActions() []string {
	if x != nil {
		return x.RecoveryActions
	}
	return nil
}

type WeeklyReviewRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountabilityStyle  string                 `protobuf:"bytes,2,opt,name=accountability_style,json=accountabilityStyle,proto3" json:"accountability_style,omitempty"`
	PreferredTone        string                 `protobuf:"bytes,3,opt,name=preferred_tone,json=preferredTone,proto3" json:"preferred_tone,omitempty"`
	DifficultyPreference string                 `protobuf:"bytes,4,opt,name=difficulty_preference,json=difficultyPreference,proto3" json:"difficulty_preference,omitempty"`
	CommonBlockers       []string               `protobuf:"bytes,5,rep,name=common_blockers,json=commonBlockers,proto3" json:"common_blockers,omitempty"`
	Goals                []string               `protobuf:"bytes,6,rep,name=goals,proto3" json:"goals,omitempty"`
	TotalHabits          int32                  `protobuf:"varint,7,opt,name=total_habits,json=totalHabits,proto3" json:"total_habits,omitempty"`
	CompletionRate       float32                `protobuf:"fixed32,8,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`
	CompletedCheckIns    int32                  `protobuf:"varint,9,opt,name=completed_check_ins,json=completedCheckIns,proto3" json:"completed_check_ins,omitempty"`
	MissedCheckIns       int32                  `protobuf:"varint,10,opt,name=missed_check_ins,json=missedCheckIns,proto3" json:"missed_check_ins,omitempty"`
	BestDay              string                 `protobuf:"bytes,11,opt,name=best_day,json=bestDay,proto3" json:"best_day,omitempty"`
	HardestDay           string                 `protobuf:"bytes,12,opt,name=hardest_day,json=hardestDay,proto3" json:"hardest_day,omitempty"`
	TopBlocker           string                 `protobuf:"bytes,13,opt,name=top_blocker,json=topBlocker,proto3" json:"top_blocker,omitempty"`
	HabitBreakdowns      []*HabitBreakdown      `protobuf:"bytes,14,rep,name=habit_breakdowns,json=habitBreakdowns,proto3" json:"habit_breakdowns,omitempty"`
	BlockerStats         []*BlockerStat         `protobuf:"bytes,15,rep,name=blocker_stats,json=blockerStats,proto3" json:"blocker_stats,omitempty"`
	MoodStats            []*MoodStat            `protobuf:"bytes,16,rep,name=mood_stats,json=moodStats,proto3" json:"mood_stats,omitempty"`
	EnergyStats          []*EnergyStat          `protobuf:"bytes,17,rep,name=energy_stats,json=energyStats,proto3" json:"energy_stats,omitempty"`
	DetectedPatterns     []string               `protobuf:"bytes,18,rep,name=detected_patterns,json=detectedPatterns,proto3" json:"detected_patterns,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WeeklyReviewRequest) Reset() {
	*x = WeeklyReviewRequest{}
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklyReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyReviewRequest) ProtoMessage() {}

func (x *WeeklyReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyReviewRequest.ProtoReflect.Descriptor instead.
func (*WeeklyReviewRequest) Descriptor() ([]byte, []int) {
	return file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescGZIP(), []int{10}
}

func (x *WeeklyReviewRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WeeklyReviewRequest) GetAccountabilityStyle() string {
	if x != nil {
		return x.AccountabilityStyle
	}
	return ""
}

func (x *WeeklyReviewRequest) GetPreferredTone() string {
	if x != nil {
		return x.PreferredTone
	}
	return ""
}

func (x *WeeklyReviewRequest) GetDifficultyPreference() string {
	if x != nil {
		return x.DifficultyPreference
	}
	return ""
}

func (x *WeeklyReviewRequest) GetCommonBlockers() []string {
	if x != nil {
		return x.CommonBlockers
	}
	return nil
}

func (x *WeeklyReviewRequest) GetGoals() []string {
	if x != nil {
		return x.Goals
	}
	return nil
}

func (x *WeeklyReviewRequest) GetTotalHabits() int32 {
	if x != nil {
		return x.TotalHabits
	}
	return 0
}

func (x *WeeklyReviewRequest) GetCompletionRate() float32 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

func (x *WeeklyReviewRequest) GetCompletedCheckIns() int32 {
	if x != nil {
		return x.CompletedCheckIns
	}
	return 0
}

func (x *WeeklyReviewRequest) GetMissedCheckIns() int32 {
	if x != nil {
		return x.MissedCheckIns
	}
	return 0
}

func (x *WeeklyReviewRequest) GetBestDay() string {
	if x != nil {
		return x.BestDay
	}
	return ""
}

func (x *WeeklyReviewRequest) GetHardestDay() string {
	if x != nil {
		return x.HardestDay
	}
	return ""
}

func (x *WeeklyReviewRequest) GetTopBlocker() string {
	if x != nil {
		return x.TopBlocker
	}
	return ""
}

func (x *WeeklyReviewRequest) GetHabitBreakdowns() []*HabitBreakdown {
	if x != nil {
		return x.HabitBreakdowns
	}
	return nil
}

func (x *WeeklyReviewRequest) GetBlockerStats() []*BlockerStat {
	if x != nil {
		return x.BlockerStats
	}
	return nil
}

func (x *WeeklyReviewRequest) GetMoodStats() []*MoodStat {
	if x != nil {
		return x.MoodStats
	}
	return nil
}

func (x *WeeklyReviewRequest) GetEnergyStats() []*EnergyStat {
	if x != nil {
		return x.EnergyStats
	}
	return nil
}

func (x *WeeklyReviewRequest) GetDetectedPatterns() []string {
	if x != nil {
		return x.DetectedPatterns
	}
	return nil
}

type WeeklyReviewResponse struct {
	state                protoimpl.MessageState    `protogen:"open.v1"`
	AiSummary            string                    `protobuf:"bytes,1,opt,name=ai_summary,json=aiSummary,proto3" json:"ai_summary,omitempty"`
	SuggestedAdjustments []*WeeklyReviewAdjustment `protobuf:"bytes,2,rep,name=suggested_adjustments,json=suggestedAdjustments,proto3" json:"suggested_adjustments,omitempty"`
	NextWeekPlan         *NextWeekPlan             `protobuf:"bytes,3,opt,name=next_week_plan,json=nextWeekPlan,proto3" json:"next_week_plan,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WeeklyReviewResponse) Reset() {
	*x = WeeklyReviewResponse{}
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklyReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyReviewResponse) ProtoMessage() {}

func (x *WeeklyReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyReviewResponse.ProtoReflect.Descriptor instead.
func (*WeeklyReviewResponse) Descriptor() ([]byte, []int) {
	return file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescGZIP(), []int{11}
}

func (x *WeeklyReviewResponse) GetAiSummary() string {
	if x != nil {
		return x.AiSummary
	}
	return ""
}

func (x *WeeklyReviewResponse) GetSuggestedAdjustments() []*WeeklyReviewAdjustment {
	if x != nil {
		return x.SuggestedAdjustments
	}
	return nil
}

func (x *WeeklyReviewResponse) GetNextWeekPlan() *NextWeekPlan {
	if x != nil {
		return x.NextWeekPlan
	}
	return nil
}

// Streaming weekly review
type WeeklyReviewStreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`            // text delta (summary text as it's generated)
	Complete      bool                   `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`     // true when the stream is finished
	Review        *WeeklyReviewResponse  `protobuf:"bytes,3,opt,name=review,proto3" json:"review,omitempty"`          // full structured response (only set when complete=true)
	Finalizing    bool                   `protobuf:"varint,4,opt,name=finalizing,proto3" json:"finalizing,omitempty"` // true when text is done, backend is parsing JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeeklyReviewStreamChunk) Reset() {
	*x = WeeklyReviewStreamChunk{}
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklyReviewStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyReviewStreamChunk) ProtoMessage() {}

func (x *WeeklyReviewStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyReviewStreamChunk.ProtoReflect.Descriptor instead.
func (*WeeklyReviewStreamChunk) Descriptor() ([]byte, []int) {
	return file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescGZIP(), []int{12}
}

func (x *WeeklyReviewStreamChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *WeeklyReviewStreamChunk) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *WeeklyReviewStreamChunk) GetReview() *WeeklyReviewResponse {
	if x != nil {
		return x.Review
	}
	return nil
}

func (x *WeeklyReviewStreamChunk) GetFinalizing() bool {
	if x != nil {
		return x.Finalizing
	}
	return false
}

var File_services_microservices_ai_coach_api_v1_ai_coach_proto protoreflect.FileDescriptor

const file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDesc = "" +
	"\n" +
	"5services/microservices/ai-coach/api/v1/ai-coach.proto\x12\aaicoach\"\xf3\x03\n" +
	"\x16CheckInFeedbackRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bhabit_id\x18\x02 \x01(\tR\ahabitId\x12\x1d\n" +
	"\n" +
	"habit_name\x18\x03 \x01(\tR\thabitName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04mood\x18\x05 \x01(\tR\x04mood\x12\x16\n" +
	"\x06energy\x18\x06 \x01(\tR\x06energy\x12\x18\n" +
	"\ablocker\x18\a \x01(\tR\ablocker\x12\x12\n" +
	"\x04note\x18\b \x01(\tR\x04note\x12\x16\n" +
	"\x06streak\x18\t \x01(\x05R\x06streak\x121\n" +
	"\x14accountability_style\x18\n" +
	" \x01(\tR\x13accountabilityStyle\x12%\n" +
	"\x0epreferred_tone\x18\v \x01(\tR\rpreferredTone\x123\n" +
	"\x15difficulty_preference\x18\f \x01(\tR\x14difficultyPreference\x12'\n" +
	"\x0fcommon_blockers\x18\r \x03(\tR\x0ecommonBlockers\x12%\n" +
	"\x0erecent_pattern\x18\x0e \x01(\tR\rrecentPattern\x12\x1d\n" +
	"\n" +
	"goal_title\x18\x0f \x01(\tR\tgoalTitle\"5\n" +
	"\x17CheckInFeedbackResponse\x12\x1a\n" +
	"\bfeedback\x18\x01 \x01(\tR\bfeedback\"\xbc\x04\n" +
	"\x1bPersonalizedCoachingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fuser_message\x18\x02 \x01(\tR\vuserMessage\x121\n" +
	"\x14accountability_style\x18\x03 \x01(\tR\x13accountabilityStyle\x12%\n" +
	"\x0epreferred_tone\x18\x04 \x01(\tR\rpreferredTone\x123\n" +
	"\x15difficulty_preference\x18\x05 \x01(\tR\x14difficultyPreference\x12!\n" +
	"\factive_goals\x18\x06 \x03(\tR\vactiveGoals\x12#\n" +
	"\ractive_habits\x18\a \x03(\tR\factiveHabits\x127\n" +
	"\x18recent_check_ins_summary\x18\b \x01(\tR\x15recentCheckInsSummary\x12'\n" +
	"\x0fcommon_blockers\x18\t \x03(\tR\x0ecommonBlockers\x12d\n" +
	"\x10pattern_insights\x18\n" +
	" \x03(\v29.aicoach.PersonalizedCoachingRequest.PatternInsightsEntryR\x0fpatternInsights\x1aB\n" +
	"\x14PatternInsightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x1cPersonalizedCoachingResponse\x12+\n" +
	"\x11coaching_response\x18\x01 \x01(\tR\x10coachingResponse\"\xdb\x01\n" +
	"\x0eHabitBreakdown\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\x12\x1d\n" +
	"\n" +
	"habit_name\x18\x02 \x01(\tR\thabitName\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12'\n" +
	"\x0fcompleted_count\x18\x04 \x01(\x05R\x0ecompletedCount\x12!\n" +
	"\fmissed_count\x18\x05 \x01(\x05R\vmissedCount\x12'\n" +
	"\x0fcompletion_rate\x18\x06 \x01(\x02R\x0ecompletionRate\"=\n" +
	"\vBlockerStat\x12\x18\n" +
	"\ablocker\x18\x01 \x01(\tR\ablocker\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"4\n" +
	"\bMoodStat\x12\x12\n" +
	"\x04mood\x18\x01 \x01(\tR\x04mood\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\":\n" +
	"\n" +
	"EnergyStat\x12\x16\n" +
	"\x06energy\x18\x01 \x01(\tR\x06energy\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xb3\x01\n" +
	"\x16WeeklyReviewAdjustment\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\x12\x1d\n" +
	"\n" +
	"habit_name\x18\x02 \x01(\tR\thabitName\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x04 \x01(\tR\n" +
	"suggestion\x12'\n" +
	"\x0fadjustment_type\x18\x05 \x01(\tR\x0eadjustmentType\"\x87\x01\n" +
	"\fNextWeekPlan\x12\x14\n" +
	"\x05focus\x18\x01 \x01(\tR\x05focus\x12 \n" +
	"\vcommitments\x18\x02 \x03(\tR\vcommitments\x12\x14\n" +
	"\x05risks\x18\x03 \x03(\tR\x05risks\x12)\n" +
	"\x10recovery_actions\x18\x04 \x03(\tR\x0frecoveryActions\"\x95\x06\n" +
	"\x13WeeklyReviewRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\x14accountability_style\x18\x02 \x01(\tR\x13accountabilityStyle\x12%\n" +
	"\x0epreferred_tone\x18\x03 \x01(\tR\rpreferredTone\x123\n" +
	"\x15difficulty_preference\x18\x04 \x01(\tR\x14difficultyPreference\x12'\n" +
	"\x0fcommon_blockers\x18\x05 \x03(\tR\x0ecommonBlockers\x12\x14\n" +
	"\x05goals\x18\x06 \x03(\tR\x05goals\x12!\n" +
	"\ftotal_habits\x18\a \x01(\x05R\vtotalHabits\x12'\n" +
	"\x0fcompletion_rate\x18\b \x01(\x02R\x0ecompletionRate\x12.\n" +
	"\x13completed_check_ins\x18\t \x01(\x05R\x11completedCheckIns\x12(\n" +
	"\x10missed_check_ins\x18\n" +
	" \x01(\x05R\x0emissedCheckIns\x12\x19\n" +
	"\bbest_day\x18\v \x01(\tR\abestDay\x12\x1f\n" +
	"\vhardest_day\x18\f \x01(\tR\n" +
	"hardestDay\x12\x1f\n" +
	"\vtop_blocker\x18\r \x01(\tR\n" +
	"topBlocker\x12B\n" +
	"\x10habit_breakdowns\x18\x0e \x03(\v2\x17.aicoach.HabitBreakdownR\x0fhabitBreakdowns\x129\n" +
	"\rblocker_stats\x18\x0f \x03(\v2\x14.aicoach.BlockerStatR\fblockerStats\x120\n" +
	"\n" +
	"mood_stats\x18\x10 \x03(\v2\x11.aicoach.MoodStatR\tmoodStats\x126\n" +
	"\fenergy_stats\x18\x11 \x03(\v2\x13.aicoach.EnergyStatR\venergyStats\x12+\n" +
	"\x11detected_patterns\x18\x12 \x03(\tR\x10detectedPatterns\"\xc8\x01\n" +
	"\x14WeeklyReviewResponse\x12\x1d\n" +
	"\n" +
	"ai_summary\x18\x01 \x01(\tR\taiSummary\x12T\n" +
	"\x15suggested_adjustments\x18\x02 \x03(\v2\x1f.aicoach.WeeklyReviewAdjustmentR\x14suggestedAdjustments\x12;\n" +
	"\x0enext_week_plan\x18\x03 \x01(\v2\x15.aicoach.NextWeekPlanR\fnextWeekPlan\"\xa2\x01\n" +
	"\x17WeeklyReviewStreamChunk\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x1a\n" +
	"\bcomplete\x18\x02 \x01(\bR\bcomplete\x125\n" +
	"\x06review\x18\x03 \x01(\v2\x1d.aicoach.WeeklyReviewResponseR\x06review\x12\x1e\n" +
	"\n" +
	"finalizing\x18\x04 \x01(\bR\n" +
	"finalizing2\x88\x03\n" +
	"\x0eAICoachService\x12\\\n" +
	"\x17GenerateCheckInFeedback\x12\x1f.aicoach.CheckInFeedbackRequest\x1a .aicoach.CheckInFeedbackResponse\x12k\n" +
	"\x1cGeneratePersonalizedCoaching\x12$.aicoach.PersonalizedCoachingRequest\x1a%.aicoach.PersonalizedCoachingResponse\x12S\n" +
	"\x14GenerateWeeklyReview\x12\x1c.aicoach.WeeklyReviewRequest\x1a\x1d.aicoach.WeeklyReviewResponse\x12V\n" +
	"\x12StreamWeeklyReview\x12\x1c.aicoach.WeeklyReviewRequest\x1a .aicoach.WeeklyReviewStreamChunk0\x01B\vZ\t./aicoachb\x06proto3"

var (
	file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescOnce sync.Once
	file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescData []byte
)

func file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescGZIP() []byte {
	file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescOnce.Do(func() {
		file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDesc), len(file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDesc)))
	})
	return file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDescData
}

var file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_services_microservices_ai_coach_api_v1_ai_coach_proto_goTypes = []any{
	(*CheckInFeedbackRequest)(nil),       // 0: aicoach.CheckInFeedbackRequest
	(*CheckInFeedbackResponse)(nil),      // 1: aicoach.CheckInFeedbackResponse
	(*PersonalizedCoachingRequest)(nil),  // 2: aicoach.PersonalizedCoachingRequest
	(*PersonalizedCoachingResponse)(nil), // 3: aicoach.PersonalizedCoachingResponse
	(*HabitBreakdown)(nil),               // 4: aicoach.HabitBreakdown
	(*BlockerStat)(nil),                  // 5: aicoach.BlockerStat
	(*MoodStat)(nil),                     // 6: aicoach.MoodStat
	(*EnergyStat)(nil),                   // 7: aicoach.EnergyStat
	(*WeeklyReviewAdjustment)(nil),       // 8: aicoach.WeeklyReviewAdjustment
	(*NextWeekPlan)(nil),                 // 9: aicoach.NextWeekPlan
	(*WeeklyReviewRequest)(nil),          // 10: aicoach.WeeklyReviewRequest
	(*WeeklyReviewResponse)(nil),         // 11: aicoach.WeeklyReviewResponse
	(*WeeklyReviewStreamChunk)(nil),      // 12: aicoach.WeeklyReviewStreamChunk
	nil,                                  // 13: aicoach.PersonalizedCoachingRequest.PatternInsightsEntry
}
var file_services_microservices_ai_coach_api_v1_ai_coach_proto_depIdxs = []int32{
	13, // 0: aicoach.PersonalizedCoachingRequest.pattern_insights:type_name -> aicoach.PersonalizedCoachingRequest.PatternInsightsEntry
	4,  // 1: aicoach.WeeklyReviewRequest.habit_breakdowns:type_name -> aicoach.HabitBreakdown
	5,  // 2: aicoach.WeeklyReviewRequest.blocker_stats:type_name -> aicoach.BlockerStat
	6,  // 3: aicoach.WeeklyReviewRequest.mood_stats:type_name -> aicoach.MoodStat
	7,  // 4: aicoach.WeeklyReviewRequest.energy_stats:type_name -> aicoach.EnergyStat
	8,  // 5: aicoach.WeeklyReviewResponse.suggested_adjustments:type_name -> aicoach.WeeklyReviewAdjustment
	9,  // 6: aicoach.WeeklyReviewResponse.next_week_plan:type_name -> aicoach.NextWeekPlan
	11, // 7: aicoach.WeeklyReviewStreamChunk.review:type_name -> aicoach.WeeklyReviewResponse
	0,  // 8: aicoach.AICoachService.GenerateCheckInFeedback:input_type -> aicoach.CheckInFeedbackRequest
	2,  // 9: aicoach.AICoachService.GeneratePersonalizedCoaching:input_type -> aicoach.PersonalizedCoachingRequest
	10, // 10: aicoach.AICoachService.GenerateWeeklyReview:input_type -> aicoach.WeeklyReviewRequest
	10, // 11: aicoach.AICoachService.StreamWeeklyReview:input_type -> aicoach.WeeklyReviewRequest
	1,  // 12: aicoach.AICoachService.GenerateCheckInFeedback:output_type -> aicoach.CheckInFeedbackResponse
	3,  // 13: aicoach.AICoachService.GeneratePersonalizedCoaching:output_type -> aicoach.PersonalizedCoachingResponse
	11, // 14: aicoach.AICoachService.GenerateWeeklyReview:output_type -> aicoach.WeeklyReviewResponse
	12, // 15: aicoach.AICoachService.StreamWeeklyReview:output_type -> aicoach.WeeklyReviewStreamChunk
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_services_microservices_ai_coach_api_v1_ai_coach_proto_init() }
func file_services_microservices_ai_coach_api_v1_ai_coach_proto_init() {
	if File_services_microservices_ai_coach_api_v1_ai_coach_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDesc), len(file_services_microservices_ai_coach_api_v1_ai_coach_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_microservices_ai_coach_api_v1_ai_coach_proto_goTypes,
		DependencyIndexes: file_services_microservices_ai_coach_api_v1_ai_coach_proto_depIdxs,
		MessageInfos:      file_services_microservices_ai_coach_api_v1_ai_coach_proto_msgTypes,
	}.Build()
	File_services_microservices_ai_coach_api_v1_ai_coach_proto = out.File
	file_services_microservices_ai_coach_api_v1_ai_coach_proto_goTypes = nil
	file_services_microservices_ai_coach_api_v1_ai_coach_proto_depIdxs = nil
}
