// Code scaffolded by goctl. Safe to edit.
// goctl 1.10.1

package main

import (
	"flag"
	"fmt"
	"net/http"

	"github.com/suleymanmyradov/growth-server/pkg/configsafe"
	"github.com/suleymanmyradov/growth-server/services/gateway/growth/internal/config"
	"github.com/suleymanmyradov/growth-server/services/gateway/growth/internal/handler"
	"github.com/suleymanmyradov/growth-server/services/gateway/growth/internal/handler/files"
	"github.com/suleymanmyradov/growth-server/services/gateway/growth/internal/middleware"
	"github.com/suleymanmyradov/growth-server/services/gateway/growth/internal/svc"

	"github.com/zeromicro/go-zero/core/conf"
	"github.com/zeromicro/go-zero/core/logx"
	"github.com/zeromicro/go-zero/rest"
)

var configFile = flag.String("f", "etc/growthapi.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	logx.Infof("starting gateway with config: %+v", configsafe.MaskSecrets(c))

	// Harden defaults if not explicitly configured in YAML
	if c.MaxConns == 0 {
		c.MaxConns = 10000
	}
	if c.MaxBytes == 0 {
		c.MaxBytes = 1 << 20 // 1 MB
	}

	server := rest.MustNewServer(c.RestConf)
	defer server.Stop()

	ctx := svc.NewServiceContext(c)

	// Order matters: rate limit first so abusive requests are rejected
	// before auth or response-shape overhead.
	server.Use(ctx.RateLimit)
	server.Use(middleware.ResponseShapeMiddleware())

	handler.RegisterHandlers(server, ctx)

	// Custom file upload route (multipart) — not generated by goctl api.
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{ctx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/files/upload",
					Handler: files.UploadFileHandler(ctx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	fmt.Printf("Starting server at %s:%d...\n", c.Host, c.Port)
	server.Start()
}
