// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article_likes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countArticleLikes = `-- name: CountArticleLikes :one
SELECT COUNT(*) FROM article_likes WHERE article_id = $1
`

func (q *Queries) CountArticleLikes(ctx context.Context, articleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countArticleLikes, articleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticleLike = `-- name: CreateArticleLike :one
INSERT INTO article_likes (article_id, user_id)
VALUES ($1, $2)
ON CONFLICT (article_id, user_id) DO NOTHING
RETURNING id, article_id, user_id, created_at
`

func (q *Queries) CreateArticleLike(ctx context.Context, articleID uuid.UUID, userID uuid.UUID) (ArticleLike, error) {
	row := q.db.QueryRow(ctx, createArticleLike, articleID, userID)
	var i ArticleLike
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArticleLike = `-- name: DeleteArticleLike :exec
DELETE FROM article_likes
WHERE article_id = $1 AND user_id = $2
`

func (q *Queries) DeleteArticleLike(ctx context.Context, articleID uuid.UUID, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteArticleLike, articleID, userID)
	return err
}

const isArticleLikedByUser = `-- name: IsArticleLikedByUser :one
SELECT EXISTS(SELECT 1 FROM article_likes WHERE article_id = $1 AND user_id = $2) AS is_liked
`

func (q *Queries) IsArticleLikedByUser(ctx context.Context, articleID uuid.UUID, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isArticleLikedByUser, articleID, userID)
	var is_liked bool
	err := row.Scan(&is_liked)
	return is_liked, err
}
