// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countArticles = `-- name: CountArticles :one
SELECT COUNT(*) FROM articles
`

func (q *Queries) CountArticles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArticles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArticlesByCategorySlug = `-- name: CountArticlesByCategorySlug :one
SELECT COUNT(*) FROM articles a
JOIN categories c ON a.category_id = c.id
WHERE c.slug = $1
`

func (q *Queries) CountArticlesByCategorySlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRow(ctx, countArticlesByCategorySlug, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (title, excerpt, content, category_id, read_time_minutes, image_url, author)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, excerpt, content, read_time_minutes AS read_time, image_url, author, published_at, created_at, updated_at
`

type CreateArticleParams struct {
	Title           string        `db:"title" json:"title"`
	Excerpt         *string       `db:"excerpt" json:"excerpt"`
	Content         string        `db:"content" json:"content"`
	CategoryID      uuid.NullUUID `db:"category_id" json:"category_id"`
	ReadTimeMinutes int32         `db:"read_time_minutes" json:"read_time_minutes"`
	ImageUrl        *string       `db:"image_url" json:"image_url"`
	Author          string        `db:"author" json:"author"`
}

type CreateArticleRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Title       string             `db:"title" json:"title"`
	Excerpt     *string            `db:"excerpt" json:"excerpt"`
	Content     string             `db:"content" json:"content"`
	ReadTime    int32              `db:"read_time" json:"read_time"`
	ImageUrl    *string            `db:"image_url" json:"image_url"`
	Author      string             `db:"author" json:"author"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (CreateArticleRow, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Title,
		arg.Excerpt,
		arg.Content,
		arg.CategoryID,
		arg.ReadTimeMinutes,
		arg.ImageUrl,
		arg.Author,
	)
	var i CreateArticleRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Excerpt,
		&i.Content,
		&i.ReadTime,
		&i.ImageUrl,
		&i.Author,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const deleteArticleTags = `-- name: DeleteArticleTags :exec
DELETE FROM article_tags WHERE article_id = $1
`

func (q *Queries) DeleteArticleTags(ctx context.Context, articleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteArticleTags, articleID)
	return err
}

const getArticle = `-- name: GetArticle :one
SELECT 
    a.id, a.title, a.excerpt, a.content, a.read_time_minutes AS read_time, a.image_url, a.author, 
    a.published_at, a.created_at, a.updated_at,
    c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
    (SELECT COUNT(*) FROM article_likes al WHERE al.article_id = a.id) AS like_count
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
WHERE a.id = $1
`

type GetArticleRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Title        string             `db:"title" json:"title"`
	Excerpt      *string            `db:"excerpt" json:"excerpt"`
	Content      string             `db:"content" json:"content"`
	ReadTime     int32              `db:"read_time" json:"read_time"`
	ImageUrl     *string            `db:"image_url" json:"image_url"`
	Author       string             `db:"author" json:"author"`
	PublishedAt  pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryID   uuid.NullUUID      `db:"category_id" json:"category_id"`
	CategoryName *string            `db:"category_name" json:"category_name"`
	CategorySlug *string            `db:"category_slug" json:"category_slug"`
	LikeCount    int64              `db:"like_count" json:"like_count"`
}

func (q *Queries) GetArticle(ctx context.Context, id uuid.UUID) (GetArticleRow, error) {
	row := q.db.QueryRow(ctx, getArticle, id)
	var i GetArticleRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Excerpt,
		&i.Content,
		&i.ReadTime,
		&i.ImageUrl,
		&i.Author,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategorySlug,
		&i.LikeCount,
	)
	return i, err
}

const getArticleByTitle = `-- name: GetArticleByTitle :one
SELECT 
    a.id, a.title, a.excerpt, a.content, a.read_time_minutes AS read_time, a.image_url, a.author, 
    a.published_at, a.created_at, a.updated_at,
    c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
    (SELECT COUNT(*) FROM article_likes al WHERE al.article_id = a.id) AS like_count
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
WHERE a.title = $1
`

type GetArticleByTitleRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Title        string             `db:"title" json:"title"`
	Excerpt      *string            `db:"excerpt" json:"excerpt"`
	Content      string             `db:"content" json:"content"`
	ReadTime     int32              `db:"read_time" json:"read_time"`
	ImageUrl     *string            `db:"image_url" json:"image_url"`
	Author       string             `db:"author" json:"author"`
	PublishedAt  pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryID   uuid.NullUUID      `db:"category_id" json:"category_id"`
	CategoryName *string            `db:"category_name" json:"category_name"`
	CategorySlug *string            `db:"category_slug" json:"category_slug"`
	LikeCount    int64              `db:"like_count" json:"like_count"`
}

func (q *Queries) GetArticleByTitle(ctx context.Context, title string) (GetArticleByTitleRow, error) {
	row := q.db.QueryRow(ctx, getArticleByTitle, title)
	var i GetArticleByTitleRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Excerpt,
		&i.Content,
		&i.ReadTime,
		&i.ImageUrl,
		&i.Author,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategorySlug,
		&i.LikeCount,
	)
	return i, err
}

const getArticleWithSaved = `-- name: GetArticleWithSaved :one
SELECT 
    a.id, a.title, a.excerpt, a.content, a.read_time_minutes AS read_time, a.image_url, a.author, 
    a.published_at, a.created_at, a.updated_at,
    c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
    EXISTS(SELECT 1 FROM saved_articles sa WHERE sa.user_id = $2 AND sa.article_id = a.id) AS is_saved,
    (SELECT COUNT(*) FROM article_likes al WHERE al.article_id = a.id) AS like_count,
    EXISTS(SELECT 1 FROM article_likes al2 WHERE al2.user_id = $2 AND al2.article_id = a.id) AS is_liked
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
WHERE a.id = $1
`

type GetArticleWithSavedRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Title        string             `db:"title" json:"title"`
	Excerpt      *string            `db:"excerpt" json:"excerpt"`
	Content      string             `db:"content" json:"content"`
	ReadTime     int32              `db:"read_time" json:"read_time"`
	ImageUrl     *string            `db:"image_url" json:"image_url"`
	Author       string             `db:"author" json:"author"`
	PublishedAt  pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryID   uuid.NullUUID      `db:"category_id" json:"category_id"`
	CategoryName *string            `db:"category_name" json:"category_name"`
	CategorySlug *string            `db:"category_slug" json:"category_slug"`
	IsSaved      bool               `db:"is_saved" json:"is_saved"`
	LikeCount    int64              `db:"like_count" json:"like_count"`
	IsLiked      bool               `db:"is_liked" json:"is_liked"`
}

func (q *Queries) GetArticleWithSaved(ctx context.Context, iD uuid.UUID, userID uuid.UUID) (GetArticleWithSavedRow, error) {
	row := q.db.QueryRow(ctx, getArticleWithSaved, iD, userID)
	var i GetArticleWithSavedRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Excerpt,
		&i.Content,
		&i.ReadTime,
		&i.ImageUrl,
		&i.Author,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategorySlug,
		&i.IsSaved,
		&i.LikeCount,
		&i.IsLiked,
	)
	return i, err
}

const getArticlesByIDs = `-- name: GetArticlesByIDs :many
SELECT
    a.id, a.title, a.excerpt, a.content, a.read_time_minutes AS read_time, a.image_url, a.author,
    a.published_at, a.created_at, a.updated_at,
    c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
    (SELECT COUNT(*) FROM article_likes al WHERE al.article_id = a.id) AS like_count
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
WHERE a.id = ANY($1::uuid[])
`

type GetArticlesByIDsRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Title        string             `db:"title" json:"title"`
	Excerpt      *string            `db:"excerpt" json:"excerpt"`
	Content      string             `db:"content" json:"content"`
	ReadTime     int32              `db:"read_time" json:"read_time"`
	ImageUrl     *string            `db:"image_url" json:"image_url"`
	Author       string             `db:"author" json:"author"`
	PublishedAt  pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryID   uuid.NullUUID      `db:"category_id" json:"category_id"`
	CategoryName *string            `db:"category_name" json:"category_name"`
	CategorySlug *string            `db:"category_slug" json:"category_slug"`
	LikeCount    int64              `db:"like_count" json:"like_count"`
}

// Bulk lookup for article list views (e.g. resolving saved articles).
// Uses ANY with a uuid array to avoid N+1 queries.
func (q *Queries) GetArticlesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetArticlesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getArticlesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArticlesByIDsRow{}
	for rows.Next() {
		var i GetArticlesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.Content,
			&i.ReadTime,
			&i.ImageUrl,
			&i.Author,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.LikeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsByArticleIDs = `-- name: GetTagsByArticleIDs :many
SELECT at.article_id, t.name, t.slug
FROM article_tags at
JOIN tags t ON at.tag_id = t.id
WHERE at.article_id = ANY($1::uuid[])
ORDER BY at.article_id, t.name
`

type GetTagsByArticleIDsRow struct {
	ArticleID uuid.UUID `db:"article_id" json:"article_id"`
	Name      string    `db:"name" json:"name"`
	Slug      string    `db:"slug" json:"slug"`
}

func (q *Queries) GetTagsByArticleIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetTagsByArticleIDsRow, error) {
	rows, err := q.db.Query(ctx, getTagsByArticleIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTagsByArticleIDsRow{}
	for rows.Next() {
		var i GetTagsByArticleIDsRow
		if err := rows.Scan(&i.ArticleID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkArticleTags = `-- name: LinkArticleTags :exec
INSERT INTO article_tags (article_id, tag_id)
SELECT $1, id FROM tags WHERE name = ANY($2::varchar[])
ON CONFLICT DO NOTHING
`

func (q *Queries) LinkArticleTags(ctx context.Context, articleID uuid.UUID, column2 []string) error {
	_, err := q.db.Exec(ctx, linkArticleTags, articleID, column2)
	return err
}

const listArticles = `-- name: ListArticles :many
SELECT
    a.id, a.title, a.excerpt, a.content, a.read_time_minutes AS read_time, a.image_url, a.author,
    a.published_at, a.created_at, a.updated_at,
    c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
    (SELECT COUNT(*) FROM article_likes al WHERE al.article_id = a.id) AS like_count
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
ORDER BY a.published_at DESC
LIMIT $1 OFFSET $2
`

type ListArticlesRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Title        string             `db:"title" json:"title"`
	Excerpt      *string            `db:"excerpt" json:"excerpt"`
	Content      string             `db:"content" json:"content"`
	ReadTime     int32              `db:"read_time" json:"read_time"`
	ImageUrl     *string            `db:"image_url" json:"image_url"`
	Author       string             `db:"author" json:"author"`
	PublishedAt  pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryID   uuid.NullUUID      `db:"category_id" json:"category_id"`
	CategoryName *string            `db:"category_name" json:"category_name"`
	CategorySlug *string            `db:"category_slug" json:"category_slug"`
	LikeCount    int64              `db:"like_count" json:"like_count"`
}

func (q *Queries) ListArticles(ctx context.Context, limit int32, offset int32) ([]ListArticlesRow, error) {
	rows, err := q.db.Query(ctx, listArticles, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesRow{}
	for rows.Next() {
		var i ListArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.Content,
			&i.ReadTime,
			&i.ImageUrl,
			&i.Author,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.LikeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByAuthor = `-- name: ListArticlesByAuthor :many
SELECT 
    a.id, a.title, a.excerpt, a.content, a.read_time_minutes AS read_time, a.image_url, a.author, 
    a.published_at, a.created_at, a.updated_at,
    c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
    (SELECT COUNT(*) FROM article_likes al WHERE al.article_id = a.id) AS like_count
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
WHERE a.author = $1
ORDER BY a.published_at DESC
LIMIT $2 OFFSET $3
`

type ListArticlesByAuthorRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Title        string             `db:"title" json:"title"`
	Excerpt      *string            `db:"excerpt" json:"excerpt"`
	Content      string             `db:"content" json:"content"`
	ReadTime     int32              `db:"read_time" json:"read_time"`
	ImageUrl     *string            `db:"image_url" json:"image_url"`
	Author       string             `db:"author" json:"author"`
	PublishedAt  pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryID   uuid.NullUUID      `db:"category_id" json:"category_id"`
	CategoryName *string            `db:"category_name" json:"category_name"`
	CategorySlug *string            `db:"category_slug" json:"category_slug"`
	LikeCount    int64              `db:"like_count" json:"like_count"`
}

func (q *Queries) ListArticlesByAuthor(ctx context.Context, author string, limit int32, offset int32) ([]ListArticlesByAuthorRow, error) {
	rows, err := q.db.Query(ctx, listArticlesByAuthor, author, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesByAuthorRow{}
	for rows.Next() {
		var i ListArticlesByAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.Content,
			&i.ReadTime,
			&i.ImageUrl,
			&i.Author,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.LikeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByAuthorWithSaved = `-- name: ListArticlesByAuthorWithSaved :many
SELECT 
    a.id, a.title, a.excerpt, a.content, a.read_time_minutes AS read_time, a.image_url, a.author, 
    a.published_at, a.created_at, a.updated_at,
    c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
    EXISTS(SELECT 1 FROM saved_articles sa WHERE sa.user_id = $4 AND sa.article_id = a.id) AS is_saved,
    (SELECT COUNT(*) FROM article_likes al WHERE al.article_id = a.id) AS like_count,
    EXISTS(SELECT 1 FROM article_likes al2 WHERE al2.user_id = $4 AND al2.article_id = a.id) AS is_liked
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
WHERE a.author = $1
ORDER BY a.published_at DESC
LIMIT $2 OFFSET $3
`

type ListArticlesByAuthorWithSavedRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Title        string             `db:"title" json:"title"`
	Excerpt      *string            `db:"excerpt" json:"excerpt"`
	Content      string             `db:"content" json:"content"`
	ReadTime     int32              `db:"read_time" json:"read_time"`
	ImageUrl     *string            `db:"image_url" json:"image_url"`
	Author       string             `db:"author" json:"author"`
	PublishedAt  pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryID   uuid.NullUUID      `db:"category_id" json:"category_id"`
	CategoryName *string            `db:"category_name" json:"category_name"`
	CategorySlug *string            `db:"category_slug" json:"category_slug"`
	IsSaved      bool               `db:"is_saved" json:"is_saved"`
	LikeCount    int64              `db:"like_count" json:"like_count"`
	IsLiked      bool               `db:"is_liked" json:"is_liked"`
}

func (q *Queries) ListArticlesByAuthorWithSaved(ctx context.Context, author string, limit int32, offset int32, userID uuid.UUID) ([]ListArticlesByAuthorWithSavedRow, error) {
	rows, err := q.db.Query(ctx, listArticlesByAuthorWithSaved,
		author,
		limit,
		offset,
		userID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesByAuthorWithSavedRow{}
	for rows.Next() {
		var i ListArticlesByAuthorWithSavedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.Content,
			&i.ReadTime,
			&i.ImageUrl,
			&i.Author,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.IsSaved,
			&i.LikeCount,
			&i.IsLiked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByCategorySlug = `-- name: ListArticlesByCategorySlug :many
SELECT 
    a.id, a.title, a.excerpt, a.content, a.read_time_minutes AS read_time, a.image_url, a.author, 
    a.published_at, a.created_at, a.updated_at,
    c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
    (SELECT COUNT(*) FROM article_likes al WHERE al.article_id = a.id) AS like_count
FROM articles a
JOIN categories c ON a.category_id = c.id
WHERE c.slug = $1
ORDER BY a.published_at DESC
LIMIT $2 OFFSET $3
`

type ListArticlesByCategorySlugRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Title        string             `db:"title" json:"title"`
	Excerpt      *string            `db:"excerpt" json:"excerpt"`
	Content      string             `db:"content" json:"content"`
	ReadTime     int32              `db:"read_time" json:"read_time"`
	ImageUrl     *string            `db:"image_url" json:"image_url"`
	Author       string             `db:"author" json:"author"`
	PublishedAt  pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryID   uuid.UUID          `db:"category_id" json:"category_id"`
	CategoryName string             `db:"category_name" json:"category_name"`
	CategorySlug string             `db:"category_slug" json:"category_slug"`
	LikeCount    int64              `db:"like_count" json:"like_count"`
}

func (q *Queries) ListArticlesByCategorySlug(ctx context.Context, slug string, limit int32, offset int32) ([]ListArticlesByCategorySlugRow, error) {
	rows, err := q.db.Query(ctx, listArticlesByCategorySlug, slug, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesByCategorySlugRow{}
	for rows.Next() {
		var i ListArticlesByCategorySlugRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.Content,
			&i.ReadTime,
			&i.ImageUrl,
			&i.Author,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.LikeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByCategorySlugWithSaved = `-- name: ListArticlesByCategorySlugWithSaved :many
SELECT 
    a.id, a.title, a.excerpt, a.content, a.read_time_minutes AS read_time, a.image_url, a.author, 
    a.published_at, a.created_at, a.updated_at,
    c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
    EXISTS(SELECT 1 FROM saved_articles sa WHERE sa.user_id = $4 AND sa.article_id = a.id) AS is_saved,
    (SELECT COUNT(*) FROM article_likes al WHERE al.article_id = a.id) AS like_count,
    EXISTS(SELECT 1 FROM article_likes al2 WHERE al2.user_id = $4 AND al2.article_id = a.id) AS is_liked
FROM articles a
JOIN categories c ON a.category_id = c.id
LEFT JOIN saved_articles sa ON sa.article_id = a.id AND sa.user_id = $4
WHERE c.slug = $1
ORDER BY a.published_at DESC
LIMIT $2 OFFSET $3
`

type ListArticlesByCategorySlugWithSavedRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Title        string             `db:"title" json:"title"`
	Excerpt      *string            `db:"excerpt" json:"excerpt"`
	Content      string             `db:"content" json:"content"`
	ReadTime     int32              `db:"read_time" json:"read_time"`
	ImageUrl     *string            `db:"image_url" json:"image_url"`
	Author       string             `db:"author" json:"author"`
	PublishedAt  pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryID   uuid.UUID          `db:"category_id" json:"category_id"`
	CategoryName string             `db:"category_name" json:"category_name"`
	CategorySlug string             `db:"category_slug" json:"category_slug"`
	IsSaved      bool               `db:"is_saved" json:"is_saved"`
	LikeCount    int64              `db:"like_count" json:"like_count"`
	IsLiked      bool               `db:"is_liked" json:"is_liked"`
}

func (q *Queries) ListArticlesByCategorySlugWithSaved(ctx context.Context, slug string, limit int32, offset int32, userID uuid.UUID) ([]ListArticlesByCategorySlugWithSavedRow, error) {
	rows, err := q.db.Query(ctx, listArticlesByCategorySlugWithSaved,
		slug,
		limit,
		offset,
		userID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesByCategorySlugWithSavedRow{}
	for rows.Next() {
		var i ListArticlesByCategorySlugWithSavedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.Content,
			&i.ReadTime,
			&i.ImageUrl,
			&i.Author,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.IsSaved,
			&i.LikeCount,
			&i.IsLiked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesWithSaved = `-- name: ListArticlesWithSaved :many
SELECT
    a.id, a.title, a.excerpt, a.content, a.read_time_minutes AS read_time, a.image_url, a.author,
    a.published_at, a.created_at, a.updated_at,
    c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
    EXISTS(SELECT 1 FROM saved_articles sa WHERE sa.user_id = $3 AND sa.article_id = a.id) AS is_saved,
    (SELECT COUNT(*) FROM article_likes al WHERE al.article_id = a.id) AS like_count,
    EXISTS(SELECT 1 FROM article_likes al2 WHERE al2.user_id = $3 AND al2.article_id = a.id) AS is_liked
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
ORDER BY a.published_at DESC
LIMIT $1 OFFSET $2
`

type ListArticlesWithSavedRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Title        string             `db:"title" json:"title"`
	Excerpt      *string            `db:"excerpt" json:"excerpt"`
	Content      string             `db:"content" json:"content"`
	ReadTime     int32              `db:"read_time" json:"read_time"`
	ImageUrl     *string            `db:"image_url" json:"image_url"`
	Author       string             `db:"author" json:"author"`
	PublishedAt  pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryID   uuid.NullUUID      `db:"category_id" json:"category_id"`
	CategoryName *string            `db:"category_name" json:"category_name"`
	CategorySlug *string            `db:"category_slug" json:"category_slug"`
	IsSaved      bool               `db:"is_saved" json:"is_saved"`
	LikeCount    int64              `db:"like_count" json:"like_count"`
	IsLiked      bool               `db:"is_liked" json:"is_liked"`
}

func (q *Queries) ListArticlesWithSaved(ctx context.Context, limit int32, offset int32, userID uuid.UUID) ([]ListArticlesWithSavedRow, error) {
	rows, err := q.db.Query(ctx, listArticlesWithSaved, limit, offset, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesWithSavedRow{}
	for rows.Next() {
		var i ListArticlesWithSavedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.Content,
			&i.ReadTime,
			&i.ImageUrl,
			&i.Author,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.IsSaved,
			&i.LikeCount,
			&i.IsLiked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchArticles = `-- name: SearchArticles :many
SELECT 
    a.id, a.title, a.excerpt, a.content, a.read_time_minutes AS read_time, a.image_url, a.author, 
    a.published_at, a.created_at, a.updated_at,
    c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
    (SELECT COUNT(*) FROM article_likes al WHERE al.article_id = a.id) AS like_count
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
WHERE a.search_vector @@ plainto_tsquery('english', $1)
ORDER BY a.published_at DESC
LIMIT $2 OFFSET $3
`

type SearchArticlesRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Title        string             `db:"title" json:"title"`
	Excerpt      *string            `db:"excerpt" json:"excerpt"`
	Content      string             `db:"content" json:"content"`
	ReadTime     int32              `db:"read_time" json:"read_time"`
	ImageUrl     *string            `db:"image_url" json:"image_url"`
	Author       string             `db:"author" json:"author"`
	PublishedAt  pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryID   uuid.NullUUID      `db:"category_id" json:"category_id"`
	CategoryName *string            `db:"category_name" json:"category_name"`
	CategorySlug *string            `db:"category_slug" json:"category_slug"`
	LikeCount    int64              `db:"like_count" json:"like_count"`
}

func (q *Queries) SearchArticles(ctx context.Context, plaintoTsquery string, limit int32, offset int32) ([]SearchArticlesRow, error) {
	rows, err := q.db.Query(ctx, searchArticles, plaintoTsquery, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchArticlesRow{}
	for rows.Next() {
		var i SearchArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.Content,
			&i.ReadTime,
			&i.ImageUrl,
			&i.Author,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.LikeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET title = $2, excerpt = $3, content = $4, category_id = $5,
    read_time_minutes = $6, image_url = $7, author = $8
WHERE id = $1
RETURNING id, title, excerpt, content, read_time_minutes AS read_time, image_url, author, published_at, created_at, updated_at
`

type UpdateArticleParams struct {
	ID              uuid.UUID     `db:"id" json:"id"`
	Title           string        `db:"title" json:"title"`
	Excerpt         *string       `db:"excerpt" json:"excerpt"`
	Content         string        `db:"content" json:"content"`
	CategoryID      uuid.NullUUID `db:"category_id" json:"category_id"`
	ReadTimeMinutes int32         `db:"read_time_minutes" json:"read_time_minutes"`
	ImageUrl        *string       `db:"image_url" json:"image_url"`
	Author          string        `db:"author" json:"author"`
}

type UpdateArticleRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Title       string             `db:"title" json:"title"`
	Excerpt     *string            `db:"excerpt" json:"excerpt"`
	Content     string             `db:"content" json:"content"`
	ReadTime    int32              `db:"read_time" json:"read_time"`
	ImageUrl    *string            `db:"image_url" json:"image_url"`
	Author      string             `db:"author" json:"author"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (UpdateArticleRow, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.ID,
		arg.Title,
		arg.Excerpt,
		arg.Content,
		arg.CategoryID,
		arg.ReadTimeMinutes,
		arg.ImageUrl,
		arg.Author,
	)
	var i UpdateArticleRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Excerpt,
		&i.Content,
		&i.ReadTime,
		&i.ImageUrl,
		&i.Author,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTags = `-- name: UpsertTags :many
INSERT INTO tags (name, slug)
SELECT unnest($1::text[]), unnest($2::text[])
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, slug
`

type UpsertTagsRow struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
	Slug string    `db:"slug" json:"slug"`
}

func (q *Queries) UpsertTags(ctx context.Context, column1 []string, column2 []string) ([]UpsertTagsRow, error) {
	rows, err := q.db.Query(ctx, upsertTags, column1, column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UpsertTagsRow{}
	for rows.Next() {
		var i UpsertTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
