// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveGoalsForUser = `-- name: CountActiveGoalsForUser :one
SELECT COUNT(*) FROM goals
WHERE user_id = $1 AND status != 'completed'
`

func (q *Queries) CountActiveGoalsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveGoalsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveHabitsForUser = `-- name: CountActiveHabitsForUser :one
SELECT COUNT(*) FROM habits
WHERE user_id = $1
`

func (q *Queries) CountActiveHabitsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveHabitsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingPlanAdjustmentsForUser = `-- name: CountPendingPlanAdjustmentsForUser :one
SELECT COUNT(*) FROM plan_adjustments
WHERE user_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingPlanAdjustmentsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingPlanAdjustmentsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDefaultFreeSubscription = `-- name: CreateDefaultFreeSubscription :one
INSERT INTO subscriptions (user_id, plan_id, status)
SELECT $1, p.id, 'free'
FROM plans p
WHERE p.code = 'free'
ON CONFLICT (user_id) DO UPDATE SET updated_at = now()
RETURNING id, user_id, plan_id, status, billing_interval, current_period_start, current_period_end, trial_end, cancel_at_period_end, stripe_customer_id, stripe_subscription_id, created_at, updated_at
`

func (q *Queries) CreateDefaultFreeSubscription(ctx context.Context, userID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, createDefaultFreeSubscription, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingInterval,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEnd,
		&i.CancelAtPeriodEnd,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUpgradeEvent = `-- name: CreateUpgradeEvent :one
WITH ins AS (
    INSERT INTO upgrade_events (
        user_id, event_type, surface, trigger_source, plan_id,
        billing_interval, feedback_reason, feedback_note, metadata
    )
    VALUES ($1, $2, $3, $4, (SELECT p2.id FROM plans p2 WHERE p2.code = $5), $6, $7, $8, $9)
    RETURNING id, user_id, plan_id, event_type, surface, trigger_source, billing_interval, feedback_reason, feedback_note, metadata, created_at
)
SELECT ins.id, ins.user_id, ins.plan_id, ins.event_type, ins.surface, ins.trigger_source, ins.billing_interval, ins.feedback_reason, ins.feedback_note, ins.metadata, ins.created_at, p.code AS plan_code
FROM ins
LEFT JOIN plans p ON p.id = ins.plan_id
`

type CreateUpgradeEventParams struct {
	UserID          uuid.UUID `db:"user_id" json:"user_id"`
	EventType       string    `db:"event_type" json:"event_type"`
	Surface         string    `db:"surface" json:"surface"`
	TriggerSource   *string   `db:"trigger_source" json:"trigger_source"`
	Code            string    `db:"code" json:"code"`
	BillingInterval *string   `db:"billing_interval" json:"billing_interval"`
	FeedbackReason  *string   `db:"feedback_reason" json:"feedback_reason"`
	FeedbackNote    *string   `db:"feedback_note" json:"feedback_note"`
	Metadata        []byte    `db:"metadata" json:"metadata"`
}

type CreateUpgradeEventRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	UserID          uuid.UUID          `db:"user_id" json:"user_id"`
	PlanID          uuid.NullUUID      `db:"plan_id" json:"plan_id"`
	EventType       string             `db:"event_type" json:"event_type"`
	Surface         string             `db:"surface" json:"surface"`
	TriggerSource   *string            `db:"trigger_source" json:"trigger_source"`
	BillingInterval *string            `db:"billing_interval" json:"billing_interval"`
	FeedbackReason  *string            `db:"feedback_reason" json:"feedback_reason"`
	FeedbackNote    *string            `db:"feedback_note" json:"feedback_note"`
	Metadata        []byte             `db:"metadata" json:"metadata"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PlanCode        *string            `db:"plan_code" json:"plan_code"`
}

func (q *Queries) CreateUpgradeEvent(ctx context.Context, arg CreateUpgradeEventParams) (CreateUpgradeEventRow, error) {
	row := q.db.QueryRow(ctx, createUpgradeEvent,
		arg.UserID,
		arg.EventType,
		arg.Surface,
		arg.TriggerSource,
		arg.Code,
		arg.BillingInterval,
		arg.FeedbackReason,
		arg.FeedbackNote,
		arg.Metadata,
	)
	var i CreateUpgradeEventRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.EventType,
		&i.Surface,
		&i.TriggerSource,
		&i.BillingInterval,
		&i.FeedbackReason,
		&i.FeedbackNote,
		&i.Metadata,
		&i.CreatedAt,
		&i.PlanCode,
	)
	return i, err
}

const getPlanByCode = `-- name: GetPlanByCode :one
SELECT id, code, name, description, price_monthly_cents, price_annual_cents, currency, active_goal_limit, active_habit_limit, weekly_review_history_limit, plan_adjustment_limit, personalized_ai_enabled, stripe_monthly_price_id, stripe_annual_price_id, is_active, created_at, updated_at FROM plans
WHERE code = $1 AND is_active = TRUE
`

func (q *Queries) GetPlanByCode(ctx context.Context, code string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByCode, code)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.PriceMonthlyCents,
		&i.PriceAnnualCents,
		&i.Currency,
		&i.ActiveGoalLimit,
		&i.ActiveHabitLimit,
		&i.WeeklyReviewHistoryLimit,
		&i.PlanAdjustmentLimit,
		&i.PersonalizedAiEnabled,
		&i.StripeMonthlyPriceID,
		&i.StripeAnnualPriceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSubscription = `-- name: GetUserSubscription :one
SELECT
    s.id, s.user_id, s.plan_id, s.status, s.billing_interval, s.current_period_start, s.current_period_end, s.trial_end, s.cancel_at_period_end, s.stripe_customer_id, s.stripe_subscription_id, s.created_at, s.updated_at,
    p.code AS plan_code,
    p.name AS plan_name,
    p.active_goal_limit,
    p.active_habit_limit,
    p.weekly_review_history_limit,
    p.plan_adjustment_limit,
    p.personalized_ai_enabled
FROM subscriptions s
JOIN plans p ON p.id = s.plan_id
WHERE s.user_id = $1
`

type GetUserSubscriptionRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	PlanID                   uuid.UUID          `db:"plan_id" json:"plan_id"`
	Status                   string             `db:"status" json:"status"`
	BillingInterval          *string            `db:"billing_interval" json:"billing_interval"`
	CurrentPeriodStart       pgtype.Timestamptz `db:"current_period_start" json:"current_period_start"`
	CurrentPeriodEnd         pgtype.Timestamptz `db:"current_period_end" json:"current_period_end"`
	TrialEnd                 pgtype.Timestamptz `db:"trial_end" json:"trial_end"`
	CancelAtPeriodEnd        bool               `db:"cancel_at_period_end" json:"cancel_at_period_end"`
	StripeCustomerID         *string            `db:"stripe_customer_id" json:"stripe_customer_id"`
	StripeSubscriptionID     *string            `db:"stripe_subscription_id" json:"stripe_subscription_id"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PlanCode                 string             `db:"plan_code" json:"plan_code"`
	PlanName                 string             `db:"plan_name" json:"plan_name"`
	ActiveGoalLimit          int32              `db:"active_goal_limit" json:"active_goal_limit"`
	ActiveHabitLimit         int32              `db:"active_habit_limit" json:"active_habit_limit"`
	WeeklyReviewHistoryLimit int32              `db:"weekly_review_history_limit" json:"weekly_review_history_limit"`
	PlanAdjustmentLimit      int32              `db:"plan_adjustment_limit" json:"plan_adjustment_limit"`
	PersonalizedAiEnabled    bool               `db:"personalized_ai_enabled" json:"personalized_ai_enabled"`
}

func (q *Queries) GetUserSubscription(ctx context.Context, userID uuid.UUID) (GetUserSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getUserSubscription, userID)
	var i GetUserSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingInterval,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEnd,
		&i.CancelAtPeriodEnd,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanCode,
		&i.PlanName,
		&i.ActiveGoalLimit,
		&i.ActiveHabitLimit,
		&i.WeeklyReviewHistoryLimit,
		&i.PlanAdjustmentLimit,
		&i.PersonalizedAiEnabled,
	)
	return i, err
}

const getUserSubscriptionByStripeCustomerID = `-- name: GetUserSubscriptionByStripeCustomerID :one
SELECT
    s.id, s.user_id, s.plan_id, s.status, s.billing_interval, s.current_period_start, s.current_period_end, s.trial_end, s.cancel_at_period_end, s.stripe_customer_id, s.stripe_subscription_id, s.created_at, s.updated_at,
    p.code AS plan_code,
    p.name AS plan_name,
    p.active_goal_limit,
    p.active_habit_limit,
    p.weekly_review_history_limit,
    p.plan_adjustment_limit,
    p.personalized_ai_enabled
FROM subscriptions s
JOIN plans p ON p.id = s.plan_id
WHERE s.stripe_customer_id = $1
`

type GetUserSubscriptionByStripeCustomerIDRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	PlanID                   uuid.UUID          `db:"plan_id" json:"plan_id"`
	Status                   string             `db:"status" json:"status"`
	BillingInterval          *string            `db:"billing_interval" json:"billing_interval"`
	CurrentPeriodStart       pgtype.Timestamptz `db:"current_period_start" json:"current_period_start"`
	CurrentPeriodEnd         pgtype.Timestamptz `db:"current_period_end" json:"current_period_end"`
	TrialEnd                 pgtype.Timestamptz `db:"trial_end" json:"trial_end"`
	CancelAtPeriodEnd        bool               `db:"cancel_at_period_end" json:"cancel_at_period_end"`
	StripeCustomerID         *string            `db:"stripe_customer_id" json:"stripe_customer_id"`
	StripeSubscriptionID     *string            `db:"stripe_subscription_id" json:"stripe_subscription_id"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PlanCode                 string             `db:"plan_code" json:"plan_code"`
	PlanName                 string             `db:"plan_name" json:"plan_name"`
	ActiveGoalLimit          int32              `db:"active_goal_limit" json:"active_goal_limit"`
	ActiveHabitLimit         int32              `db:"active_habit_limit" json:"active_habit_limit"`
	WeeklyReviewHistoryLimit int32              `db:"weekly_review_history_limit" json:"weekly_review_history_limit"`
	PlanAdjustmentLimit      int32              `db:"plan_adjustment_limit" json:"plan_adjustment_limit"`
	PersonalizedAiEnabled    bool               `db:"personalized_ai_enabled" json:"personalized_ai_enabled"`
}

func (q *Queries) GetUserSubscriptionByStripeCustomerID(ctx context.Context, stripeCustomerID *string) (GetUserSubscriptionByStripeCustomerIDRow, error) {
	row := q.db.QueryRow(ctx, getUserSubscriptionByStripeCustomerID, stripeCustomerID)
	var i GetUserSubscriptionByStripeCustomerIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingInterval,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEnd,
		&i.CancelAtPeriodEnd,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanCode,
		&i.PlanName,
		&i.ActiveGoalLimit,
		&i.ActiveHabitLimit,
		&i.WeeklyReviewHistoryLimit,
		&i.PlanAdjustmentLimit,
		&i.PersonalizedAiEnabled,
	)
	return i, err
}

const isStripeEventProcessed = `-- name: IsStripeEventProcessed :one
SELECT EXISTS(
    SELECT 1 FROM processed_events
    WHERE consumer = 'stripe_webhooks' AND event_id = $1
)
`

func (q *Queries) IsStripeEventProcessed(ctx context.Context, eventID string) (bool, error) {
	row := q.db.QueryRow(ctx, isStripeEventProcessed, eventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActivePlans = `-- name: ListActivePlans :many
SELECT id, code, name, description, price_monthly_cents, price_annual_cents, currency, active_goal_limit, active_habit_limit, weekly_review_history_limit, plan_adjustment_limit, personalized_ai_enabled, stripe_monthly_price_id, stripe_annual_price_id, is_active, created_at, updated_at FROM plans
WHERE is_active = TRUE
ORDER BY price_monthly_cents ASC
`

func (q *Queries) ListActivePlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.PriceMonthlyCents,
			&i.PriceAnnualCents,
			&i.Currency,
			&i.ActiveGoalLimit,
			&i.ActiveHabitLimit,
			&i.WeeklyReviewHistoryLimit,
			&i.PlanAdjustmentLimit,
			&i.PersonalizedAiEnabled,
			&i.StripeMonthlyPriceID,
			&i.StripeAnnualPriceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredActiveSubscriptions = `-- name: ListExpiredActiveSubscriptions :many
SELECT
    s.id, s.user_id, s.plan_id, s.status, s.billing_interval, s.current_period_start, s.current_period_end, s.trial_end, s.cancel_at_period_end, s.stripe_customer_id, s.stripe_subscription_id, s.created_at, s.updated_at,
    p.code AS plan_code,
    p.name AS plan_name,
    p.active_goal_limit,
    p.active_habit_limit,
    p.weekly_review_history_limit,
    p.plan_adjustment_limit,
    p.personalized_ai_enabled
FROM subscriptions s
JOIN plans p ON p.id = s.plan_id
WHERE s.status IN ('active', 'trialing')
  AND s.cancel_at_period_end = true
  AND s.current_period_end < NOW()
LIMIT $1
`

type ListExpiredActiveSubscriptionsRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	PlanID                   uuid.UUID          `db:"plan_id" json:"plan_id"`
	Status                   string             `db:"status" json:"status"`
	BillingInterval          *string            `db:"billing_interval" json:"billing_interval"`
	CurrentPeriodStart       pgtype.Timestamptz `db:"current_period_start" json:"current_period_start"`
	CurrentPeriodEnd         pgtype.Timestamptz `db:"current_period_end" json:"current_period_end"`
	TrialEnd                 pgtype.Timestamptz `db:"trial_end" json:"trial_end"`
	CancelAtPeriodEnd        bool               `db:"cancel_at_period_end" json:"cancel_at_period_end"`
	StripeCustomerID         *string            `db:"stripe_customer_id" json:"stripe_customer_id"`
	StripeSubscriptionID     *string            `db:"stripe_subscription_id" json:"stripe_subscription_id"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PlanCode                 string             `db:"plan_code" json:"plan_code"`
	PlanName                 string             `db:"plan_name" json:"plan_name"`
	ActiveGoalLimit          int32              `db:"active_goal_limit" json:"active_goal_limit"`
	ActiveHabitLimit         int32              `db:"active_habit_limit" json:"active_habit_limit"`
	WeeklyReviewHistoryLimit int32              `db:"weekly_review_history_limit" json:"weekly_review_history_limit"`
	PlanAdjustmentLimit      int32              `db:"plan_adjustment_limit" json:"plan_adjustment_limit"`
	PersonalizedAiEnabled    bool               `db:"personalized_ai_enabled" json:"personalized_ai_enabled"`
}

func (q *Queries) ListExpiredActiveSubscriptions(ctx context.Context, limit int32) ([]ListExpiredActiveSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredActiveSubscriptions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredActiveSubscriptionsRow{}
	for rows.Next() {
		var i ListExpiredActiveSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.BillingInterval,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.TrialEnd,
			&i.CancelAtPeriodEnd,
			&i.StripeCustomerID,
			&i.StripeSubscriptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlanCode,
			&i.PlanName,
			&i.ActiveGoalLimit,
			&i.ActiveHabitLimit,
			&i.WeeklyReviewHistoryLimit,
			&i.PlanAdjustmentLimit,
			&i.PersonalizedAiEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStripeEventProcessed = `-- name: MarkStripeEventProcessed :exec
INSERT INTO processed_events (consumer, event_id)
VALUES ('stripe_webhooks', $1)
ON CONFLICT DO NOTHING
`

func (q *Queries) MarkStripeEventProcessed(ctx context.Context, eventID string) error {
	_, err := q.db.Exec(ctx, markStripeEventProcessed, eventID)
	return err
}

const upsertUserSubscription = `-- name: UpsertUserSubscription :one
INSERT INTO subscriptions (
    user_id,
    plan_id,
    status,
    billing_interval,
    current_period_start,
    current_period_end,
    trial_end,
    cancel_at_period_end,
    stripe_customer_id,
    stripe_subscription_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (user_id)
DO UPDATE SET
    plan_id = EXCLUDED.plan_id,
    status = EXCLUDED.status,
    billing_interval = EXCLUDED.billing_interval,
    current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end,
    trial_end = EXCLUDED.trial_end,
    cancel_at_period_end = EXCLUDED.cancel_at_period_end,
    stripe_customer_id = EXCLUDED.stripe_customer_id,
    stripe_subscription_id = EXCLUDED.stripe_subscription_id
RETURNING id, user_id, plan_id, status, billing_interval, current_period_start, current_period_end, trial_end, cancel_at_period_end, stripe_customer_id, stripe_subscription_id, created_at, updated_at
`

type UpsertUserSubscriptionParams struct {
	UserID               uuid.UUID          `db:"user_id" json:"user_id"`
	PlanID               uuid.UUID          `db:"plan_id" json:"plan_id"`
	Status               string             `db:"status" json:"status"`
	BillingInterval      *string            `db:"billing_interval" json:"billing_interval"`
	CurrentPeriodStart   pgtype.Timestamptz `db:"current_period_start" json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `db:"current_period_end" json:"current_period_end"`
	TrialEnd             pgtype.Timestamptz `db:"trial_end" json:"trial_end"`
	CancelAtPeriodEnd    bool               `db:"cancel_at_period_end" json:"cancel_at_period_end"`
	StripeCustomerID     *string            `db:"stripe_customer_id" json:"stripe_customer_id"`
	StripeSubscriptionID *string            `db:"stripe_subscription_id" json:"stripe_subscription_id"`
}

func (q *Queries) UpsertUserSubscription(ctx context.Context, arg UpsertUserSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertUserSubscription,
		arg.UserID,
		arg.PlanID,
		arg.Status,
		arg.BillingInterval,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.TrialEnd,
		arg.CancelAtPeriodEnd,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingInterval,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEnd,
		&i.CancelAtPeriodEnd,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
