// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: check_ins.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countCheckInsByHabit = `-- name: CountCheckInsByHabit :one
SELECT COUNT(*) FROM check_ins
WHERE habit_id = $1
`

func (q *Queries) CountCheckInsByHabit(ctx context.Context, habitID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCheckInsByHabit, habitID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCheckInsByUser = `-- name: CountCheckInsByUser :one
SELECT COUNT(*) FROM check_ins
WHERE user_id = $1
`

func (q *Queries) CountCheckInsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCheckInsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCheckIn = `-- name: CreateCheckIn :one
INSERT INTO check_ins (user_id, habit_id, status, mood, energy, blocker, note, local_date)
SELECT $1, $2, $3, $4, $5, $6, $7, (NOW() AT TIME ZONE COALESCE(
  (SELECT timezone FROM user_settings WHERE user_id = $1),
  'UTC'
))::date
RETURNING id, user_id, habit_id, status, mood, energy, blocker, note, created_at, local_date
`

type CreateCheckInParams struct {
	UserID  uuid.UUID      `db:"user_id" json:"user_id"`
	HabitID uuid.UUID      `db:"habit_id" json:"habit_id"`
	Status  string         `db:"status" json:"status"`
	Mood    sql.NullString `db:"mood" json:"mood"`
	Energy  sql.NullString `db:"energy" json:"energy"`
	Blocker sql.NullString `db:"blocker" json:"blocker"`
	Note    sql.NullString `db:"note" json:"note"`
}

func (q *Queries) CreateCheckIn(ctx context.Context, arg CreateCheckInParams) (CheckIn, error) {
	row := q.db.QueryRowContext(ctx, createCheckIn,
		arg.UserID,
		arg.HabitID,
		arg.Status,
		arg.Mood,
		arg.Energy,
		arg.Blocker,
		arg.Note,
	)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HabitID,
		&i.Status,
		&i.Mood,
		&i.Energy,
		&i.Blocker,
		&i.Note,
		&i.CreatedAt,
		&i.LocalDate,
	)
	return i, err
}

const getCheckInHistory = `-- name: GetCheckInHistory :many
SELECT id, user_id, habit_id, status, mood, energy, blocker, note, created_at, local_date FROM check_ins
WHERE user_id = $1
  AND created_at >= $2
  AND created_at < $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type GetCheckInHistoryParams struct {
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	CreatedAt_2 time.Time `db:"created_at_2" json:"created_at_2"`
	Limit       int32     `db:"limit" json:"limit"`
	Offset      int32     `db:"offset" json:"offset"`
}

func (q *Queries) GetCheckInHistory(ctx context.Context, arg GetCheckInHistoryParams) ([]CheckIn, error) {
	rows, err := q.db.QueryContext(ctx, getCheckInHistory,
		arg.UserID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CheckIn
	for rows.Next() {
		var i CheckIn
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HabitID,
			&i.Status,
			&i.Mood,
			&i.Energy,
			&i.Blocker,
			&i.Note,
			&i.CreatedAt,
			&i.LocalDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCheckInsByHabit = `-- name: GetCheckInsByHabit :many
SELECT id, user_id, habit_id, status, mood, energy, blocker, note, created_at, local_date FROM check_ins
WHERE habit_id = $1 AND user_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetCheckInsByHabitParams struct {
	HabitID uuid.UUID `db:"habit_id" json:"habit_id"`
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
}

func (q *Queries) GetCheckInsByHabit(ctx context.Context, arg GetCheckInsByHabitParams) ([]CheckIn, error) {
	rows, err := q.db.QueryContext(ctx, getCheckInsByHabit,
		arg.HabitID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CheckIn
	for rows.Next() {
		var i CheckIn
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HabitID,
			&i.Status,
			&i.Mood,
			&i.Energy,
			&i.Blocker,
			&i.Note,
			&i.CreatedAt,
			&i.LocalDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCheckInsByUser = `-- name: GetCheckInsByUser :many
SELECT id, user_id, habit_id, status, mood, energy, blocker, note, created_at, local_date FROM check_ins
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetCheckInsByUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) GetCheckInsByUser(ctx context.Context, arg GetCheckInsByUserParams) ([]CheckIn, error) {
	rows, err := q.db.QueryContext(ctx, getCheckInsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CheckIn
	for rows.Next() {
		var i CheckIn
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HabitID,
			&i.Status,
			&i.Mood,
			&i.Energy,
			&i.Blocker,
			&i.Note,
			&i.CreatedAt,
			&i.LocalDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCheckInsForWeek = `-- name: GetCheckInsForWeek :many
SELECT id, user_id, habit_id, status, mood, energy, blocker, note, created_at, local_date FROM check_ins
WHERE user_id = $1
  AND created_at >= $2
  AND created_at < $3
ORDER BY created_at DESC
`

type GetCheckInsForWeekParams struct {
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	WeekStart time.Time `db:"week_start" json:"week_start"`
	WeekEnd   time.Time `db:"week_end" json:"week_end"`
}

func (q *Queries) GetCheckInsForWeek(ctx context.Context, arg GetCheckInsForWeekParams) ([]CheckIn, error) {
	rows, err := q.db.QueryContext(ctx, getCheckInsForWeek, arg.UserID, arg.WeekStart, arg.WeekEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CheckIn
	for rows.Next() {
		var i CheckIn
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HabitID,
			&i.Status,
			&i.Mood,
			&i.Energy,
			&i.Blocker,
			&i.Note,
			&i.CreatedAt,
			&i.LocalDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayCheckIns = `-- name: GetTodayCheckIns :many
SELECT ci.id, ci.user_id, ci.habit_id, ci.status, ci.mood, ci.energy, ci.blocker, ci.note, ci.created_at, ci.local_date FROM check_ins ci
LEFT JOIN user_settings us ON ci.user_id = us.user_id
WHERE ci.user_id = $1
  AND ci.local_date = (NOW() AT TIME ZONE COALESCE(us.timezone, 'UTC'))::date
`

func (q *Queries) GetTodayCheckIns(ctx context.Context, userID uuid.UUID) ([]CheckIn, error) {
	rows, err := q.db.QueryContext(ctx, getTodayCheckIns, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CheckIn
	for rows.Next() {
		var i CheckIn
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HabitID,
			&i.Status,
			&i.Mood,
			&i.Energy,
			&i.Blocker,
			&i.Note,
			&i.CreatedAt,
			&i.LocalDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasCheckedInToday = `-- name: HasCheckedInToday :one
SELECT EXISTS(
    SELECT 1 FROM check_ins ci
    LEFT JOIN user_settings us ON ci.user_id = us.user_id
    WHERE ci.user_id = $1 AND ci.habit_id = $2
      AND ci.local_date = (NOW() AT TIME ZONE COALESCE(us.timezone, 'UTC'))::date
) AS exists
`

type HasCheckedInTodayParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	HabitID uuid.UUID `db:"habit_id" json:"habit_id"`
}

func (q *Queries) HasCheckedInToday(ctx context.Context, arg HasCheckedInTodayParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasCheckedInToday, arg.UserID, arg.HabitID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
