// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countGoalsByUser = `-- name: CountGoalsByUser :one
SELECT COUNT(*) FROM goals WHERE user_id = $1
`

func (q *Queries) CountGoalsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGoalsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGoal = `-- name: CreateGoal :one
WITH ins AS (
    INSERT INTO goals (title, description, category_id, due_date, user_id)
    VALUES ($1, $2, (SELECT c2.id FROM categories c2 WHERE c2.slug = $3), $4, $5)
    RETURNING id, user_id, category_id, title, description, status, progress, due_date, created_at, updated_at
)
SELECT ins.id, ins.user_id, ins.category_id, ins.title, ins.description, ins.status, ins.progress, ins.due_date, ins.created_at, ins.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       (ins.status = 'completed') AS completed
FROM ins
LEFT JOIN categories c ON c.id = ins.category_id
`

type CreateGoalParams struct {
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Slug        string             `db:"slug" json:"slug"`
	DueDate     pgtype.Timestamptz `db:"due_date" json:"due_date"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
}

type CreateGoalRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	Progress    int32              `db:"progress" json:"progress"`
	DueDate     pgtype.Timestamptz `db:"due_date" json:"due_date"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (CreateGoalRow, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.Title,
		arg.Description,
		arg.Slug,
		arg.DueDate,
		arg.UserID,
	)
	var i CreateGoalRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Progress,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Completed,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals WHERE id = $1
`

func (q *Queries) DeleteGoal(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGoal, id)
	return err
}

const getGoal = `-- name: GetGoal :one
SELECT g.id, g.user_id, g.category_id, g.title, g.description, g.status, g.progress, g.due_date, g.created_at, g.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       (g.status = 'completed') AS completed
FROM goals g
LEFT JOIN categories c ON c.id = g.category_id
WHERE g.id = $1
`

type GetGoalRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	Progress    int32              `db:"progress" json:"progress"`
	DueDate     pgtype.Timestamptz `db:"due_date" json:"due_date"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

func (q *Queries) GetGoal(ctx context.Context, id uuid.UUID) (GetGoalRow, error) {
	row := q.db.QueryRow(ctx, getGoal, id)
	var i GetGoalRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Progress,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Completed,
	)
	return i, err
}

const getGoalsByIDs = `-- name: GetGoalsByIDs :many
SELECT g.id, g.user_id, g.category_id, g.title, g.description, g.status, g.progress, g.due_date, g.created_at, g.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       (g.status = 'completed') AS completed
FROM goals g
LEFT JOIN categories c ON c.id = g.category_id
WHERE g.id = ANY($1::uuid[])
`

type GetGoalsByIDsRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	Progress    int32              `db:"progress" json:"progress"`
	DueDate     pgtype.Timestamptz `db:"due_date" json:"due_date"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

func (q *Queries) GetGoalsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetGoalsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getGoalsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGoalsByIDsRow{}
	for rows.Next() {
		var i GetGoalsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Progress,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoals = `-- name: ListGoals :many

SELECT g.id, g.user_id, g.category_id, g.title, g.description, g.status, g.progress, g.due_date, g.created_at, g.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       (g.status = 'completed') AS completed
FROM goals g
LEFT JOIN categories c ON c.id = g.category_id
WHERE g.user_id = $1
ORDER BY g.created_at DESC
LIMIT $2 OFFSET $3
`

type ListGoalsRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	Progress    int32              `db:"progress" json:"progress"`
	DueDate     pgtype.Timestamptz `db:"due_date" json:"due_date"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

// Goal rows are returned with a resolved category slug and a derived
// `completed` flag so callers never deal with category_id directly.
func (q *Queries) ListGoals(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]ListGoalsRow, error) {
	rows, err := q.db.Query(ctx, listGoals, userID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoalsRow{}
	for rows.Next() {
		var i ListGoalsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Progress,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsKeyset = `-- name: ListGoalsKeyset :many
SELECT g.id, g.user_id, g.category_id, g.title, g.description, g.status, g.progress, g.due_date, g.created_at, g.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       (g.status = 'completed') AS completed
FROM goals g
LEFT JOIN categories c ON c.id = g.category_id
WHERE g.user_id = $1
  AND ($2::timestamptz IS NULL OR g.created_at < $2)
ORDER BY g.created_at DESC
LIMIT $3
`

type ListGoalsKeysetRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	Progress    int32              `db:"progress" json:"progress"`
	DueDate     pgtype.Timestamptz `db:"due_date" json:"due_date"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

// Keyset pagination: pass last_created_at from the previous page (or NULL).
func (q *Queries) ListGoalsKeyset(ctx context.Context, userID uuid.UUID, column2 pgtype.Timestamptz, limit int32) ([]ListGoalsKeysetRow, error) {
	rows, err := q.db.Query(ctx, listGoalsKeyset, userID, column2, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoalsKeysetRow{}
	for rows.Next() {
		var i ListGoalsKeysetRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Progress,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleGoal = `-- name: ToggleGoal :one
WITH upd AS (
    UPDATE goals
    SET status = CASE WHEN status = 'completed' THEN 'active' ELSE 'completed' END,
        progress = CASE WHEN status = 'completed' THEN 0 ELSE 100 END
    WHERE goals.id = $1
    RETURNING id, user_id, category_id, title, description, status, progress, due_date, created_at, updated_at
)
SELECT upd.id, upd.user_id, upd.category_id, upd.title, upd.description, upd.status, upd.progress, upd.due_date, upd.created_at, upd.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       (upd.status = 'completed') AS completed
FROM upd
LEFT JOIN categories c ON c.id = upd.category_id
`

type ToggleGoalRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	Progress    int32              `db:"progress" json:"progress"`
	DueDate     pgtype.Timestamptz `db:"due_date" json:"due_date"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

func (q *Queries) ToggleGoal(ctx context.Context, id uuid.UUID) (ToggleGoalRow, error) {
	row := q.db.QueryRow(ctx, toggleGoal, id)
	var i ToggleGoalRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Progress,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Completed,
	)
	return i, err
}

const updateGoal = `-- name: UpdateGoal :one
WITH upd AS (
    UPDATE goals
    SET title = $2, description = $3,
        category_id = (SELECT c2.id FROM categories c2 WHERE c2.slug = $4),
        due_date = $5
    WHERE goals.id = $1
    RETURNING id, user_id, category_id, title, description, status, progress, due_date, created_at, updated_at
)
SELECT upd.id, upd.user_id, upd.category_id, upd.title, upd.description, upd.status, upd.progress, upd.due_date, upd.created_at, upd.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       (upd.status = 'completed') AS completed
FROM upd
LEFT JOIN categories c ON c.id = upd.category_id
`

type UpdateGoalParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Slug        string             `db:"slug" json:"slug"`
	DueDate     pgtype.Timestamptz `db:"due_date" json:"due_date"`
}

type UpdateGoalRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	Progress    int32              `db:"progress" json:"progress"`
	DueDate     pgtype.Timestamptz `db:"due_date" json:"due_date"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (UpdateGoalRow, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Slug,
		arg.DueDate,
	)
	var i UpdateGoalRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Progress,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Completed,
	)
	return i, err
}

const updateGoalProgress = `-- name: UpdateGoalProgress :one
WITH upd AS (
    UPDATE goals
    SET progress = $2,
        status = CASE WHEN $2 >= 100 THEN 'completed' ELSE status END
    WHERE goals.id = $1
    RETURNING id, user_id, category_id, title, description, status, progress, due_date, created_at, updated_at
)
SELECT upd.id, upd.user_id, upd.category_id, upd.title, upd.description, upd.status, upd.progress, upd.due_date, upd.created_at, upd.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       (upd.status = 'completed') AS completed
FROM upd
LEFT JOIN categories c ON c.id = upd.category_id
`

type UpdateGoalProgressRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	Progress    int32              `db:"progress" json:"progress"`
	DueDate     pgtype.Timestamptz `db:"due_date" json:"due_date"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

func (q *Queries) UpdateGoalProgress(ctx context.Context, iD uuid.UUID, progress int32) (UpdateGoalProgressRow, error) {
	row := q.db.QueryRow(ctx, updateGoalProgress, iD, progress)
	var i UpdateGoalProgressRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Progress,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Completed,
	)
	return i, err
}
