// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: habits.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countHabitsByUser = `-- name: CountHabitsByUser :one
SELECT COUNT(*) FROM habits WHERE user_id = $1
`

func (q *Queries) CountHabitsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countHabitsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHabit = `-- name: CreateHabit :one
WITH ins AS (
    INSERT INTO habits (name, description, category_id, user_id)
    VALUES ($1, $2, (SELECT c2.id FROM categories c2 WHERE c2.slug = $3), $4)
    RETURNING id, user_id, category_id, name, description, streak, created_at, updated_at
)
SELECT ins.id, ins.user_id, ins.category_id, ins.name, ins.description, ins.streak, ins.created_at, ins.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       false AS completed
FROM ins
LEFT JOIN categories c ON c.id = ins.category_id
`

type CreateHabitRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Streak      int32              `db:"streak" json:"streak"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

func (q *Queries) CreateHabit(ctx context.Context, name string, description *string, slug string, userID uuid.UUID) (CreateHabitRow, error) {
	row := q.db.QueryRow(ctx, createHabit,
		name,
		description,
		slug,
		userID,
	)
	var i CreateHabitRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Streak,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Completed,
	)
	return i, err
}

const deleteHabit = `-- name: DeleteHabit :exec
DELETE FROM habits WHERE id = $1
`

func (q *Queries) DeleteHabit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHabit, id)
	return err
}

const getHabit = `-- name: GetHabit :one
SELECT h.id, h.user_id, h.category_id, h.name, h.description, h.streak, h.created_at, h.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       EXISTS (
           SELECT 1 FROM check_ins ci
           WHERE ci.habit_id = h.id AND ci.status = 'completed'
             AND ci.local_date = (now() AT TIME ZONE COALESCE(
                 (SELECT s.timezone FROM user_settings s WHERE s.user_id = h.user_id), 'UTC'))::date
       ) AS completed
FROM habits h
LEFT JOIN categories c ON c.id = h.category_id
WHERE h.id = $1
`

type GetHabitRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Streak      int32              `db:"streak" json:"streak"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

func (q *Queries) GetHabit(ctx context.Context, id uuid.UUID) (GetHabitRow, error) {
	row := q.db.QueryRow(ctx, getHabit, id)
	var i GetHabitRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Streak,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Completed,
	)
	return i, err
}

const getHabitsByIDs = `-- name: GetHabitsByIDs :many
SELECT h.id, h.user_id, h.category_id, h.name, h.description, h.streak, h.created_at, h.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       EXISTS (
           SELECT 1 FROM check_ins ci
           WHERE ci.habit_id = h.id AND ci.status = 'completed'
             AND ci.local_date = (now() AT TIME ZONE COALESCE(
                 (SELECT s.timezone FROM user_settings s WHERE s.user_id = h.user_id), 'UTC'))::date
       ) AS completed
FROM habits h
LEFT JOIN categories c ON c.id = h.category_id
WHERE h.id = ANY($1::uuid[])
`

type GetHabitsByIDsRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Streak      int32              `db:"streak" json:"streak"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

func (q *Queries) GetHabitsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetHabitsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getHabitsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHabitsByIDsRow{}
	for rows.Next() {
		var i GetHabitsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Streak,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabits = `-- name: ListHabits :many

SELECT h.id, h.user_id, h.category_id, h.name, h.description, h.streak, h.created_at, h.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       EXISTS (
           SELECT 1 FROM check_ins ci
           WHERE ci.habit_id = h.id AND ci.status = 'completed'
             AND ci.local_date = (now() AT TIME ZONE COALESCE(
                 (SELECT s.timezone FROM user_settings s WHERE s.user_id = h.user_id), 'UTC'))::date
       ) AS completed
FROM habits h
LEFT JOIN categories c ON c.id = h.category_id
WHERE h.user_id = $1
ORDER BY h.created_at DESC
LIMIT $2 OFFSET $3
`

type ListHabitsRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Streak      int32              `db:"streak" json:"streak"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

// Habit rows carry a resolved category slug and a derived `completed` flag:
// completed = a 'completed' check-in exists for the habit today (in the
// owner's timezone). There is no stored boolean to keep in sync.
func (q *Queries) ListHabits(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]ListHabitsRow, error) {
	rows, err := q.db.Query(ctx, listHabits, userID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHabitsRow{}
	for rows.Next() {
		var i ListHabitsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Streak,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabitsKeyset = `-- name: ListHabitsKeyset :many
SELECT h.id, h.user_id, h.category_id, h.name, h.description, h.streak, h.created_at, h.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       EXISTS (
           SELECT 1 FROM check_ins ci
           WHERE ci.habit_id = h.id AND ci.status = 'completed'
             AND ci.local_date = (now() AT TIME ZONE COALESCE(
                 (SELECT s.timezone FROM user_settings s WHERE s.user_id = h.user_id), 'UTC'))::date
       ) AS completed
FROM habits h
LEFT JOIN categories c ON c.id = h.category_id
WHERE h.user_id = $1
  AND ($2::timestamptz IS NULL OR h.created_at < $2)
ORDER BY h.created_at DESC
LIMIT $3
`

type ListHabitsKeysetRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Streak      int32              `db:"streak" json:"streak"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

// Keyset pagination: pass last_created_at from the previous page (or NULL).
func (q *Queries) ListHabitsKeyset(ctx context.Context, userID uuid.UUID, column2 pgtype.Timestamptz, limit int32) ([]ListHabitsKeysetRow, error) {
	rows, err := q.db.Query(ctx, listHabitsKeyset, userID, column2, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHabitsKeysetRow{}
	for rows.Next() {
		var i ListHabitsKeysetRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Streak,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHabitCompleted = `-- name: MarkHabitCompleted :one
WITH today AS (
    SELECT (now() AT TIME ZONE COALESCE(
        (SELECT s.timezone FROM user_settings s
         JOIN habits h ON h.user_id = s.user_id
         WHERE h.id = $1), 'UTC'))::date AS d
), added AS (
    INSERT INTO check_ins (user_id, habit_id, local_date, status)
    SELECT h.user_id, h.id, (SELECT d FROM today), 'completed'
    FROM habits h
    WHERE h.id = $1
    ON CONFLICT (habit_id, local_date) DO UPDATE SET status = 'completed'
        WHERE check_ins.status <> 'completed'
    RETURNING id
), upd AS (
    UPDATE habits
    SET streak = streak + (CASE WHEN EXISTS (SELECT 1 FROM added) THEN 1 ELSE 0 END)
    WHERE id = $1
    RETURNING id, user_id, category_id, name, description, streak, created_at, updated_at
)
SELECT upd.id, upd.user_id, upd.category_id, upd.name, upd.description, upd.streak, upd.created_at, upd.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       true AS completed
FROM upd
LEFT JOIN categories c ON c.id = upd.category_id
`

type MarkHabitCompletedRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Streak      int32              `db:"streak" json:"streak"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

// Idempotent: completing an already-completed habit changes nothing.
func (q *Queries) MarkHabitCompleted(ctx context.Context, id uuid.UUID) (MarkHabitCompletedRow, error) {
	row := q.db.QueryRow(ctx, markHabitCompleted, id)
	var i MarkHabitCompletedRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Streak,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Completed,
	)
	return i, err
}

const resetTodayHabits = `-- name: ResetTodayHabits :execrows
DELETE FROM check_ins ci
WHERE ci.user_id = $1
  AND ci.status = 'completed'
  AND ci.local_date = (now() AT TIME ZONE COALESCE(
      (SELECT s.timezone FROM user_settings s WHERE s.user_id = $1), 'UTC'))::date
`

// "Uncompletes" all of today's habits by deleting today's completed check-ins.
func (q *Queries) ResetTodayHabits(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, resetTodayHabits, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const toggleHabit = `-- name: ToggleHabit :one
WITH today AS (
    SELECT (now() AT TIME ZONE COALESCE(
        (SELECT s.timezone FROM user_settings s
         JOIN habits h ON h.user_id = s.user_id
         WHERE h.id = $1), 'UTC'))::date AS d
), existing AS (
    SELECT ci.id FROM check_ins ci
    WHERE ci.habit_id = $1
      AND ci.local_date = (SELECT d FROM today)
      AND ci.status = 'completed'
), removed AS (
    DELETE FROM check_ins WHERE id IN (SELECT id FROM existing) RETURNING id
), added AS (
    INSERT INTO check_ins (user_id, habit_id, local_date, status)
    SELECT h.user_id, h.id, (SELECT d FROM today), 'completed'
    FROM habits h
    WHERE h.id = $1 AND NOT EXISTS (SELECT 1 FROM existing)
    ON CONFLICT (habit_id, local_date) DO UPDATE SET status = 'completed'
    RETURNING id
), upd AS (
    UPDATE habits
    SET streak = CASE WHEN EXISTS (SELECT 1 FROM added)
                      THEN streak + 1
                      ELSE GREATEST(streak - 1, 0) END
    WHERE id = $1
    RETURNING id, user_id, category_id, name, description, streak, created_at, updated_at
)
SELECT upd.id, upd.user_id, upd.category_id, upd.name, upd.description, upd.streak, upd.created_at, upd.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       EXISTS (SELECT 1 FROM added) AS completed
FROM upd
LEFT JOIN categories c ON c.id = upd.category_id
`

type ToggleHabitRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Streak      int32              `db:"streak" json:"streak"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

// Toggles today's completion by inserting or deleting a completed check-in
// for today (owner's timezone) and adjusting the streak accordingly.
func (q *Queries) ToggleHabit(ctx context.Context, id uuid.UUID) (ToggleHabitRow, error) {
	row := q.db.QueryRow(ctx, toggleHabit, id)
	var i ToggleHabitRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Streak,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Completed,
	)
	return i, err
}

const updateHabit = `-- name: UpdateHabit :one
WITH upd AS (
    UPDATE habits
    SET name = $2, description = $3,
        category_id = (SELECT c2.id FROM categories c2 WHERE c2.slug = $4)
    WHERE habits.id = $1
    RETURNING id, user_id, category_id, name, description, streak, created_at, updated_at
)
SELECT upd.id, upd.user_id, upd.category_id, upd.name, upd.description, upd.streak, upd.created_at, upd.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       EXISTS (
           SELECT 1 FROM check_ins ci
           WHERE ci.habit_id = upd.id AND ci.status = 'completed'
             AND ci.local_date = (now() AT TIME ZONE COALESCE(
                 (SELECT s.timezone FROM user_settings s WHERE s.user_id = upd.user_id), 'UTC'))::date
       ) AS completed
FROM upd
LEFT JOIN categories c ON c.id = upd.category_id
`

type UpdateHabitRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Streak      int32              `db:"streak" json:"streak"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

func (q *Queries) UpdateHabit(ctx context.Context, iD uuid.UUID, name string, description *string, slug string) (UpdateHabitRow, error) {
	row := q.db.QueryRow(ctx, updateHabit,
		iD,
		name,
		description,
		slug,
	)
	var i UpdateHabitRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Streak,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Completed,
	)
	return i, err
}

const updateHabitStreak = `-- name: UpdateHabitStreak :one
WITH upd AS (
    UPDATE habits SET streak = $2 WHERE habits.id = $1 RETURNING id, user_id, category_id, name, description, streak, created_at, updated_at
)
SELECT upd.id, upd.user_id, upd.category_id, upd.name, upd.description, upd.streak, upd.created_at, upd.updated_at,
       COALESCE(c.slug, '')::varchar AS category,
       EXISTS (
           SELECT 1 FROM check_ins ci
           WHERE ci.habit_id = upd.id AND ci.status = 'completed'
             AND ci.local_date = (now() AT TIME ZONE COALESCE(
                 (SELECT s.timezone FROM user_settings s WHERE s.user_id = upd.user_id), 'UTC'))::date
       ) AS completed
FROM upd
LEFT JOIN categories c ON c.id = upd.category_id
`

type UpdateHabitStreakRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID  uuid.NullUUID      `db:"category_id" json:"category_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Streak      int32              `db:"streak" json:"streak"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Category    string             `db:"category" json:"category"`
	Completed   bool               `db:"completed" json:"completed"`
}

func (q *Queries) UpdateHabitStreak(ctx context.Context, iD uuid.UUID, streak int32) (UpdateHabitStreakRow, error) {
	row := q.db.QueryRow(ctx, updateHabitStreak, iD, streak)
	var i UpdateHabitStreakRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Streak,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Completed,
	)
	return i, err
}
