// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: habits.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countHabitsByUser = `-- name: CountHabitsByUser :one
SELECT COUNT(*) FROM habits WHERE user_id = $1
`

func (q *Queries) CountHabitsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countHabitsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (name, description, category, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, streak, completed, category, user_id, created_at, updated_at
`

func (q *Queries) CreateHabit(ctx context.Context, name string, description *string, category string, userID uuid.UUID) (Habit, error) {
	row := q.db.QueryRow(ctx, createHabit,
		name,
		description,
		category,
		userID,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Streak,
		&i.Completed,
		&i.Category,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHabit = `-- name: DeleteHabit :exec
DELETE FROM habits WHERE id = $1
`

func (q *Queries) DeleteHabit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHabit, id)
	return err
}

const getHabit = `-- name: GetHabit :one
SELECT id, name, description, streak, completed, category, user_id, created_at, updated_at
FROM habits
WHERE id = $1
`

func (q *Queries) GetHabit(ctx context.Context, id uuid.UUID) (Habit, error) {
	row := q.db.QueryRow(ctx, getHabit, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Streak,
		&i.Completed,
		&i.Category,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHabitsByIDs = `-- name: GetHabitsByIDs :many
SELECT id, name, description, streak, completed, category, user_id, created_at, updated_at
FROM habits
WHERE id = ANY($1::uuid[])
`

// Bulk lookup for habit list views (e.g. resolving saved habits).
func (q *Queries) GetHabitsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Habit, error) {
	rows, err := q.db.Query(ctx, getHabitsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Habit{}
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Streak,
			&i.Completed,
			&i.Category,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabits = `-- name: ListHabits :many
SELECT id, name, description, streak, completed, category, user_id, created_at, updated_at
FROM habits
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListHabits(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]Habit, error) {
	rows, err := q.db.Query(ctx, listHabits, userID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Habit{}
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Streak,
			&i.Completed,
			&i.Category,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHabitCompleted = `-- name: MarkHabitCompleted :one
UPDATE habits
SET completed = true,
    streak = CASE WHEN NOT completed THEN streak + 1 ELSE streak END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, description, streak, completed, category, user_id, created_at, updated_at
`

func (q *Queries) MarkHabitCompleted(ctx context.Context, id uuid.UUID) (Habit, error) {
	row := q.db.QueryRow(ctx, markHabitCompleted, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Streak,
		&i.Completed,
		&i.Category,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetTodayHabits = `-- name: ResetTodayHabits :execrows
UPDATE habits
SET completed = false, updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND completed = true
`

func (q *Queries) ResetTodayHabits(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, resetTodayHabits, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const toggleHabit = `-- name: ToggleHabit :one
UPDATE habits
SET completed = NOT completed,
    streak = CASE WHEN NOT completed THEN streak + 1 ELSE streak END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, description, streak, completed, category, user_id, created_at, updated_at
`

func (q *Queries) ToggleHabit(ctx context.Context, id uuid.UUID) (Habit, error) {
	row := q.db.QueryRow(ctx, toggleHabit, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Streak,
		&i.Completed,
		&i.Category,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHabit = `-- name: UpdateHabit :one
UPDATE habits
SET name = $2, description = $3, category = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, description, streak, completed, category, user_id, created_at, updated_at
`

func (q *Queries) UpdateHabit(ctx context.Context, iD uuid.UUID, name string, description *string, category string) (Habit, error) {
	row := q.db.QueryRow(ctx, updateHabit,
		iD,
		name,
		description,
		category,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Streak,
		&i.Completed,
		&i.Category,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHabitStreak = `-- name: UpdateHabitStreak :one
UPDATE habits
SET streak = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, description, streak, completed, category, user_id, created_at, updated_at
`

func (q *Queries) UpdateHabitStreak(ctx context.Context, iD uuid.UUID, streak int32) (Habit, error) {
	row := q.db.QueryRow(ctx, updateHabitStreak, iD, streak)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Streak,
		&i.Completed,
		&i.Category,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
