// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countNotifications = `-- name: CountNotifications :one
SELECT COUNT(*) FROM notifications
`

func (q *Queries) CountNotifications(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotifications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotificationsByUser = `-- name: CountNotificationsByUser :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1
`

func (q *Queries) CountNotificationsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotificationsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1 AND read = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (title, message, item_type, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, title, message, item_type, read, user_id, created_at
`

type CreateNotificationParams struct {
	Title    string    `db:"title" json:"title"`
	Message  string    `db:"message" json:"message"`
	ItemType string    `db:"item_type" json:"item_type"`
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.Title,
		arg.Message,
		arg.ItemType,
		arg.UserID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.ItemType,
		&i.Read,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllNotificationsByUser = `-- name: DeleteAllNotificationsByUser :exec
DELETE FROM notifications WHERE user_id = $1
`

func (q *Queries) DeleteAllNotificationsByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllNotificationsByUser, userID)
	return err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications WHERE id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotification, id)
	return err
}

const getNotification = `-- name: GetNotification :one
SELECT id, title, message, item_type, read, user_id, created_at FROM notifications WHERE id = $1
`

func (q *Queries) GetNotification(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.ItemType,
		&i.Read,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1 AND read = false
`

func (q *Queries) GetUnreadCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, title, message, item_type, read, user_id, created_at FROM notifications
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListNotificationsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.ItemType,
			&i.Read,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByType = `-- name: ListNotificationsByType :many
SELECT id, title, message, item_type, read, user_id, created_at FROM notifications WHERE user_id = $1 AND item_type = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListNotificationsByTypeParams struct {
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	ItemType string    `db:"item_type" json:"item_type"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListNotificationsByType(ctx context.Context, arg ListNotificationsByTypeParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByType,
		arg.UserID,
		arg.ItemType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.ItemType,
			&i.Read,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, title, message, item_type, read, user_id, created_at FROM notifications WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.ItemType,
			&i.Read,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, title, message, item_type, read, user_id, created_at
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsForUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.ItemType,
			&i.Read,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotifications = `-- name: ListUnreadNotifications :many
SELECT id, title, message, item_type, read, user_id, created_at FROM notifications WHERE user_id = $1 AND read = false
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUnreadNotificationsParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListUnreadNotifications(ctx context.Context, arg ListUnreadNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.ItemType,
			&i.Read,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read = true
WHERE user_id = $1 AND read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET read = true
WHERE id = $1
RETURNING id, title, message, item_type, read, user_id, created_at
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, markNotificationRead, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.ItemType,
		&i.Read,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
