// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountActivities(ctx context.Context) (int64, error)
	CountActivitiesByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountActivitiesByUserAndType(ctx context.Context, arg CountActivitiesByUserAndTypeParams) (int64, error)
	CountArticleShares(ctx context.Context) (int64, error)
	CountArticleSharesByArticle(ctx context.Context, articleID uuid.UUID) (int64, error)
	CountArticleSharesByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountArticles(ctx context.Context) (int64, error)
	CountArticlesByCategory(ctx context.Context, category string) (int64, error)
	CountNotifications(ctx context.Context) (int64, error)
	CountNotificationsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountSavedItems(ctx context.Context) (int64, error)
	CountSavedItemsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountSavedItemsByUserAndType(ctx context.Context, arg CountSavedItemsByUserAndTypeParams) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUserSettings(ctx context.Context) (int64, error)
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (CreateArticleRow, error)
	CreateArticleShare(ctx context.Context, arg CreateArticleShareParams) (ArticleShare, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateSavedItem(ctx context.Context, arg CreateSavedItemParams) (SavedItem, error)
	CreateUserSettings(ctx context.Context, arg CreateUserSettingsParams) (UserSetting, error)
	DeleteActivitiesByUser(ctx context.Context, userID uuid.UUID) error
	DeleteActivity(ctx context.Context, id uuid.UUID) error
	DeleteAllNotificationsByUser(ctx context.Context, userID uuid.UUID) error
	DeleteArticle(ctx context.Context, id uuid.UUID) error
	DeleteArticleShare(ctx context.Context, id uuid.UUID) error
	DeleteArticleShareByUserAndArticle(ctx context.Context, arg DeleteArticleShareByUserAndArticleParams) error
	DeleteNotification(ctx context.Context, id uuid.UUID) error
	DeleteSavedItem(ctx context.Context, id uuid.UUID) error
	DeleteSavedItemByUserAndItem(ctx context.Context, arg DeleteSavedItemByUserAndItemParams) error
	DeleteUserSettings(ctx context.Context, userID uuid.UUID) error
	GetAchievements(ctx context.Context, userID uuid.UUID) ([]GetAchievementsRow, error)
	GetActivity(ctx context.Context, id uuid.UUID) (Activity, error)
	GetActivityCalendar(ctx context.Context, arg GetActivityCalendarParams) ([]GetActivityCalendarRow, error)
	GetActivityFeed(ctx context.Context, arg GetActivityFeedParams) ([]Activity, error)
	GetActivityStats(ctx context.Context, userID uuid.UUID) (GetActivityStatsRow, error)
	GetArticle(ctx context.Context, id uuid.UUID) (GetArticleRow, error)
	GetArticleByTitle(ctx context.Context, title string) (GetArticleByTitleRow, error)
	GetArticleShare(ctx context.Context, id uuid.UUID) (ArticleShare, error)
	GetArticleShareByUserAndArticle(ctx context.Context, arg GetArticleShareByUserAndArticleParams) (ArticleShare, error)
	GetNotification(ctx context.Context, id uuid.UUID) (Notification, error)
	GetSavedItem(ctx context.Context, id uuid.UUID) (SavedItem, error)
	GetSavedItemByUserAndItem(ctx context.Context, arg GetSavedItemByUserAndItemParams) (SavedItem, error)
	GetStreaks(ctx context.Context, userID uuid.UUID) (GetStreaksRow, error)
	GetUnreadCount(ctx context.Context, userID uuid.UUID) (int64, error)
	GetUserSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error)
	GetUserSettingsByID(ctx context.Context, id uuid.UUID) (UserSetting, error)
	IsItemSaved(ctx context.Context, arg IsItemSavedParams) (bool, error)
	ListActivities(ctx context.Context, arg ListActivitiesParams) ([]Activity, error)
	ListActivitiesByType(ctx context.Context, arg ListActivitiesByTypeParams) ([]Activity, error)
	ListActivitiesByUser(ctx context.Context, arg ListActivitiesByUserParams) ([]Activity, error)
	ListArticleShares(ctx context.Context, arg ListArticleSharesParams) ([]ArticleShare, error)
	ListArticleSharesByArticle(ctx context.Context, arg ListArticleSharesByArticleParams) ([]ArticleShare, error)
	ListArticleSharesByUser(ctx context.Context, arg ListArticleSharesByUserParams) ([]ArticleShare, error)
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]ListArticlesRow, error)
	ListArticlesByAuthor(ctx context.Context, arg ListArticlesByAuthorParams) ([]ListArticlesByAuthorRow, error)
	ListArticlesByCategory(ctx context.Context, arg ListArticlesByCategoryParams) ([]ListArticlesByCategoryRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListNotificationsByType(ctx context.Context, arg ListNotificationsByTypeParams) ([]Notification, error)
	ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error)
	ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error)
	ListSavedItems(ctx context.Context, arg ListSavedItemsParams) ([]SavedItem, error)
	ListSavedItemsByType(ctx context.Context, arg ListSavedItemsByTypeParams) ([]SavedItem, error)
	ListSavedItemsByUser(ctx context.Context, arg ListSavedItemsByUserParams) ([]SavedItem, error)
	ListUnreadNotifications(ctx context.Context, arg ListUnreadNotificationsParams) ([]Notification, error)
	LogActivity(ctx context.Context, arg LogActivityParams) (Activity, error)
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error
	MarkNotificationRead(ctx context.Context, id uuid.UUID) (Notification, error)
	SearchArticles(ctx context.Context, arg SearchArticlesParams) ([]SearchArticlesRow, error)
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (UpdateArticleRow, error)
	UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UserSetting, error)
}

var _ Querier = (*Queries)(nil)
