// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site_settings.sql

package db

import (
	"context"
)

const deleteSiteSetting = `-- name: DeleteSiteSetting :exec
DELETE FROM site_settings WHERE key = $1
`

func (q *Queries) DeleteSiteSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSiteSetting, key)
	return err
}

const getSiteSetting = `-- name: GetSiteSetting :one
SELECT key, value, created_at, updated_at
FROM site_settings
WHERE key = $1
`

func (q *Queries) GetSiteSetting(ctx context.Context, key string) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, getSiteSetting, key)
	var i SiteSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllSiteSettings = `-- name: ListAllSiteSettings :many
SELECT key, value, created_at, updated_at
FROM site_settings
ORDER BY key
`

func (q *Queries) ListAllSiteSettings(ctx context.Context) ([]SiteSetting, error) {
	rows, err := q.db.Query(ctx, listAllSiteSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteSetting{}
	for rows.Next() {
		var i SiteSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteSettings = `-- name: ListSiteSettings :many
SELECT key, value, created_at, updated_at
FROM site_settings
WHERE key = ANY($1::text[])
ORDER BY key
`

func (q *Queries) ListSiteSettings(ctx context.Context, dollar_1 []string) ([]SiteSetting, error) {
	rows, err := q.db.Query(ctx, listSiteSettings, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteSetting{}
	for rows.Next() {
		var i SiteSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSiteSetting = `-- name: UpsertSiteSetting :one
INSERT INTO site_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
    SET value = EXCLUDED.value,
        updated_at = now()
RETURNING key, value, created_at, updated_at
`

func (q *Queries) UpsertSiteSetting(ctx context.Context, key string, value []byte) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, upsertSiteSetting, key, value)
	var i SiteSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
