// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mfa.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAdminMfaBackupCode = `-- name: ConsumeAdminMfaBackupCode :one
UPDATE admin_mfa_backup_codes
SET used_at = now()
WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
RETURNING id
`

func (q *Queries) ConsumeAdminMfaBackupCode(ctx context.Context, userID uuid.UUID, codeHash string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeAdminMfaBackupCode, userID, codeHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createAdminMfaTicket = `-- name: CreateAdminMfaTicket :one
INSERT INTO admin_mfa_tickets (user_id, token_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, purpose, attempts, expires_at, created_at
`

// Tickets bridge the password step and the TOTP step of login. Only a SHA-256
// hash of the client-facing token is stored.
func (q *Queries) CreateAdminMfaTicket(ctx context.Context, userID uuid.UUID, tokenHash string, purpose string, expiresAt pgtype.Timestamptz) (AdminMfaTicket, error) {
	row := q.db.QueryRow(ctx, createAdminMfaTicket,
		userID,
		tokenHash,
		purpose,
		expiresAt,
	)
	var i AdminMfaTicket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAdminMfaBackupCodesForUser = `-- name: DeleteAdminMfaBackupCodesForUser :exec
DELETE FROM admin_mfa_backup_codes WHERE user_id = $1
`

func (q *Queries) DeleteAdminMfaBackupCodesForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdminMfaBackupCodesForUser, userID)
	return err
}

const deleteAdminMfaTicket = `-- name: DeleteAdminMfaTicket :exec
DELETE FROM admin_mfa_tickets WHERE id = $1
`

func (q *Queries) DeleteAdminMfaTicket(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdminMfaTicket, id)
	return err
}

const deleteAdminMfaTicketsForUser = `-- name: DeleteAdminMfaTicketsForUser :exec
DELETE FROM admin_mfa_tickets WHERE user_id = $1
`

func (q *Queries) DeleteAdminMfaTicketsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdminMfaTicketsForUser, userID)
	return err
}

const deleteExpiredAdminMfaTickets = `-- name: DeleteExpiredAdminMfaTickets :exec
DELETE FROM admin_mfa_tickets WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredAdminMfaTickets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAdminMfaTickets)
	return err
}

const disableInternalUserTotp = `-- name: DisableInternalUserTotp :exec
UPDATE internal_users
SET totp_secret_encrypted = NULL,
    totp_enabled_at = NULL
WHERE id = $1
`

func (q *Queries) DisableInternalUserTotp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableInternalUserTotp, id)
	return err
}

const enableInternalUserTotp = `-- name: EnableInternalUserTotp :exec
UPDATE internal_users
SET totp_enabled_at = now()
WHERE id = $1
`

func (q *Queries) EnableInternalUserTotp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, enableInternalUserTotp, id)
	return err
}

const getAdminMfaTicketByHash = `-- name: GetAdminMfaTicketByHash :one
SELECT id, user_id, token_hash, purpose, attempts, expires_at, created_at
FROM admin_mfa_tickets
WHERE token_hash = $1
`

func (q *Queries) GetAdminMfaTicketByHash(ctx context.Context, tokenHash string) (AdminMfaTicket, error) {
	row := q.db.QueryRow(ctx, getAdminMfaTicketByHash, tokenHash)
	var i AdminMfaTicket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementAdminMfaTicketAttempts = `-- name: IncrementAdminMfaTicketAttempts :exec
UPDATE admin_mfa_tickets
SET attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) IncrementAdminMfaTicketAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementAdminMfaTicketAttempts, id)
	return err
}

const insertAdminMfaBackupCode = `-- name: InsertAdminMfaBackupCode :exec
INSERT INTO admin_mfa_backup_codes (user_id, code_hash)
VALUES ($1, $2)
`

// Backup codes are stored as SHA-256 hashes. Consume returns a row only when
// an unused code matches, which is also the validity signal.
func (q *Queries) InsertAdminMfaBackupCode(ctx context.Context, userID uuid.UUID, codeHash string) error {
	_, err := q.db.Exec(ctx, insertAdminMfaBackupCode, userID, codeHash)
	return err
}

const setInternalUserTotpSecret = `-- name: SetInternalUserTotpSecret :exec

UPDATE internal_users
SET totp_secret_encrypted = $2
WHERE id = $1
`

// Admin MFA: pending TOTP secrets on internal_users, pre-auth tickets, and
// one-time backup codes. Table rationale lives in migration 068.
// Pending/active TOTP secret lifecycle. The secret written by
// SetInternalUserTotpSecret is inert until EnableInternalUserTotp confirms it
// with a valid code — login only requires MFA once totp_enabled_at is set.
func (q *Queries) SetInternalUserTotpSecret(ctx context.Context, iD uuid.UUID, totpSecretEncrypted *string) error {
	_, err := q.db.Exec(ctx, setInternalUserTotpSecret, iD, totpSecretEncrypted)
	return err
}
