// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: client.proto

package goaltemplates

import (
	"context"

	"github.com/suleymanmyradov/growth-server/services/microservices/client/rpc/pb/client"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ListGoalTemplatesRequest  = client.ListGoalTemplatesRequest
	ListGoalTemplatesResponse = client.ListGoalTemplatesResponse

	GoalTemplates interface {
		ListGoalTemplates(ctx context.Context, in *ListGoalTemplatesRequest, opts ...grpc.CallOption) (*ListGoalTemplatesResponse, error)
	}

	defaultGoalTemplates struct {
		cli zrpc.Client
	}
)

func NewGoalTemplates(cli zrpc.Client) GoalTemplates {
	return &defaultGoalTemplates{
		cli: cli,
	}
}

func (m *defaultGoalTemplates) ListGoalTemplates(ctx context.Context, in *ListGoalTemplatesRequest, opts ...grpc.CallOption) (*ListGoalTemplatesResponse, error) {
	client := client.NewGoalTemplatesClient(m.cli.Conn())
	return client.ListGoalTemplates(ctx, in, opts...)
}
