// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: services/gateway/services/habits/api/v1/habits.proto

package habits

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Habit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Streak        int32                  `protobuf:"varint,6,opt,name=streak,proto3" json:"streak,omitempty"`
	Completed     bool                   `protobuf:"varint,7,opt,name=completed,proto3" json:"completed,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Completions   []*HabitCompletion     `protobuf:"bytes,10,rep,name=completions,proto3" json:"completions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Habit) Reset() {
	*x = Habit{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Habit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Habit) ProtoMessage() {}

func (x *Habit) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Habit.ProtoReflect.Descriptor instead.
func (*Habit) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{0}
}

func (x *Habit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Habit) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Habit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Habit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Habit) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Habit) GetStreak() int32 {
	if x != nil {
		return x.Streak
	}
	return 0
}

func (x *Habit) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *Habit) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Habit) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Habit) GetCompletions() []*HabitCompletion {
	if x != nil {
		return x.Completions
	}
	return nil
}

type HabitCompletion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HabitId       string                 `protobuf:"bytes,2,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HabitCompletion) Reset() {
	*x = HabitCompletion{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HabitCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HabitCompletion) ProtoMessage() {}

func (x *HabitCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HabitCompletion.ProtoReflect.Descriptor instead.
func (*HabitCompletion) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{1}
}

func (x *HabitCompletion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HabitCompletion) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *HabitCompletion) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *HabitCompletion) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ListHabitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"` // optional filter
	CompletedOnly bool                   `protobuf:"varint,3,opt,name=completed_only,json=completedOnly,proto3" json:"completed_only,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHabitsRequest) Reset() {
	*x = ListHabitsRequest{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHabitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHabitsRequest) ProtoMessage() {}

func (x *ListHabitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHabitsRequest.ProtoReflect.Descriptor instead.
func (*ListHabitsRequest) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{2}
}

func (x *ListHabitsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListHabitsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListHabitsRequest) GetCompletedOnly() bool {
	if x != nil {
		return x.CompletedOnly
	}
	return false
}

func (x *ListHabitsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListHabitsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListHabitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Habits        []*Habit               `protobuf:"bytes,1,rep,name=habits,proto3" json:"habits,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHabitsResponse) Reset() {
	*x = ListHabitsResponse{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHabitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHabitsResponse) ProtoMessage() {}

func (x *ListHabitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHabitsResponse.ProtoReflect.Descriptor instead.
func (*ListHabitsResponse) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{3}
}

func (x *ListHabitsResponse) GetHabits() []*Habit {
	if x != nil {
		return x.Habits
	}
	return nil
}

func (x *ListHabitsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateHabitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHabitRequest) Reset() {
	*x = CreateHabitRequest{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHabitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHabitRequest) ProtoMessage() {}

func (x *CreateHabitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHabitRequest.ProtoReflect.Descriptor instead.
func (*CreateHabitRequest) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{4}
}

func (x *CreateHabitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateHabitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHabitRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateHabitRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type CreateHabitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Habit         *Habit                 `protobuf:"bytes,1,opt,name=habit,proto3" json:"habit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHabitResponse) Reset() {
	*x = CreateHabitResponse{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHabitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHabitResponse) ProtoMessage() {}

func (x *CreateHabitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHabitResponse.ProtoReflect.Descriptor instead.
func (*CreateHabitResponse) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{5}
}

func (x *CreateHabitResponse) GetHabit() *Habit {
	if x != nil {
		return x.Habit
	}
	return nil
}

type GetHabitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHabitRequest) Reset() {
	*x = GetHabitRequest{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHabitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitRequest) ProtoMessage() {}

func (x *GetHabitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitRequest.ProtoReflect.Descriptor instead.
func (*GetHabitRequest) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{6}
}

func (x *GetHabitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetHabitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetHabitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Habit         *Habit                 `protobuf:"bytes,1,opt,name=habit,proto3" json:"habit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHabitResponse) Reset() {
	*x = GetHabitResponse{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHabitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitResponse) ProtoMessage() {}

func (x *GetHabitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitResponse.ProtoReflect.Descriptor instead.
func (*GetHabitResponse) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{7}
}

func (x *GetHabitResponse) GetHabit() *Habit {
	if x != nil {
		return x.Habit
	}
	return nil
}

type UpdateHabitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHabitRequest) Reset() {
	*x = UpdateHabitRequest{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHabitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHabitRequest) ProtoMessage() {}

func (x *UpdateHabitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHabitRequest.ProtoReflect.Descriptor instead.
func (*UpdateHabitRequest) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateHabitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateHabitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateHabitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateHabitRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateHabitRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type UpdateHabitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Habit         *Habit                 `protobuf:"bytes,1,opt,name=habit,proto3" json:"habit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHabitResponse) Reset() {
	*x = UpdateHabitResponse{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHabitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHabitResponse) ProtoMessage() {}

func (x *UpdateHabitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHabitResponse.ProtoReflect.Descriptor instead.
func (*UpdateHabitResponse) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateHabitResponse) GetHabit() *Habit {
	if x != nil {
		return x.Habit
	}
	return nil
}

type DeleteHabitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHabitRequest) Reset() {
	*x = DeleteHabitRequest{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHabitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHabitRequest) ProtoMessage() {}

func (x *DeleteHabitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHabitRequest.ProtoReflect.Descriptor instead.
func (*DeleteHabitRequest) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteHabitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteHabitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteHabitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHabitResponse) Reset() {
	*x = DeleteHabitResponse{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHabitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHabitResponse) ProtoMessage() {}

func (x *DeleteHabitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHabitResponse.ProtoReflect.Descriptor instead.
func (*DeleteHabitResponse) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{11}
}

type ToggleHabitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD format, defaults to today
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleHabitRequest) Reset() {
	*x = ToggleHabitRequest{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleHabitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleHabitRequest) ProtoMessage() {}

func (x *ToggleHabitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleHabitRequest.ProtoReflect.Descriptor instead.
func (*ToggleHabitRequest) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{12}
}

func (x *ToggleHabitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToggleHabitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ToggleHabitRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ToggleHabitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Habit         *Habit                 `protobuf:"bytes,1,opt,name=habit,proto3" json:"habit,omitempty"`
	Completed     bool                   `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleHabitResponse) Reset() {
	*x = ToggleHabitResponse{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleHabitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleHabitResponse) ProtoMessage() {}

func (x *ToggleHabitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleHabitResponse.ProtoReflect.Descriptor instead.
func (*ToggleHabitResponse) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{13}
}

func (x *ToggleHabitResponse) GetHabit() *Habit {
	if x != nil {
		return x.Habit
	}
	return nil
}

func (x *ToggleHabitResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type ResetTodayHabitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetTodayHabitsRequest) Reset() {
	*x = ResetTodayHabitsRequest{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetTodayHabitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetTodayHabitsRequest) ProtoMessage() {}

func (x *ResetTodayHabitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetTodayHabitsRequest.ProtoReflect.Descriptor instead.
func (*ResetTodayHabitsRequest) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{14}
}

func (x *ResetTodayHabitsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ResetTodayHabitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResetCount    int32                  `protobuf:"varint,1,opt,name=reset_count,json=resetCount,proto3" json:"reset_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetTodayHabitsResponse) Reset() {
	*x = ResetTodayHabitsResponse{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetTodayHabitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetTodayHabitsResponse) ProtoMessage() {}

func (x *ResetTodayHabitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetTodayHabitsResponse.ProtoReflect.Descriptor instead.
func (*ResetTodayHabitsResponse) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{15}
}

func (x *ResetTodayHabitsResponse) GetResetCount() int32 {
	if x != nil {
		return x.ResetCount
	}
	return 0
}

type GetHabitStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // week, month, year
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHabitStatsRequest) Reset() {
	*x = GetHabitStatsRequest{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHabitStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitStatsRequest) ProtoMessage() {}

func (x *GetHabitStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitStatsRequest.ProtoReflect.Descriptor instead.
func (*GetHabitStatsRequest) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{16}
}

func (x *GetHabitStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetHabitStatsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetHabitStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalHabits    int32                  `protobuf:"varint,1,opt,name=total_habits,json=totalHabits,proto3" json:"total_habits,omitempty"`
	CompletedToday int32                  `protobuf:"varint,2,opt,name=completed_today,json=completedToday,proto3" json:"completed_today,omitempty"`
	CurrentStreak  int32                  `protobuf:"varint,3,opt,name=current_streak,json=currentStreak,proto3" json:"current_streak,omitempty"`
	LongestStreak  int32                  `protobuf:"varint,4,opt,name=longest_streak,json=longestStreak,proto3" json:"longest_streak,omitempty"`
	CompletionRate float32                `protobuf:"fixed32,5,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`
	CategoryStats  []*CategoryStats       `protobuf:"bytes,6,rep,name=category_stats,json=categoryStats,proto3" json:"category_stats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetHabitStatsResponse) Reset() {
	*x = GetHabitStatsResponse{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHabitStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitStatsResponse) ProtoMessage() {}

func (x *GetHabitStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitStatsResponse.ProtoReflect.Descriptor instead.
func (*GetHabitStatsResponse) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{17}
}

func (x *GetHabitStatsResponse) GetTotalHabits() int32 {
	if x != nil {
		return x.TotalHabits
	}
	return 0
}

func (x *GetHabitStatsResponse) GetCompletedToday() int32 {
	if x != nil {
		return x.CompletedToday
	}
	return 0
}

func (x *GetHabitStatsResponse) GetCurrentStreak() int32 {
	if x != nil {
		return x.CurrentStreak
	}
	return 0
}

func (x *GetHabitStatsResponse) GetLongestStreak() int32 {
	if x != nil {
		return x.LongestStreak
	}
	return 0
}

func (x *GetHabitStatsResponse) GetCompletionRate() float32 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

func (x *GetHabitStatsResponse) GetCategoryStats() []*CategoryStats {
	if x != nil {
		return x.CategoryStats
	}
	return nil
}

type CategoryStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Completed     int32                  `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryStats) Reset() {
	*x = CategoryStats{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryStats) ProtoMessage() {}

func (x *CategoryStats) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryStats.ProtoReflect.Descriptor instead.
func (*CategoryStats) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{18}
}

func (x *CategoryStats) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CategoryStats) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CategoryStats) GetCompleted() int32 {
	if x != nil {
		return x.Completed
	}
	return 0
}

type GetHabitCalendarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"` // YYYY-MM format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHabitCalendarRequest) Reset() {
	*x = GetHabitCalendarRequest{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHabitCalendarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitCalendarRequest) ProtoMessage() {}

func (x *GetHabitCalendarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitCalendarRequest.ProtoReflect.Descriptor instead.
func (*GetHabitCalendarRequest) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{19}
}

func (x *GetHabitCalendarRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetHabitCalendarRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

type GetHabitCalendarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          []*CalendarDay         `protobuf:"bytes,1,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHabitCalendarResponse) Reset() {
	*x = GetHabitCalendarResponse{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHabitCalendarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitCalendarResponse) ProtoMessage() {}

func (x *GetHabitCalendarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitCalendarResponse.ProtoReflect.Descriptor instead.
func (*GetHabitCalendarResponse) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{20}
}

func (x *GetHabitCalendarResponse) GetDays() []*CalendarDay {
	if x != nil {
		return x.Days
	}
	return nil
}

type CalendarDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Completed     int32                  `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalendarDay) Reset() {
	*x = CalendarDay{}
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarDay) ProtoMessage() {}

func (x *CalendarDay) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_services_habits_api_v1_habits_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarDay.ProtoReflect.Descriptor instead.
func (*CalendarDay) Descriptor() ([]byte, []int) {
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP(), []int{21}
}

func (x *CalendarDay) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CalendarDay) GetCompleted() int32 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *CalendarDay) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_services_gateway_services_habits_api_v1_habits_proto protoreflect.FileDescriptor

const file_services_gateway_services_habits_api_v1_habits_proto_rawDesc = "" +
	"\n" +
	"4services/gateway/services/habits/api/v1/habits.proto\x12\x06habits\"\xb1\x02\n" +
	"\x05Habit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x16\n" +
	"\x06streak\x18\x06 \x01(\x05R\x06streak\x12\x1c\n" +
	"\tcompleted\x18\a \x01(\bR\tcompleted\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x129\n" +
	"\vcompletions\x18\n" +
	" \x03(\v2\x17.habits.HabitCompletionR\vcompletions\"s\n" +
	"\x0fHabitCompletion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bhabit_id\x18\x02 \x01(\tR\ahabitId\x12!\n" +
	"\fcompleted_at\x18\x03 \x01(\tR\vcompletedAt\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\"\x9d\x01\n" +
	"\x11ListHabitsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12%\n" +
	"\x0ecompleted_only\x18\x03 \x01(\bR\rcompletedOnly\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"Q\n" +
	"\x12ListHabitsResponse\x12%\n" +
	"\x06habits\x18\x01 \x03(\v2\r.habits.HabitR\x06habits\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x7f\n" +
	"\x12CreateHabitRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\":\n" +
	"\x13CreateHabitResponse\x12#\n" +
	"\x05habit\x18\x01 \x01(\v2\r.habits.HabitR\x05habit\":\n" +
	"\x0fGetHabitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"7\n" +
	"\x10GetHabitResponse\x12#\n" +
	"\x05habit\x18\x01 \x01(\v2\r.habits.HabitR\x05habit\"\x8f\x01\n" +
	"\x12UpdateHabitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\":\n" +
	"\x13UpdateHabitResponse\x12#\n" +
	"\x05habit\x18\x01 \x01(\v2\r.habits.HabitR\x05habit\"=\n" +
	"\x12DeleteHabitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x15\n" +
	"\x13DeleteHabitResponse\"Q\n" +
	"\x12ToggleHabitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"X\n" +
	"\x13ToggleHabitResponse\x12#\n" +
	"\x05habit\x18\x01 \x01(\v2\r.habits.HabitR\x05habit\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\bR\tcompleted\"2\n" +
	"\x17ResetTodayHabitsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x18ResetTodayHabitsResponse\x12\x1f\n" +
	"\vreset_count\x18\x01 \x01(\x05R\n" +
	"resetCount\"G\n" +
	"\x14GetHabitStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"\x98\x02\n" +
	"\x15GetHabitStatsResponse\x12!\n" +
	"\ftotal_habits\x18\x01 \x01(\x05R\vtotalHabits\x12'\n" +
	"\x0fcompleted_today\x18\x02 \x01(\x05R\x0ecompletedToday\x12%\n" +
	"\x0ecurrent_streak\x18\x03 \x01(\x05R\rcurrentStreak\x12%\n" +
	"\x0elongest_streak\x18\x04 \x01(\x05R\rlongestStreak\x12'\n" +
	"\x0fcompletion_rate\x18\x05 \x01(\x02R\x0ecompletionRate\x12<\n" +
	"\x0ecategory_stats\x18\x06 \x03(\v2\x15.habits.CategoryStatsR\rcategoryStats\"_\n" +
	"\rCategoryStats\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\x05R\tcompleted\"H\n" +
	"\x17GetHabitCalendarRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\"C\n" +
	"\x18GetHabitCalendarResponse\x12'\n" +
	"\x04days\x18\x01 \x03(\v2\x13.habits.CalendarDayR\x04days\"U\n" +
	"\vCalendarDay\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\x05R\tcompleted\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total2\xaf\x05\n" +
	"\rHabitsService\x12C\n" +
	"\n" +
	"ListHabits\x12\x19.habits.ListHabitsRequest\x1a\x1a.habits.ListHabitsResponse\x12F\n" +
	"\vCreateHabit\x12\x1a.habits.CreateHabitRequest\x1a\x1b.habits.CreateHabitResponse\x12=\n" +
	"\bGetHabit\x12\x17.habits.GetHabitRequest\x1a\x18.habits.GetHabitResponse\x12F\n" +
	"\vUpdateHabit\x12\x1a.habits.UpdateHabitRequest\x1a\x1b.habits.UpdateHabitResponse\x12F\n" +
	"\vDeleteHabit\x12\x1a.habits.DeleteHabitRequest\x1a\x1b.habits.DeleteHabitResponse\x12F\n" +
	"\vToggleHabit\x12\x1a.habits.ToggleHabitRequest\x1a\x1b.habits.ToggleHabitResponse\x12U\n" +
	"\x10ResetTodayHabits\x12\x1f.habits.ResetTodayHabitsRequest\x1a .habits.ResetTodayHabitsResponse\x12L\n" +
	"\rGetHabitStats\x12\x1c.habits.GetHabitStatsRequest\x1a\x1d.habits.GetHabitStatsResponse\x12U\n" +
	"\x10GetHabitCalendar\x12\x1f.habits.GetHabitCalendarRequest\x1a .habits.GetHabitCalendarResponseB\n" +
	"Z\b./habitsb\x06proto3"

var (
	file_services_gateway_services_habits_api_v1_habits_proto_rawDescOnce sync.Once
	file_services_gateway_services_habits_api_v1_habits_proto_rawDescData []byte
)

func file_services_gateway_services_habits_api_v1_habits_proto_rawDescGZIP() []byte {
	file_services_gateway_services_habits_api_v1_habits_proto_rawDescOnce.Do(func() {
		file_services_gateway_services_habits_api_v1_habits_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_gateway_services_habits_api_v1_habits_proto_rawDesc), len(file_services_gateway_services_habits_api_v1_habits_proto_rawDesc)))
	})
	return file_services_gateway_services_habits_api_v1_habits_proto_rawDescData
}

var file_services_gateway_services_habits_api_v1_habits_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_services_gateway_services_habits_api_v1_habits_proto_goTypes = []any{
	(*Habit)(nil),                    // 0: habits.Habit
	(*HabitCompletion)(nil),          // 1: habits.HabitCompletion
	(*ListHabitsRequest)(nil),        // 2: habits.ListHabitsRequest
	(*ListHabitsResponse)(nil),       // 3: habits.ListHabitsResponse
	(*CreateHabitRequest)(nil),       // 4: habits.CreateHabitRequest
	(*CreateHabitResponse)(nil),      // 5: habits.CreateHabitResponse
	(*GetHabitRequest)(nil),          // 6: habits.GetHabitRequest
	(*GetHabitResponse)(nil),         // 7: habits.GetHabitResponse
	(*UpdateHabitRequest)(nil),       // 8: habits.UpdateHabitRequest
	(*UpdateHabitResponse)(nil),      // 9: habits.UpdateHabitResponse
	(*DeleteHabitRequest)(nil),       // 10: habits.DeleteHabitRequest
	(*DeleteHabitResponse)(nil),      // 11: habits.DeleteHabitResponse
	(*ToggleHabitRequest)(nil),       // 12: habits.ToggleHabitRequest
	(*ToggleHabitResponse)(nil),      // 13: habits.ToggleHabitResponse
	(*ResetTodayHabitsRequest)(nil),  // 14: habits.ResetTodayHabitsRequest
	(*ResetTodayHabitsResponse)(nil), // 15: habits.ResetTodayHabitsResponse
	(*GetHabitStatsRequest)(nil),     // 16: habits.GetHabitStatsRequest
	(*GetHabitStatsResponse)(nil),    // 17: habits.GetHabitStatsResponse
	(*CategoryStats)(nil),            // 18: habits.CategoryStats
	(*GetHabitCalendarRequest)(nil),  // 19: habits.GetHabitCalendarRequest
	(*GetHabitCalendarResponse)(nil), // 20: habits.GetHabitCalendarResponse
	(*CalendarDay)(nil),              // 21: habits.CalendarDay
}
var file_services_gateway_services_habits_api_v1_habits_proto_depIdxs = []int32{
	1,  // 0: habits.Habit.completions:type_name -> habits.HabitCompletion
	0,  // 1: habits.ListHabitsResponse.habits:type_name -> habits.Habit
	0,  // 2: habits.CreateHabitResponse.habit:type_name -> habits.Habit
	0,  // 3: habits.GetHabitResponse.habit:type_name -> habits.Habit
	0,  // 4: habits.UpdateHabitResponse.habit:type_name -> habits.Habit
	0,  // 5: habits.ToggleHabitResponse.habit:type_name -> habits.Habit
	18, // 6: habits.GetHabitStatsResponse.category_stats:type_name -> habits.CategoryStats
	21, // 7: habits.GetHabitCalendarResponse.days:type_name -> habits.CalendarDay
	2,  // 8: habits.HabitsService.ListHabits:input_type -> habits.ListHabitsRequest
	4,  // 9: habits.HabitsService.CreateHabit:input_type -> habits.CreateHabitRequest
	6,  // 10: habits.HabitsService.GetHabit:input_type -> habits.GetHabitRequest
	8,  // 11: habits.HabitsService.UpdateHabit:input_type -> habits.UpdateHabitRequest
	10, // 12: habits.HabitsService.DeleteHabit:input_type -> habits.DeleteHabitRequest
	12, // 13: habits.HabitsService.ToggleHabit:input_type -> habits.ToggleHabitRequest
	14, // 14: habits.HabitsService.ResetTodayHabits:input_type -> habits.ResetTodayHabitsRequest
	16, // 15: habits.HabitsService.GetHabitStats:input_type -> habits.GetHabitStatsRequest
	19, // 16: habits.HabitsService.GetHabitCalendar:input_type -> habits.GetHabitCalendarRequest
	3,  // 17: habits.HabitsService.ListHabits:output_type -> habits.ListHabitsResponse
	5,  // 18: habits.HabitsService.CreateHabit:output_type -> habits.CreateHabitResponse
	7,  // 19: habits.HabitsService.GetHabit:output_type -> habits.GetHabitResponse
	9,  // 20: habits.HabitsService.UpdateHabit:output_type -> habits.UpdateHabitResponse
	11, // 21: habits.HabitsService.DeleteHabit:output_type -> habits.DeleteHabitResponse
	13, // 22: habits.HabitsService.ToggleHabit:output_type -> habits.ToggleHabitResponse
	15, // 23: habits.HabitsService.ResetTodayHabits:output_type -> habits.ResetTodayHabitsResponse
	17, // 24: habits.HabitsService.GetHabitStats:output_type -> habits.GetHabitStatsResponse
	20, // 25: habits.HabitsService.GetHabitCalendar:output_type -> habits.GetHabitCalendarResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_services_gateway_services_habits_api_v1_habits_proto_init() }
func file_services_gateway_services_habits_api_v1_habits_proto_init() {
	if File_services_gateway_services_habits_api_v1_habits_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_gateway_services_habits_api_v1_habits_proto_rawDesc), len(file_services_gateway_services_habits_api_v1_habits_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_gateway_services_habits_api_v1_habits_proto_goTypes,
		DependencyIndexes: file_services_gateway_services_habits_api_v1_habits_proto_depIdxs,
		MessageInfos:      file_services_gateway_services_habits_api_v1_habits_proto_msgTypes,
	}.Build()
	File_services_gateway_services_habits_api_v1_habits_proto = out.File
	file_services_gateway_services_habits_api_v1_habits_proto_goTypes = nil
	file_services_gateway_services_habits_api_v1_habits_proto_depIdxs = nil
}
