#!/usr/bin/env bash
# Production deploy entrypoint — runs ON the VM, invoked by GitHub Actions
# (see .github/workflows/deploy.yml) or manually over SSH.
#
# Steps: sync repo to origin/main → pull GHCR images → run migrations →
# recreate changed containers → verify health endpoints. Exits non-zero on
# any failure so the CI deploy job goes red.
#
# Rollback to a previous build (images are tagged sha-<commit>):
#   cd /home/ubuntu/growth-server
#   BACKEND_TAG=sha-<sha> docker compose -f deploy/docker-compose.prod.yml \
#     --env-file deploy/.env.prod --profile admin up -d --no-deps \
#     auth client search ai-coach filemanager notifications ai-coach-consumer \
#     search-sync gateway ai-gateway adminway caddy

set -euo pipefail

REPO_DIR=/home/ubuntu/growth-server
cd "$REPO_DIR"

# Sync tracked files (compose, Caddyfile, configs) to the pushed commit.
# deploy/.env.prod and logs/ are gitignored, so they survive the reset.
git fetch origin main
git reset --hard origin/main

COMPOSE=(docker compose -f deploy/docker-compose.prod.yml --env-file deploy/.env.prod --profile admin --profile tools --profile monitoring)

# --- Secrets layout -------------------------------------------------------
# .env.prod is only for compose-time interpolation; app containers read
# .env.shared (non-secrets) + .env.<svc> (per-service secrets). split-env.sh
# performs the one-time migration from the old all-in-one .env.prod —
# idempotent, a no-op once split. setup-db-roles.sh (run after migrations)
# then fills each service's POSTGRES_DATASOURCE with a least-privilege role.
deploy/scripts/split-env.sh

touch deploy/.env.shared deploy/.env.auth deploy/.env.adminway \
  deploy/.env.client deploy/.env.search deploy/.env.ai-coach \
  deploy/.env.ai-gateway deploy/.env.ai-coach-consumer deploy/.env.filemanager \
  deploy/.env.notifications deploy/.env.search-sync deploy/.env.analytics-consumer \
  deploy/.env.gateway

# --- Admin panel IP allowlist --------------------------------------------
# Regenerate the Caddy matcher from ADMIN_ALLOWED_IPS (deploy/.env.prod:
# space- or comma-separated CIDRs). Unset → matcher never matches → panel
# reachable from anywhere (same as before), with a loud warning.
ADMIN_IPS=$(grep '^ADMIN_ALLOWED_IPS=' deploy/.env.prod | head -1 | cut -d= -f2- | tr ',' ' ' | tr -d '"'"'" | xargs || true)
ALLOWLIST=deploy/caddy/admin-allowlist.caddyfile
if [ -n "$ADMIN_IPS" ]; then
  {
    echo "# GENERATED by deploy/deploy.sh from ADMIN_ALLOWED_IPS — do not edit."
    echo "@admin_forbidden not remote_ip $ADMIN_IPS"
    printf 'handle @admin_forbidden {\n\trespond "Forbidden" 403\n}\n'
  } > "$ALLOWLIST"
  echo "==> admin allowlist active: $ADMIN_IPS"
else
  cat > "$ALLOWLIST" <<'EOF'
# GENERATED by deploy/deploy.sh — ADMIN_ALLOWED_IPS unset, allowlist disabled.
@admin_forbidden {
	path /__admin_allowlist_disabled__
}
handle @admin_forbidden {
	respond "Forbidden" 403
}
EOF
  echo "!! WARNING: ADMIN_ALLOWED_IPS unset in deploy/.env.prod — admin panel is" >&2
  echo "!! reachable from any IP. Set it to lock down admin.evolella.com." >&2
fi

if ! grep -qs '^JWT_PRIVATE_KEY=' deploy/.env.auth deploy/.env.prod; then
  echo "!! WARNING: JWT_PRIVATE_KEY unset (deploy/.env.auth) — auth cannot sign" >&2
  echo "!! tokens and will fail closed at startup." >&2
fi
if ! grep -qs '^ADMIN_JWT_PRIVATE_KEY=' deploy/.env.adminway deploy/.env.prod; then
  echo "!! WARNING: ADMIN_JWT_PRIVATE_KEY unset (deploy/.env.adminway) — adminway" >&2
  echo "!! cannot sign tokens and will fail closed at startup." >&2
fi

# The migrate service reads DATABASE_URL from the env file. Create it once
# from the existing Postgres credentials without printing anything.
if ! grep -q '^DATABASE_URL=' deploy/.env.prod; then
  PG_USER=$(grep '^POSTGRES_USER=' deploy/.env.prod | head -1 | cut -d= -f2-)
  PG_PASS=$(grep '^POSTGRES_PASSWORD=' deploy/.env.prod | head -1 | cut -d= -f2-)
  PG_DB=$(grep '^POSTGRES_DB=' deploy/.env.prod | head -1 | cut -d= -f2-)
  printf 'DATABASE_URL=postgres://%s:%s@postgres:5432/%s?sslmode=disable\n' \
    "$PG_USER" "$PG_PASS" "$PG_DB" >> deploy/.env.prod
fi

BACKEND_SERVICES=(auth client search ai-coach filemanager notifications ai-coach-consumer search-sync analytics-consumer gateway ai-gateway adminway)
MONITORING_SERVICES=(prometheus grafana loki promtail tempo cadvisor alertmanager node-exporter blackbox)

echo "==> Pulling images"
"${COMPOSE[@]}" pull "${BACKEND_SERVICES[@]}" migrate "${MONITORING_SERVICES[@]}"

echo "==> Running migrations"
# -T + </dev/null: `compose run` attaches stdin by default and would CONSUME
# the rest of this script (the script itself is piped in over SSH), so the
# deploy silently stopped after migrations. No trailing args either:
# `compose run <svc> cmd` would REPLACE the service command (which carries
# -path/-database/up).
"${COMPOSE[@]}" run --rm -T migrate < /dev/null

echo "==> Reconciling per-service Postgres roles"
# Creates/updates svc_* roles and re-grants on the current schema (tables added
# by the migration above get their grants here). Also writes each service's
# POSTGRES_DATASOURCE into deploy/.env.<svc>.
deploy/scripts/setup-db-roles.sh

echo "==> Recreating changed services"
# --force-recreate: deploy/config/*.yaml are bind-mounted, not baked into the
# image, so compose sees no container definition change on config-only deploys
# and would silently keep running the old config.
"${COMPOSE[@]}" up -d --no-deps --force-recreate "${BACKEND_SERVICES[@]}" "${MONITORING_SERVICES[@]}" caddy

echo "==> Re-enforcing MinIO bucket policy"
# Idempotent: reapplies the scoped anonymous policy (articles/* download
# only) and verifies it round-tripped. Fails the deploy if MinIO is
# unreachable or the policy doesn't stick — an open bucket must never ride
# along on a green deploy.
deploy/scripts/harden-minio.sh

echo "==> Health checks"
# Per-service docker healthchecks first — they catch a service that is
# running but wedged (the external /health check only proves Caddy is up).
# Containers are named deploy-<svc>-1 (compose project = deploy).
unhealthy=""
for _ in $(seq 1 40); do
  unhealthy=""
  for svc in "${BACKEND_SERVICES[@]}"; do
    status=$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' \
      "deploy-${svc}-1" 2>/dev/null || echo missing)
    [ "$status" = healthy ] || unhealthy="$unhealthy $svc:${status}"
  done
  [ -z "$unhealthy" ] && break
  sleep 3
done

if [ -n "$unhealthy" ]; then
  echo "!! Services failed health checks:$unhealthy" >&2
  docker compose -f deploy/docker-compose.prod.yml --env-file deploy/.env.prod ps >&2
  exit 1
fi
echo "==> All services report healthy"

echo "==> Verifying MinIO bucket stays private from the outside"
# Unsigned request to the bucket root must be refused — 403 from MinIO's
# private policy, 404 from Caddy's presigned-only matcher. Anything else
# (200/301/5xx) means anonymous file access may be open. Retried briefly:
# Caddy was just recreated and may still be coming up (transient 000/5xx).
files_code=000
for _ in $(seq 1 10); do
  files_code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 \
    "https://api.evolella.com/files/growthmind/" || echo 000)
  [ "$files_code" = "403" ] || [ "$files_code" = "404" ] && break
  sleep 3
done
if [ "$files_code" != "403" ] && [ "$files_code" != "404" ]; then
  echo "!! /files/ answered an unsigned request with HTTP $files_code" >&2
  echo "!! — anonymous MinIO access may be open. Aborting deploy." >&2
  exit 1
fi

check() { curl -fsS --max-time 5 -o /dev/null "$1"; }
for _ in $(seq 1 30); do
  if check https://api.evolella.com/health \
    && check https://app.evolella.com \
    && check https://admin.evolella.com/login; then
    echo "==> Deploy healthy"
    docker image prune -f >/dev/null
    exit 0
  fi
  sleep 2
done

echo "!! Health checks failed after deploy" >&2
docker compose -f deploy/docker-compose.prod.yml --env-file deploy/.env.prod ps >&2
docker compose -f deploy/docker-compose.prod.yml --env-file deploy/.env.prod logs --tail 30 gateway adminway ai-gateway >&2
exit 1
