#!/usr/bin/env bash
# Regenerate deploy/caddy/paddle-webhook-ips.caddyfile from Paddle's live IP
# endpoints (https://api.paddle.com/ips + sandbox-api.paddle.com/ips — the
# endpoints are the source of truth and the lists can change).
#
# The generated file rejects non-Paddle sources for
# POST /api/v1/billing/paddle-webhook at the edge. Signature verification in
# the app remains the primary check; this is defense in depth.
#
# Usage:  ./fetch-paddle-webhook-ips.sh            # refresh the file
# Schedule on the VM (cron):  */30 * * * * /home/ubuntu/growth-server/deploy/scripts/fetch-paddle-webhook-ips.sh
# The script reloads Caddy in-place when the allowlist actually changed.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/caddy/paddle-webhook-ips.caddyfile"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

fetch_cidrs() {
	curl -fsS --max-time 15 "$1" \
		| python3 -c 'import json,sys; print(" ".join(json.load(sys.stdin)["data"]["ipv4_cidrs"]))'
}

LIVE_CIDRS="$(fetch_cidrs https://api.paddle.com/ips)"
SANDBOX_CIDRS="$(fetch_cidrs https://sandbox-api.paddle.com/ips)"

if [ -z "$LIVE_CIDRS" ] || [ -z "$SANDBOX_CIDRS" ]; then
	echo "error: empty CIDR list from Paddle — keeping existing file" >&2
	exit 1
fi

# Path match + "not remote_ip <allowlist>" is more specific than the generic
# /api/v1/* handle, so Caddy evaluates it first. Allowed sources fall through
# to the normal gateway route; everyone else gets 403 before reaching the app.
cat >"$TMP" <<EOF
# AUTO-GENERATED by deploy/scripts/fetch-paddle-webhook-ips.sh — do not edit.
# Sources: https://api.paddle.com/ips + https://sandbox-api.paddle.com/ips
# Regenerated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
@paddle_webhook_hostile {
	path /api/v1/billing/paddle-webhook
	not remote_ip $LIVE_CIDRS $SANDBOX_CIDRS
}
handle @paddle_webhook_hostile {
	respond "Forbidden" 403
}
EOF

# Sanity check: the file must contain at least one /32 CIDR.
grep -q '/32' "$TMP" || { echo "error: generated file has no CIDRs" >&2; exit 1; }

if cmp -s "$TMP" "$OUT" 2>/dev/null; then
	exit 0  # unchanged — nothing to do
fi

mv "$TMP" "$OUT"
echo "updated $OUT"

# Reload Caddy if it's running so the new list takes effect immediately.
if docker ps --format '{{.Names}}' | grep -q '^deploy-caddy-1$'; then
	docker exec deploy-caddy-1 caddy reload --config /etc/caddy/Caddyfile --force \
		&& echo "caddy reloaded"
fi
