root = "."
tmp_dir = "tmp/air-adminway"

[build]
cmd = "go build -o ./bin/adminway ./services/adminway/adminapi"
entrypoint = ["./bin/adminway", "-f", "services/adminway/adminapi/etc/adminapi.yaml"]
include_ext = ["go", "yaml", "yml", "tpl", "tmpl", "html"]
include_dir = ["services/adminway", "pkg"]
exclude_dir = ["tmp", "bin", "logs", "deploy", "docs", "sql", "scripts", "vendor", "testdata", "node_modules"]
exclude_regex = ["_test\\.go"]
delay = 1000
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true
