// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_tickets.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPushTicket = `-- name: CreatePushTicket :exec

INSERT INTO push_tickets (ticket_id, push_token, user_id, notification_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (ticket_id, push_token) DO NOTHING
`

// Push ticket persistence for async Expo receipt processing.
// Owned exclusively by the notifications service.
func (q *Queries) CreatePushTicket(ctx context.Context, ticketID string, pushToken string, userID uuid.UUID, notificationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createPushTicket,
		ticketID,
		pushToken,
		userID,
		notificationID,
	)
	return err
}

const deleteOldPushTickets = `-- name: DeleteOldPushTickets :exec
DELETE FROM push_tickets
WHERE created_at < $1 AND receipt_status != 'pending'
`

func (q *Queries) DeleteOldPushTickets(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldPushTickets, createdAt)
	return err
}

const listPendingPushTickets = `-- name: ListPendingPushTickets :many
SELECT id, ticket_id, push_token, user_id, notification_id, receipt_status, receipt_error, receipt_checked_at, created_at
FROM push_tickets
WHERE receipt_status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingPushTickets(ctx context.Context, limit int32) ([]PushTicket, error) {
	rows, err := q.db.Query(ctx, listPendingPushTickets, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushTicket{}
	for rows.Next() {
		var i PushTicket
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.PushToken,
			&i.UserID,
			&i.NotificationID,
			&i.ReceiptStatus,
			&i.ReceiptError,
			&i.ReceiptCheckedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPushTicketReceiptError = `-- name: MarkPushTicketReceiptError :exec
UPDATE push_tickets
SET receipt_status = 'error', receipt_error = $3, receipt_checked_at = now()
WHERE ticket_id = $1 AND push_token = $2
`

func (q *Queries) MarkPushTicketReceiptError(ctx context.Context, ticketID string, pushToken string, receiptError *string) error {
	_, err := q.db.Exec(ctx, markPushTicketReceiptError, ticketID, pushToken, receiptError)
	return err
}

const markPushTicketReceiptOK = `-- name: MarkPushTicketReceiptOK :exec
UPDATE push_tickets
SET receipt_status = 'ok', receipt_checked_at = now()
WHERE ticket_id = $1 AND push_token = $2
`

func (q *Queries) MarkPushTicketReceiptOK(ctx context.Context, ticketID string, pushToken string) error {
	_, err := q.db.Exec(ctx, markPushTicketReceiptOK, ticketID, pushToken)
	return err
}
