// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BumpCheckInCountToday(ctx context.Context, userID uuid.UUID) error
	// Cancel all unsent reminders of a given type for a user. Used when the user
	// disables a notification preference (e.g. habit reminders) so no further
	// reminders of that type fire until re-enabled.
	CancelPendingByType(ctx context.Context, userID uuid.UUID, type_ string) (int64, error)
	CancelPendingReminderForDate(ctx context.Context, userID uuid.UUID, type_ string, column3 pgtype.Date, column4 string) error
	// Claim due, unclaimed, unsent reminders by setting claimed_at (a lease).
	// Does NOT set sent_at — that happens only after successful Kafka publish
	// via MarkReminderSent. Stale claims (claimed_at older than the lease window)
	// are released by ReleaseStaleClaims so a crashed scheduler does not lose
	// reminders. Uses FOR UPDATE SKIP LOCKED so multiple instances don't claim
	// the same rows.
	ClaimDueReminders(ctx context.Context, limit int32) ([]ClaimDueRemindersRow, error)
	CountNotificationsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateNotification(ctx context.Context, title string, message string, type_ string, userID uuid.UUID) (CreateNotificationRow, error)
	// Batch insert the same notification for many users (admin broadcast).
	// Uses unnest to fan out a single INSERT...SELECT over the uuid array.
	CreateNotificationsForUsers(ctx context.Context, title string, message string, type_ string, column4 []uuid.UUID) (int64, error)
	DecrementHabitCount(ctx context.Context, userID uuid.UUID) error
	DeleteAllNotificationsByUser(ctx context.Context, userID uuid.UUID) error
	DeleteNotification(ctx context.Context, id uuid.UUID) error
	DeleteNotificationPreferences(ctx context.Context, userID uuid.UUID) error
	DeleteNotificationPreferencesByUser(ctx context.Context, userID uuid.UUID) error
	// Bulk cleanup queries for user_deleted event consumers.
	DeleteNotificationsByUser(ctx context.Context, userID uuid.UUID) error
	DeleteReminderState(ctx context.Context, userID uuid.UUID) error
	DeleteRemindersByUser(ctx context.Context, userID uuid.UUID) error
	// Reminders: sent_at IS NULL means pending.
	EnqueueReminder(ctx context.Context, userID uuid.UUID, type_ string, scheduledAt pgtype.Timestamptz, metadata []byte) (EnqueueReminderRow, error)
	GetNotification(ctx context.Context, id uuid.UUID) (GetNotificationRow, error)
	GetNotificationPreferences(ctx context.Context, userID uuid.UUID) (NotificationPreference, error)
	GetPendingByUser(ctx context.Context, userID uuid.UUID) ([]GetPendingByUserRow, error)
	GetReminderState(ctx context.Context, userID uuid.UUID) (ReminderState, error)
	GetUnreadCount(ctx context.Context, userID uuid.UUID) (int64, error)
	IncrementHabitCount(ctx context.Context, userID uuid.UUID) error
	IsEventProcessed(ctx context.Context, eventID string) (bool, error)
	ListNotifications(ctx context.Context, limit int32, offset int32) ([]ListNotificationsRow, error)
	ListNotificationsByType(ctx context.Context, userID uuid.UUID, type_ string, limit int32, offset int32) ([]ListNotificationsByTypeRow, error)
	// Keyset pagination for typed notification feeds.
	ListNotificationsByTypeKeyset(ctx context.Context, userID uuid.UUID, type_ string, column3 pgtype.Timestamptz, limit int32) ([]ListNotificationsByTypeKeysetRow, error)
	ListNotificationsForUser(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]ListNotificationsForUserRow, error)
	// Keyset pagination: more efficient than OFFSET for deep pages.
	ListNotificationsForUserKeyset(ctx context.Context, userID uuid.UUID, column2 pgtype.Timestamptz, limit int32) ([]ListNotificationsForUserKeysetRow, error)
	ListUnreadNotifications(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]ListUnreadNotificationsRow, error)
	// Keyset pagination for unread notifications feed.
	ListUnreadNotificationsKeyset(ctx context.Context, userID uuid.UUID, column2 pgtype.Timestamptz, limit int32) ([]ListUnreadNotificationsKeysetRow, error)
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error
	MarkEventProcessed(ctx context.Context, eventID string) error
	MarkNotificationRead(ctx context.Context, id uuid.UUID) (MarkNotificationReadRow, error)
	MarkReminderSent(ctx context.Context, id uuid.UUID) (MarkReminderSentRow, error)
	// Release claims older than the lease window (minutes) so they can be
	// re-claimed by the next tick. This handles scheduler crashes: a reminder
	// that was claimed but never acked (sent_at still NULL) becomes claimable
	// again after the lease expires.
	ReleaseStaleClaims(ctx context.Context, dollar_1 int32) (int64, error)
	SetOnboardingCompleted(ctx context.Context, userID uuid.UUID) error
	UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error)
	UpsertReminderStateSettings(ctx context.Context, userID uuid.UUID, timezone string, checkInTime pgtype.Time, habitReminders bool) error
}

var _ Querier = (*Queries)(nil)
