// Code scaffolded by goctl. Safe to edit.
// goctl 1.10.1

package main

import (
	"context"
	"flag"
	"fmt"
	"net/http"

	"github.com/suleymanmyradov/growth-server/pkg/configsafe"
	"github.com/suleymanmyradov/growth-server/pkg/httpx/errors"
	"github.com/suleymanmyradov/growth-server/services/ai-gateway/aiapi/internal/config"
	"github.com/suleymanmyradov/growth-server/services/ai-gateway/aiapi/internal/handler"
	"github.com/suleymanmyradov/growth-server/services/ai-gateway/aiapi/internal/handler/personalization"
	"github.com/suleymanmyradov/growth-server/services/ai-gateway/aiapi/internal/handler/voice"
	"github.com/suleymanmyradov/growth-server/services/ai-gateway/aiapi/internal/middleware"
	"github.com/suleymanmyradov/growth-server/services/ai-gateway/aiapi/internal/svc"

	"github.com/zeromicro/go-zero/core/conf"
	"github.com/zeromicro/go-zero/core/logx"
	"github.com/zeromicro/go-zero/rest"
	"github.com/zeromicro/go-zero/rest/httpx"
)

var configFile = flag.String("f", "etc/aiapi.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	logx.Infof("starting ai-gateway with config: %+v", configsafe.MaskSecrets(c))

	// Harden defaults if not explicitly configured in YAML
	if c.MaxConns == 0 {
		c.MaxConns = 10000
	}
	if c.MaxBytes == 0 {
		c.MaxBytes = 25 << 20 // 25 MB — voice uploads can be large
	}

	server := rest.MustNewServer(c.RestConf)
	defer server.Stop()

	// Install a custom error handler so gRPC status errors returned from logic
	// layers are mapped to proper HTTP status codes with JSON bodies.
	httpx.SetErrorHandlerCtx(func(_ context.Context, err error) (int, any) {
		code, body := errors.GrpcErrorResponse(err)
		return code, body
	})

	ctx := svc.NewServiceContext(c)

	// Order matters: rate limit first so abusive requests are rejected
	// before auth or response-shape overhead.
	server.Use(ctx.RateLimit)
	server.Use(middleware.ResponseShapeMiddleware())

	handler.RegisterHandlers(server, ctx)

	// Custom-transport routes — not generated by goctl api because they use
	// multipart/form-data or text/event-stream transports the .api format
	// cannot express. Documented in swagger/custom-transports.yaml and merged
	// into swagger-combined.json by make swagger-combined.
	//
	// Coaching stream (SSE): agentic coaching via StreamAgent with on-demand
	// tool calls. The handler is a thin wrapper; all orchestration lives in
	// personalization.StreamCoaching.
	// Voice routes: dictate (multipart audio → text) and live voice chat
	// (multipart audio → SSE stream of transcript + coaching + TTS audio).
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{ctx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/personalization/coaching-stream",
					Handler: personalization.StreamPersonalizedCoachingHandler(ctx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/personalization/transcribe",
					Handler: voice.TranscribeHandler(ctx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/personalization/voice-turn",
					Handler: voice.VoiceTurnHandler(ctx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	fmt.Printf("Starting ai-gateway at %s:%d...\n", c.Host, c.Port)
	server.Start()
}
