// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: client.proto

package server

import (
	"context"

	"github.com/suleymanmyradov/growth-server/services/microservices/client/rpc/internal/logic/settings"
	"github.com/suleymanmyradov/growth-server/services/microservices/client/rpc/internal/svc"
	"github.com/suleymanmyradov/growth-server/services/microservices/client/rpc/pb/client"
)

type SettingsServer struct {
	svcCtx *svc.ServiceContext
	client.UnimplementedSettingsServer
}

func NewSettingsServer(svcCtx *svc.ServiceContext) *SettingsServer {
	return &SettingsServer{
		svcCtx: svcCtx,
	}
}

func (s *SettingsServer) GetSettings(ctx context.Context, in *client.GetSettingsRequest) (*client.GetSettingsResponse, error) {
	l := settingslogic.NewGetSettingsLogic(ctx, s.svcCtx)
	return l.GetSettings(in)
}

func (s *SettingsServer) UpdateSettings(ctx context.Context, in *client.UpdateSettingsRequest) (*client.UpdateSettingsResponse, error) {
	l := settingslogic.NewUpdateSettingsLogic(ctx, s.svcCtx)
	return l.UpdateSettings(in)
}

func (s *SettingsServer) GetPreferences(ctx context.Context, in *client.GetPreferencesRequest) (*client.GetPreferencesResponse, error) {
	l := settingslogic.NewGetPreferencesLogic(ctx, s.svcCtx)
	return l.GetPreferences(in)
}

func (s *SettingsServer) UpdatePreferences(ctx context.Context, in *client.UpdatePreferencesRequest) (*client.UpdatePreferencesResponse, error) {
	l := settingslogic.NewUpdatePreferencesLogic(ctx, s.svcCtx)
	return l.UpdatePreferences(in)
}

func (s *SettingsServer) UploadAvatar(ctx context.Context, in *client.UploadAvatarRequest) (*client.UploadAvatarResponse, error) {
	l := settingslogic.NewUploadAvatarLogic(ctx, s.svcCtx)
	return l.UploadAvatar(in)
}

func (s *SettingsServer) DeleteAccount(ctx context.Context, in *client.DeleteAccountRequest) (*client.DeleteAccountResponse, error) {
	l := settingslogic.NewDeleteAccountLogic(ctx, s.svcCtx)
	return l.DeleteAccount(in)
}

func (s *SettingsServer) ExportData(ctx context.Context, in *client.ExportDataRequest) (*client.ExportDataResponse, error) {
	l := settingslogic.NewExportDataLogic(ctx, s.svcCtx)
	return l.ExportData(in)
}

func (s *SettingsServer) GetPrivacySettings(ctx context.Context, in *client.GetPrivacySettingsRequest) (*client.GetPrivacySettingsResponse, error) {
	l := settingslogic.NewGetPrivacySettingsLogic(ctx, s.svcCtx)
	return l.GetPrivacySettings(in)
}

func (s *SettingsServer) UpdatePrivacySettings(ctx context.Context, in *client.UpdatePrivacySettingsRequest) (*client.UpdatePrivacySettingsResponse, error) {
	l := settingslogic.NewUpdatePrivacySettingsLogic(ctx, s.svcCtx)
	return l.UpdatePrivacySettings(in)
}
