// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: settings.proto

package settingsservice

import (
	"context"

	"github.com/suleymanmyradov/growth-server/services/gateway/services/settings/rpc/settings"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AppPreferences                = settings.AppPreferences
	DeleteAccountRequest          = settings.DeleteAccountRequest
	DeleteAccountResponse         = settings.DeleteAccountResponse
	ExportDataRequest             = settings.ExportDataRequest
	ExportDataResponse            = settings.ExportDataResponse
	GetPreferencesRequest         = settings.GetPreferencesRequest
	GetPreferencesResponse        = settings.GetPreferencesResponse
	GetPrivacySettingsRequest     = settings.GetPrivacySettingsRequest
	GetPrivacySettingsResponse    = settings.GetPrivacySettingsResponse
	GetSettingsRequest            = settings.GetSettingsRequest
	GetSettingsResponse           = settings.GetSettingsResponse
	PrivacySettings               = settings.PrivacySettings
	UpdatePreferencesRequest      = settings.UpdatePreferencesRequest
	UpdatePreferencesResponse     = settings.UpdatePreferencesResponse
	UpdatePrivacySettingsRequest  = settings.UpdatePrivacySettingsRequest
	UpdatePrivacySettingsResponse = settings.UpdatePrivacySettingsResponse
	UpdateSettingsRequest         = settings.UpdateSettingsRequest
	UpdateSettingsResponse        = settings.UpdateSettingsResponse
	UploadAvatarRequest           = settings.UploadAvatarRequest
	UploadAvatarResponse          = settings.UploadAvatarResponse
	UserSettings                  = settings.UserSettings

	SettingsService interface {
		// User settings
		GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*GetSettingsResponse, error)
		UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*UpdateSettingsResponse, error)
		// App preferences
		GetPreferences(ctx context.Context, in *GetPreferencesRequest, opts ...grpc.CallOption) (*GetPreferencesResponse, error)
		UpdatePreferences(ctx context.Context, in *UpdatePreferencesRequest, opts ...grpc.CallOption) (*UpdatePreferencesResponse, error)
		// Avatar management
		UploadAvatar(ctx context.Context, in *UploadAvatarRequest, opts ...grpc.CallOption) (*UploadAvatarResponse, error)
		// Privacy settings
		GetPrivacySettings(ctx context.Context, in *GetPrivacySettingsRequest, opts ...grpc.CallOption) (*GetPrivacySettingsResponse, error)
		UpdatePrivacySettings(ctx context.Context, in *UpdatePrivacySettingsRequest, opts ...grpc.CallOption) (*UpdatePrivacySettingsResponse, error)
		// Data management
		ExportData(ctx context.Context, in *ExportDataRequest, opts ...grpc.CallOption) (*ExportDataResponse, error)
		DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error)
	}

	defaultSettingsService struct {
		cli zrpc.Client
	}
)

func NewSettingsService(cli zrpc.Client) SettingsService {
	return &defaultSettingsService{
		cli: cli,
	}
}

// User settings
func (m *defaultSettingsService) GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*GetSettingsResponse, error) {
	client := settings.NewSettingsServiceClient(m.cli.Conn())
	return client.GetSettings(ctx, in, opts...)
}

func (m *defaultSettingsService) UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*UpdateSettingsResponse, error) {
	client := settings.NewSettingsServiceClient(m.cli.Conn())
	return client.UpdateSettings(ctx, in, opts...)
}

// App preferences
func (m *defaultSettingsService) GetPreferences(ctx context.Context, in *GetPreferencesRequest, opts ...grpc.CallOption) (*GetPreferencesResponse, error) {
	client := settings.NewSettingsServiceClient(m.cli.Conn())
	return client.GetPreferences(ctx, in, opts...)
}

func (m *defaultSettingsService) UpdatePreferences(ctx context.Context, in *UpdatePreferencesRequest, opts ...grpc.CallOption) (*UpdatePreferencesResponse, error) {
	client := settings.NewSettingsServiceClient(m.cli.Conn())
	return client.UpdatePreferences(ctx, in, opts...)
}

// Avatar management
func (m *defaultSettingsService) UploadAvatar(ctx context.Context, in *UploadAvatarRequest, opts ...grpc.CallOption) (*UploadAvatarResponse, error) {
	client := settings.NewSettingsServiceClient(m.cli.Conn())
	return client.UploadAvatar(ctx, in, opts...)
}

// Privacy settings
func (m *defaultSettingsService) GetPrivacySettings(ctx context.Context, in *GetPrivacySettingsRequest, opts ...grpc.CallOption) (*GetPrivacySettingsResponse, error) {
	client := settings.NewSettingsServiceClient(m.cli.Conn())
	return client.GetPrivacySettings(ctx, in, opts...)
}

func (m *defaultSettingsService) UpdatePrivacySettings(ctx context.Context, in *UpdatePrivacySettingsRequest, opts ...grpc.CallOption) (*UpdatePrivacySettingsResponse, error) {
	client := settings.NewSettingsServiceClient(m.cli.Conn())
	return client.UpdatePrivacySettings(ctx, in, opts...)
}

// Data management
func (m *defaultSettingsService) ExportData(ctx context.Context, in *ExportDataRequest, opts ...grpc.CallOption) (*ExportDataResponse, error) {
	client := settings.NewSettingsServiceClient(m.cli.Conn())
	return client.ExportData(ctx, in, opts...)
}

func (m *defaultSettingsService) DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error) {
	client := settings.NewSettingsServiceClient(m.cli.Conn())
	return client.DeleteAccount(ctx, in, opts...)
}
