// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: client.proto

package articles

import (
	"context"

	"github.com/suleymanmyradov/growth-server/services/microservices/client/rpc/pb/client"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetArticleRequest         = client.GetArticleRequest
	GetArticleResponse        = client.GetArticleResponse
	GetAuthorArticlesRequest  = client.GetAuthorArticlesRequest
	GetAuthorArticlesResponse = client.GetAuthorArticlesResponse
	LikeArticleRequest        = client.LikeArticleRequest
	LikeArticleResponse       = client.LikeArticleResponse
	ListArticlesRequest       = client.ListArticlesRequest
	ListArticlesResponse      = client.ListArticlesResponse
	ShareArticleRequest       = client.ShareArticleRequest
	ShareArticleResponse      = client.ShareArticleResponse

	Articles interface {
		ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error)
		GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*GetArticleResponse, error)
		LikeArticle(ctx context.Context, in *LikeArticleRequest, opts ...grpc.CallOption) (*LikeArticleResponse, error)
		ShareArticle(ctx context.Context, in *ShareArticleRequest, opts ...grpc.CallOption) (*ShareArticleResponse, error)
		GetAuthorArticles(ctx context.Context, in *GetAuthorArticlesRequest, opts ...grpc.CallOption) (*GetAuthorArticlesResponse, error)
	}

	defaultArticles struct {
		cli zrpc.Client
	}
)

func NewArticles(cli zrpc.Client) Articles {
	return &defaultArticles{
		cli: cli,
	}
}

func (m *defaultArticles) ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error) {
	client := client.NewArticlesClient(m.cli.Conn())
	return client.ListArticles(ctx, in, opts...)
}

func (m *defaultArticles) GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*GetArticleResponse, error) {
	client := client.NewArticlesClient(m.cli.Conn())
	return client.GetArticle(ctx, in, opts...)
}

func (m *defaultArticles) LikeArticle(ctx context.Context, in *LikeArticleRequest, opts ...grpc.CallOption) (*LikeArticleResponse, error) {
	client := client.NewArticlesClient(m.cli.Conn())
	return client.LikeArticle(ctx, in, opts...)
}

func (m *defaultArticles) ShareArticle(ctx context.Context, in *ShareArticleRequest, opts ...grpc.CallOption) (*ShareArticleResponse, error) {
	client := client.NewArticlesClient(m.cli.Conn())
	return client.ShareArticle(ctx, in, opts...)
}

func (m *defaultArticles) GetAuthorArticles(ctx context.Context, in *GetAuthorArticlesRequest, opts ...grpc.CallOption) (*GetAuthorArticlesResponse, error) {
	client := client.NewArticlesClient(m.cli.Conn())
	return client.GetAuthorArticles(ctx, in, opts...)
}
