// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: conversations.proto

package server

import (
	"context"

	"github.com/suleymanmyradov/growth-server/services/microservices/conversations/rpc/internal/logic/conversationsservice"
	"github.com/suleymanmyradov/growth-server/services/microservices/conversations/rpc/internal/svc"
	"github.com/suleymanmyradov/growth-server/services/microservices/conversations/rpc/pb/conversations"
)

type ConversationsServiceServer struct {
	svcCtx *svc.ServiceContext
	conversations.UnimplementedConversationsServiceServer
}

func NewConversationsServiceServer(svcCtx *svc.ServiceContext) *ConversationsServiceServer {
	return &ConversationsServiceServer{
		svcCtx: svcCtx,
	}
}

// CRUD operations
func (s *ConversationsServiceServer) ListConversations(ctx context.Context, in *conversations.ListConversationsRequest) (*conversations.ListConversationsResponse, error) {
	l := conversationsservicelogic.NewListConversationsLogic(ctx, s.svcCtx)
	return l.ListConversations(in)
}

func (s *ConversationsServiceServer) StartConversation(ctx context.Context, in *conversations.StartConversationRequest) (*conversations.StartConversationResponse, error) {
	l := conversationsservicelogic.NewStartConversationLogic(ctx, s.svcCtx)
	return l.StartConversation(in)
}

func (s *ConversationsServiceServer) GetConversation(ctx context.Context, in *conversations.GetConversationRequest) (*conversations.GetConversationResponse, error) {
	l := conversationsservicelogic.NewGetConversationLogic(ctx, s.svcCtx)
	return l.GetConversation(in)
}

func (s *ConversationsServiceServer) UpdateConversation(ctx context.Context, in *conversations.UpdateConversationRequest) (*conversations.UpdateConversationResponse, error) {
	l := conversationsservicelogic.NewUpdateConversationLogic(ctx, s.svcCtx)
	return l.UpdateConversation(in)
}

func (s *ConversationsServiceServer) DeleteConversation(ctx context.Context, in *conversations.DeleteConversationRequest) (*conversations.DeleteConversationResponse, error) {
	l := conversationsservicelogic.NewDeleteConversationLogic(ctx, s.svcCtx)
	return l.DeleteConversation(in)
}

// Message operations
func (s *ConversationsServiceServer) SendMessage(ctx context.Context, in *conversations.SendMessageRequest) (*conversations.SendMessageResponse, error) {
	l := conversationsservicelogic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}

func (s *ConversationsServiceServer) GetMessages(ctx context.Context, in *conversations.GetMessagesRequest) (*conversations.GetMessagesResponse, error) {
	l := conversationsservicelogic.NewGetMessagesLogic(ctx, s.svcCtx)
	return l.GetMessages(in)
}

func (s *ConversationsServiceServer) ContinueConversation(ctx context.Context, in *conversations.ContinueConversationRequest) (*conversations.ContinueConversationResponse, error) {
	l := conversationsservicelogic.NewContinueConversationLogic(ctx, s.svcCtx)
	return l.ContinueConversation(in)
}

// AI features
func (s *ConversationsServiceServer) GetConversationSuggestions(ctx context.Context, in *conversations.GetConversationSuggestionsRequest) (*conversations.GetConversationSuggestionsResponse, error) {
	l := conversationsservicelogic.NewGetConversationSuggestionsLogic(ctx, s.svcCtx)
	return l.GetConversationSuggestions(in)
}

func (s *ConversationsServiceServer) RateMessage(ctx context.Context, in *conversations.RateMessageRequest) (*conversations.RateMessageResponse, error) {
	l := conversationsservicelogic.NewRateMessageLogic(ctx, s.svcCtx)
	return l.RateMessage(in)
}
