// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: habits.proto

package server

import (
	"context"

	"github.com/suleymanmyradov/growth-server/services/gateway/services/habits/rpc/habits"
	"github.com/suleymanmyradov/growth-server/services/gateway/services/habits/rpc/internal/logic"
	"github.com/suleymanmyradov/growth-server/services/gateway/services/habits/rpc/internal/svc"
)

type HabitsServiceServer struct {
	svcCtx *svc.ServiceContext
	habits.UnimplementedHabitsServiceServer
}

func NewHabitsServiceServer(svcCtx *svc.ServiceContext) *HabitsServiceServer {
	return &HabitsServiceServer{
		svcCtx: svcCtx,
	}
}

// CRUD operations
func (s *HabitsServiceServer) ListHabits(ctx context.Context, in *habits.ListHabitsRequest) (*habits.ListHabitsResponse, error) {
	l := logic.NewListHabitsLogic(ctx, s.svcCtx)
	return l.ListHabits(in)
}

func (s *HabitsServiceServer) CreateHabit(ctx context.Context, in *habits.CreateHabitRequest) (*habits.CreateHabitResponse, error) {
	l := logic.NewCreateHabitLogic(ctx, s.svcCtx)
	return l.CreateHabit(in)
}

func (s *HabitsServiceServer) GetHabit(ctx context.Context, in *habits.GetHabitRequest) (*habits.GetHabitResponse, error) {
	l := logic.NewGetHabitLogic(ctx, s.svcCtx)
	return l.GetHabit(in)
}

func (s *HabitsServiceServer) UpdateHabit(ctx context.Context, in *habits.UpdateHabitRequest) (*habits.UpdateHabitResponse, error) {
	l := logic.NewUpdateHabitLogic(ctx, s.svcCtx)
	return l.UpdateHabit(in)
}

func (s *HabitsServiceServer) DeleteHabit(ctx context.Context, in *habits.DeleteHabitRequest) (*habits.DeleteHabitResponse, error) {
	l := logic.NewDeleteHabitLogic(ctx, s.svcCtx)
	return l.DeleteHabit(in)
}

// Habit operations
func (s *HabitsServiceServer) ToggleHabit(ctx context.Context, in *habits.ToggleHabitRequest) (*habits.ToggleHabitResponse, error) {
	l := logic.NewToggleHabitLogic(ctx, s.svcCtx)
	return l.ToggleHabit(in)
}

func (s *HabitsServiceServer) ResetTodayHabits(ctx context.Context, in *habits.ResetTodayHabitsRequest) (*habits.ResetTodayHabitsResponse, error) {
	l := logic.NewResetTodayHabitsLogic(ctx, s.svcCtx)
	return l.ResetTodayHabits(in)
}

// Analytics
func (s *HabitsServiceServer) GetHabitStats(ctx context.Context, in *habits.GetHabitStatsRequest) (*habits.GetHabitStatsResponse, error) {
	l := logic.NewGetHabitStatsLogic(ctx, s.svcCtx)
	return l.GetHabitStats(in)
}

func (s *HabitsServiceServer) GetHabitCalendar(ctx context.Context, in *habits.GetHabitCalendarRequest) (*habits.GetHabitCalendarResponse, error) {
	l := logic.NewGetHabitCalendarLogic(ctx, s.svcCtx)
	return l.GetHabitCalendar(in)
}
