// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: report.proto

package server

import (
	"context"

	"github.com/suleymanmyradov/growth-server/services/gateway/services/report/rpc/internal/logic"
	"github.com/suleymanmyradov/growth-server/services/gateway/services/report/rpc/internal/svc"
	"github.com/suleymanmyradov/growth-server/services/gateway/services/report/rpc/report"
)

type ReportServiceServer struct {
	svcCtx *svc.ServiceContext
	report.UnimplementedReportServiceServer
}

func NewReportServiceServer(svcCtx *svc.ServiceContext) *ReportServiceServer {
	return &ReportServiceServer{
		svcCtx: svcCtx,
	}
}

// Report CRUD
func (s *ReportServiceServer) SubmitReport(ctx context.Context, in *report.SubmitReportRequest) (*report.SubmitReportResponse, error) {
	l := logic.NewSubmitReportLogic(ctx, s.svcCtx)
	return l.SubmitReport(in)
}

func (s *ReportServiceServer) GetReport(ctx context.Context, in *report.GetReportRequest) (*report.GetReportResponse, error) {
	l := logic.NewGetReportLogic(ctx, s.svcCtx)
	return l.GetReport(in)
}

func (s *ReportServiceServer) ListReports(ctx context.Context, in *report.ListReportsRequest) (*report.ListReportsResponse, error) {
	l := logic.NewListReportsLogic(ctx, s.svcCtx)
	return l.ListReports(in)
}

func (s *ReportServiceServer) UpdateReport(ctx context.Context, in *report.UpdateReportRequest) (*report.UpdateReportResponse, error) {
	l := logic.NewUpdateReportLogic(ctx, s.svcCtx)
	return l.UpdateReport(in)
}

func (s *ReportServiceServer) CloseReport(ctx context.Context, in *report.CloseReportRequest) (*report.CloseReportResponse, error) {
	l := logic.NewCloseReportLogic(ctx, s.svcCtx)
	return l.CloseReport(in)
}

// Report metadata
func (s *ReportServiceServer) GetReportCategories(ctx context.Context, in *report.GetReportCategoriesRequest) (*report.GetReportCategoriesResponse, error) {
	l := logic.NewGetReportCategoriesLogic(ctx, s.svcCtx)
	return l.GetReportCategories(in)
}

func (s *ReportServiceServer) GetReportStatus(ctx context.Context, in *report.GetReportStatusRequest) (*report.GetReportStatusResponse, error) {
	l := logic.NewGetReportStatusLogic(ctx, s.svcCtx)
	return l.GetReportStatus(in)
}

// Attachments
func (s *ReportServiceServer) UploadAttachment(ctx context.Context, in *report.UploadAttachmentRequest) (*report.UploadAttachmentResponse, error) {
	l := logic.NewUploadAttachmentLogic(ctx, s.svcCtx)
	return l.UploadAttachment(in)
}

// Comments
func (s *ReportServiceServer) AddReportComment(ctx context.Context, in *report.AddReportCommentRequest) (*report.AddReportCommentResponse, error) {
	l := logic.NewAddReportCommentLogic(ctx, s.svcCtx)
	return l.AddReportComment(in)
}

func (s *ReportServiceServer) GetReportComments(ctx context.Context, in *report.GetReportCommentsRequest) (*report.GetReportCommentsResponse, error) {
	l := logic.NewGetReportCommentsLogic(ctx, s.svcCtx)
	return l.GetReportComments(in)
}
