// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: client.proto

package server

import (
	"context"

	"github.com/suleymanmyradov/growth-server/services/microservices/client/rpc/internal/logic/saved"
	"github.com/suleymanmyradov/growth-server/services/microservices/client/rpc/internal/svc"
	"github.com/suleymanmyradov/growth-server/services/microservices/client/rpc/pb/client"
)

type SavedServer struct {
	svcCtx *svc.ServiceContext
	client.UnimplementedSavedServer
}

func NewSavedServer(svcCtx *svc.ServiceContext) *SavedServer {
	return &SavedServer{
		svcCtx: svcCtx,
	}
}

func (s *SavedServer) SaveItem(ctx context.Context, in *client.SaveItemRequest) (*client.SaveItemResponse, error) {
	l := savedlogic.NewSaveItemLogic(ctx, s.svcCtx)
	return l.SaveItem(in)
}

func (s *SavedServer) RemoveSaved(ctx context.Context, in *client.RemoveSavedRequest) (*client.RemoveSavedResponse, error) {
	l := savedlogic.NewRemoveSavedLogic(ctx, s.svcCtx)
	return l.RemoveSaved(in)
}

func (s *SavedServer) ListSaved(ctx context.Context, in *client.ListSavedRequest) (*client.ListSavedResponse, error) {
	l := savedlogic.NewListSavedLogic(ctx, s.svcCtx)
	return l.ListSaved(in)
}

func (s *SavedServer) GetSavedItem(ctx context.Context, in *client.GetSavedItemRequest) (*client.GetSavedItemResponse, error) {
	l := savedlogic.NewGetSavedItemLogic(ctx, s.svcCtx)
	return l.GetSavedItem(in)
}

func (s *SavedServer) CreateCollection(ctx context.Context, in *client.CreateCollectionRequest) (*client.CreateCollectionResponse, error) {
	l := savedlogic.NewCreateCollectionLogic(ctx, s.svcCtx)
	return l.CreateCollection(in)
}

func (s *SavedServer) UpdateCollection(ctx context.Context, in *client.UpdateCollectionRequest) (*client.UpdateCollectionResponse, error) {
	l := savedlogic.NewUpdateCollectionLogic(ctx, s.svcCtx)
	return l.UpdateCollection(in)
}

func (s *SavedServer) DeleteCollection(ctx context.Context, in *client.DeleteCollectionRequest) (*client.DeleteCollectionResponse, error) {
	l := savedlogic.NewDeleteCollectionLogic(ctx, s.svcCtx)
	return l.DeleteCollection(in)
}

func (s *SavedServer) ListCollections(ctx context.Context, in *client.ListCollectionsRequest) (*client.ListCollectionsResponse, error) {
	l := savedlogic.NewListCollectionsLogic(ctx, s.svcCtx)
	return l.ListCollections(in)
}

func (s *SavedServer) GetCollection(ctx context.Context, in *client.GetCollectionRequest) (*client.GetCollectionResponse, error) {
	l := savedlogic.NewGetCollectionLogic(ctx, s.svcCtx)
	return l.GetCollection(in)
}

func (s *SavedServer) MoveToCollection(ctx context.Context, in *client.MoveToCollectionRequest) (*client.MoveToCollectionResponse, error) {
	l := savedlogic.NewMoveToCollectionLogic(ctx, s.svcCtx)
	return l.MoveToCollection(in)
}

func (s *SavedServer) GetSavedStats(ctx context.Context, in *client.GetSavedStatsRequest) (*client.GetSavedStatsResponse, error) {
	l := savedlogic.NewGetSavedStatsLogic(ctx, s.svcCtx)
	return l.GetSavedStats(in)
}

func (s *SavedServer) ExportSaved(ctx context.Context, in *client.ExportSavedRequest) (*client.ExportSavedResponse, error) {
	l := savedlogic.NewExportSavedLogic(ctx, s.svcCtx)
	return l.ExportSaved(in)
}
