// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: client.proto

package server

import (
	"context"

	"github.com/suleymanmyradov/growth-server/services/microservices/client/rpc/internal/logic/habittemplates"
	"github.com/suleymanmyradov/growth-server/services/microservices/client/rpc/internal/svc"
	"github.com/suleymanmyradov/growth-server/services/microservices/client/rpc/pb/client"
)

type HabitTemplatesServer struct {
	svcCtx *svc.ServiceContext
	client.UnimplementedHabitTemplatesServer
}

func NewHabitTemplatesServer(svcCtx *svc.ServiceContext) *HabitTemplatesServer {
	return &HabitTemplatesServer{
		svcCtx: svcCtx,
	}
}

func (s *HabitTemplatesServer) ListHabitTemplates(ctx context.Context, in *client.ListHabitTemplatesRequest) (*client.ListHabitTemplatesResponse, error) {
	l := habittemplateslogic.NewListHabitTemplatesLogic(ctx, s.svcCtx)
	return l.ListHabitTemplates(in)
}
