// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: client.proto

package categories

import (
	"context"

	"github.com/suleymanmyradov/growth-server/services/microservices/client/rpc/pb/client"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ListCategoriesRequest  = client.ListCategoriesRequest
	ListCategoriesResponse = client.ListCategoriesResponse

	Categories interface {
		ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
	}

	defaultCategories struct {
		cli zrpc.Client
	}
)

func NewCategories(cli zrpc.Client) Categories {
	return &defaultCategories{
		cli: cli,
	}
}

func (m *defaultCategories) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	client := client.NewCategoriesClient(m.cli.Conn())
	return client.ListCategories(ctx, in, opts...)
}
